import type { SerieBClub } from "./types";

/**
 * Avellino, Bari, Carrarese, Catanzaro, Cesena.
 *
 * Vedi `types.ts` per cosa qui è fattuale (nome, data di nascita, nazionalità, reparto) e
 * cosa è nostra stima dichiarata (casella puntuale e Overall).
 */
export const CLUBS_01: SerieBClub[] = [
  {
    // Neopromossa dalla Serie C, rosa costruita per la salvezza tranquilla ma con un
    // attacco di categoria superiore: Tutino è uno dei realizzatori più forti della B.
    name: "Avellino",
    prestigeTier: 1,
    players: [
      { name: "Antony Iannarilli", nation: "Italia", birthDate: "1990-12-18", role: "POR", overall: 63 },
      { name: "Leonardo Marson", nation: "Italia", birthDate: "1998-01-05", role: "POR", overall: 60 },
      { name: "Pasquale Pane", nation: "Italia", birthDate: "1990-03-11", role: "POR", overall: 60 },
      { name: "Filippo Missori", nation: "Italia", birthDate: "2004-03-24", role: "TD", secondaryRoles: ["QD"], overall: 63 },
      { name: "Tommaso Cancellotti", nation: "Italia", birthDate: "1992-05-22", role: "TD", secondaryRoles: ["QD"], overall: 62 },
      { name: "Armando Izzo", nation: "Italia", birthDate: "1992-03-02", role: "DC", overall: 68 },
      { name: "Lorenco Šimić", nation: "Croazia", birthDate: "1996-07-15", role: "DC", overall: 63 },
      { name: "Alessandro Fontanarosa", nation: "Italia", birthDate: "2003-02-07", role: "DC", overall: 61 },
      { name: "Patrick Enrici", nation: "Italia", birthDate: "2001-05-02", role: "DC", overall: 60 },
      { name: "Marco Sala", nation: "Italia", birthDate: "1999-06-04", role: "TS", secondaryRoles: ["QS"], overall: 62 },
      { name: "Alessandro Milani", nation: "Venezuela", birthDate: "2005-06-14", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Luca Palmiero", nation: "Italia", birthDate: "1996-05-01", role: "MED", overall: 64 },
      { name: "Marco Armellino", nation: "Italia", birthDate: "1989-08-21", role: "MED", overall: 62 },
      { name: "Dimitris Sounas", nation: "Grecia", birthDate: "1994-08-12", role: "CC", overall: 64 },
      { name: "Martin Palumbo", nation: "Norvegia", birthDate: "2002-03-05", role: "CC", overall: 60 },
      { name: "Andréa Le Borgne", nation: "Francia", birthDate: "2006-07-27", role: "CC", overall: 60 },
      { name: "Justin Kumi", nation: "Italia", birthDate: "2004-07-16", role: "ED", overall: 60 },
      { name: "Michele Besaggio", nation: "Italia", birthDate: "2002-04-28", role: "ES", overall: 60 },
      { name: "Gennaro Tutino", nation: "Italia", birthDate: "1996-08-20", role: "ATT", secondaryRoles: ["TQS"], overall: 70 },
      { name: "Cosimo Patierno", nation: "Italia", birthDate: "1991-03-01", role: "ATT", overall: 66 },
      { name: "Tommaso Biasci", nation: "Italia", birthDate: "1994-11-10", role: "ATT", overall: 63 },
      { name: "Andrea Favilli", nation: "Italia", birthDate: "1997-05-17", role: "ATT", overall: 63 },
      { name: "Roberto Insigne", nation: "Italia", birthDate: "1994-05-11", role: "TQS", secondaryRoles: ["ES"], overall: 67 },
      { name: "Luca Pandolfi", nation: "Italia", birthDate: "1998-03-14", role: "TQD", overall: 62 },
      { name: "Luca D'Andrea", nation: "Italia", birthDate: "2004-09-06", role: "TQD", overall: 61 },
    ],
  },
  {
    // Piazza da Serie A per storia e pubblico, rosa da alta classifica: Maggiore e Moncini
    // sono innesti di categoria superiore.
    name: "Bari",
    prestigeTier: 2,
    players: [
      { name: "Marco Pissardo", nation: "Italia", birthDate: "1998-01-08", role: "POR", overall: 64 },
      { name: "Michele Cerofolini", nation: "Italia", birthDate: "1999-01-04", role: "POR", overall: 63 },
      { name: "Davide Marfella", nation: "Italia", birthDate: "1999-09-15", role: "POR", overall: 60 },
      { name: "Lorenzo Dickmann", nation: "Italia", birthDate: "1996-09-24", role: "TD", secondaryRoles: ["QD"], overall: 65 },
      { name: "Tomás Esteves", nation: "Portogallo", birthDate: "2002-04-03", role: "TD", secondaryRoles: ["QD"], overall: 63 },
      { name: "Dimitris Nikolaou", nation: "Grecia", birthDate: "1998-08-13", role: "DC", overall: 67 },
      { name: "Andrea Cistana", nation: "Italia", birthDate: "1997-04-01", role: "DC", overall: 65 },
      { name: "Valerio Mantovani", nation: "Italia", birthDate: "1996-04-18", role: "DC", overall: 64 },
      { name: "Cas Odenthal", nation: "Paesi Bassi", birthDate: "2000-09-26", role: "DC", overall: 63 },
      { name: "Raffaele Pucino", nation: "Italia", birthDate: "1991-05-03", role: "TS", secondaryRoles: ["QS"], overall: 64 },
      { name: "Riccardo Burgio", nation: "Italia", birthDate: "2001-05-05", role: "TS", secondaryRoles: ["QS"], overall: 61 },
      { name: "Giulio Maggiore", nation: "Italia", birthDate: "1998-03-12", role: "MED", secondaryRoles: ["CC"], overall: 70 },
      { name: "Ebrima Darboe", nation: "Gambia", birthDate: "2001-06-06", role: "MED", overall: 63 },
      { name: "Matthias Verreth", nation: "Belgio", birthDate: "1998-02-20", role: "CC", overall: 67 },
      { name: "Matthias Braunöder", nation: "Austria", birthDate: "2002-03-27", role: "CC", overall: 63 },
      { name: "Riccardo Pagano", nation: "Italia", birthDate: "2004-11-28", role: "CC", overall: 62 },
      { name: "Nicola Bellomo", nation: "Italia", birthDate: "1991-02-18", role: "TRQ", overall: 66 },
      { name: "Mehdi Dorval", nation: "Algeria", birthDate: "2001-02-09", role: "ES", secondaryRoles: ["TS"], overall: 67 },
      { name: "Federico Artioli", nation: "Italia", birthDate: "2001-06-12", role: "ED", overall: 61 },
      { name: "Gabriele Moncini", nation: "Italia", birthDate: "1996-04-26", role: "ATT", overall: 68 },
      { name: "Christian Gytkjær", nation: "Danimarca", birthDate: "1990-05-06", role: "ATT", overall: 67 },
      { name: "Marvin Çuni", nation: "Albania", birthDate: "2001-07-10", role: "ATT", overall: 61 },
      { name: "Giuseppe Sibilli", nation: "Italia", birthDate: "1996-08-07", role: "TQS", overall: 67 },
      { name: "Anthony Partipilo", nation: "Italia", birthDate: "1994-10-27", role: "TQD", overall: 64 },
      { name: "Kevin Piscopo", nation: "Italia", birthDate: "1998-02-06", role: "TQD", overall: 62 },
    ],
  },
  {
    // Rosa corta e giovane, obiettivo salvezza: Salamon e Torregrossa sono l'esperienza che
    // tiene in piedi il reparto.
    name: "Carrarese",
    prestigeTier: 1,
    players: [
      { name: "Marco Bleve", nation: "Italia", birthDate: "1995-10-18", role: "POR", overall: 63 },
      { name: "Vincenzo Fiorillo", nation: "Italia", birthDate: "1990-01-13", role: "POR", overall: 62 },
      { name: "Stefano Mazzini", nation: "Italia", birthDate: "1998-12-06", role: "POR", overall: 60 },
      { name: "Devid Eugene Bouah", nation: "Italia", birthDate: "2001-08-13", role: "TD", secondaryRoles: ["QD"], overall: 61 },
      { name: "Simone Zanon", nation: "Italia", birthDate: "2001-08-30", role: "TD", secondaryRoles: ["QD"], overall: 60 },
      { name: "Bartosz Salamon", nation: "Polonia", birthDate: "1991-05-01", role: "DC", overall: 66 },
      { name: "Julián Illanes", nation: "Argentina", birthDate: "1997-03-10", role: "DC", overall: 63 },
      { name: "Filippo Oliana", nation: "Italia", birthDate: "1999-06-30", role: "DC", overall: 61 },
      { name: "Fabio Ruggeri", nation: "Italia", birthDate: "2004-12-13", role: "DC", overall: 60 },
      { name: "Nicolò Calabrese", nation: "Italia", birthDate: "2004-11-16", role: "DC", overall: 60 },
      { name: "Marco Imperiale", nation: "Italia", birthDate: "1999-05-01", role: "TS", secondaryRoles: ["QS"], overall: 61 },
      { name: "Jonas Rouhi", nation: "Svezia", birthDate: "2004-01-07", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Nicolás Schiavi", nation: "Argentina", birthDate: "1995-02-01", role: "MED", overall: 64 },
      { name: "Emanuele Zuelli", nation: "Italia", birthDate: "2001-11-22", role: "MED", overall: 62 },
      { name: "Filippo Melegoni", nation: "Italia", birthDate: "1999-02-18", role: "CC", overall: 65 },
      { name: "Luis Hasa", nation: "Italia", birthDate: "2004-01-06", role: "CC", overall: 62 },
      { name: "Antonio Troise", nation: "Italia", birthDate: "2005-04-24", role: "CC", overall: 60 },
      { name: "Niccolò Belloni", nation: "Italia", birthDate: "1994-07-10", role: "ED", overall: 62 },
      { name: "Dachi Lordkipanidze", nation: "Georgia", birthDate: "2005-03-08", role: "ES", overall: 60 },
      { name: "Federico Accornero", nation: "Italia", birthDate: "2004-02-05", role: "TRQ", overall: 60 },
      { name: "Ernesto Torregrossa", nation: "Venezuela", birthDate: "1992-06-28", role: "ATT", overall: 65 },
      { name: "Mattia Finotto", nation: "Italia", birthDate: "1992-12-28", role: "ATT", overall: 64 },
      { name: "Fabio Abiuso", nation: "Italia", birthDate: "2003-02-02", role: "ATT", overall: 61 },
      { name: "Filippo Distefano", nation: "Italia", birthDate: "2003-08-28", role: "TQD", overall: 63 },
      { name: "Nikola Sekulov", nation: "Italia", birthDate: "2002-02-18", role: "TQS", overall: 63 },
    ],
  },
  {
    // Squadra da metà classifica alta con un centravanti da categoria superiore (Iemmello)
    // e un trequartista di scuola francese (Oudin).
    name: "Catanzaro",
    prestigeTier: 1,
    players: [
      { name: "Mirko Pigliacelli", nation: "Italia", birthDate: "1993-06-30", role: "POR", overall: 67 },
      { name: "Christian Marietta", nation: "Italia", birthDate: "2002-04-14", role: "POR", overall: 60 },
      { name: "Edoardo Borrelli", nation: "Italia", birthDate: "2004-07-23", role: "POR", overall: 60 },
      { name: "Tommaso Cassandro", nation: "Italia", birthDate: "2000-01-09", role: "TD", secondaryRoles: ["QD"], overall: 64 },
      { name: "Matias Antonini", nation: "Brasile", birthDate: "1998-04-09", role: "DC", overall: 64 },
      { name: "Nicolò Brighenti", nation: "Italia", birthDate: "1989-08-01", role: "DC", overall: 63 },
      { name: "Ruggero Frosinini", nation: "Italia", birthDate: "2001-02-16", role: "DC", overall: 61 },
      { name: "Ervin Bashi", nation: "Albania", birthDate: "2005-07-24", role: "DC", overall: 60 },
      { name: "Fellipe Jack", nation: "Brasile", birthDate: "2006-01-12", role: "DC", overall: 60 },
      { name: "Gonçalo Esteves", nation: "Portogallo", birthDate: "2004-02-27", role: "TS", secondaryRoles: ["QS"], overall: 63 },
      { name: "Bruno Verrengia", nation: "Italia", birthDate: "2003-09-22", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Jacopo Petriccione", nation: "Italia", birthDate: "1995-02-22", role: "MED", overall: 64 },
      { name: "Davide Buglio", nation: "Italia", birthDate: "1998-02-26", role: "MED", overall: 62 },
      { name: "Simone Pontisso", nation: "Italia", birthDate: "1997-03-20", role: "CC", overall: 64 },
      { name: "Marco Pompetti", nation: "Italia", birthDate: "2000-05-22", role: "CC", overall: 64 },
      { name: "Costantino Favasuli", nation: "Italia", birthDate: "2004-04-26", role: "ED", overall: 62 },
      { name: "Patrick Nuamah", nation: "Italia", birthDate: "2005-12-31", role: "ES", overall: 60 },
      { name: "Rémi Oudin", nation: "Francia", birthDate: "1996-11-18", role: "TRQ", overall: 68 },
      { name: "Pietro Iemmello", nation: "Italia", birthDate: "1992-03-06", role: "ATT", overall: 70 },
      { name: "Filippo Pittarello", nation: "Italia", birthDate: "1996-10-09", role: "ATT", overall: 64 },
      { name: "Federico Di Francesco", nation: "Italia", birthDate: "1994-06-14", role: "TQS", secondaryRoles: ["ES"], overall: 67 },
      { name: "Mattia Liberali", nation: "Italia", birthDate: "2007-04-06", role: "TQS", overall: 62 },
      { name: "Marco D'Alessandro", nation: "Italia", birthDate: "1991-02-17", role: "TQD", overall: 65 },
      { name: "N'Dri Koffi", nation: "Francia", birthDate: "2002-03-09", role: "TQD", overall: 62 },
    ],
  },
  {
    // Rosa profonda e ambiziosa: Castrovilli è l'ex nazionale che alza il livello del
    // reparto, davanti c'è abbondanza vera.
    name: "Cesena",
    prestigeTier: 1,
    players: [
      { name: "Jonathan Klinsmann", nation: "Stati Uniti", birthDate: "1997-04-08", role: "POR", overall: 65 },
      { name: "Alessandro Siano", nation: "Italia", birthDate: "2001-04-28", role: "POR", overall: 60 },
      { name: "Luca Ferretti", nation: "Italia", birthDate: "2003-12-23", role: "POR", overall: 60 },
      { name: "Tommaso Corazza", nation: "Italia", birthDate: "2004-06-29", role: "TD", secondaryRoles: ["QD"], overall: 62 },
      { name: "Andrea Ciofi", nation: "Italia", birthDate: "1999-06-28", role: "DC", secondaryRoles: ["TD"], overall: 63 },
      { name: "Giovanni Zaro", nation: "Italia", birthDate: "1994-05-12", role: "DC", overall: 64 },
      { name: "Massimiliano Mangraviti", nation: "Italia", birthDate: "1998-01-24", role: "DC", overall: 64 },
      { name: "Matteo Piacentini", nation: "Italia", birthDate: "1999-04-20", role: "DC", overall: 62 },
      { name: "Peter Amoran", nation: "Svezia", birthDate: "2004-05-22", role: "DC", overall: 60 },
      { name: "Gianluca Frabotta", nation: "Italia", birthDate: "1999-06-24", role: "TS", secondaryRoles: ["QS"], overall: 63 },
      { name: "Vittorio Magni", nation: "Italia", birthDate: "2006-06-01", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Michele Castagnetti", nation: "Italia", birthDate: "1989-12-27", role: "MED", overall: 65 },
      { name: "Dimitri Bisoli", nation: "Italia", birthDate: "1994-03-25", role: "MED", overall: 64 },
      { name: "Tommaso Berti", nation: "Italia", birthDate: "2004-03-07", role: "CC", overall: 65 },
      { name: "Tommaso Arrigoni", nation: "Italia", birthDate: "1994-02-26", role: "CC", overall: 63 },
      { name: "Matteo Guidi", nation: "Italia", birthDate: "2003-07-03", role: "CC", overall: 61 },
      { name: "Simone Bastoni", nation: "Italia", birthDate: "1996-11-05", role: "ES", secondaryRoles: ["TS"], overall: 67 },
      { name: "Gaetano Castrovilli", nation: "Italia", birthDate: "1997-02-17", role: "TRQ", secondaryRoles: ["CC"], overall: 71 },
      { name: "Alberto Cerri", nation: "Italia", birthDate: "1996-04-16", role: "ATT", overall: 68 },
      { name: "Cristian Shpendi", nation: "Albania", birthDate: "2003-05-19", role: "ATT", overall: 68 },
      { name: "Giacomo Vrioni", nation: "Italia", birthDate: "1998-10-15", role: "ATT", overall: 66 },
      { name: "Ibrahima Papa Wade", nation: "Italia", birthDate: "2006-10-08", role: "ATT", overall: 60 },
      { name: "Riccardo Ciervo", nation: "Italia", birthDate: "2002-04-01", role: "TQS", overall: 65 },
      { name: "Marco Olivieri", nation: "Italia", birthDate: "1999-06-30", role: "TQD", overall: 63 },
    ],
  },
];
