import type { SerieBClub } from "./types";

/** Sampdoria, Spezia, Südtirol, Venezia, Virtus Entella. */
export const CLUBS_04: SerieBClub[] = [
  {
    // La rosa più costosa della categoria dopo Monza, e la più discontinua: Barák è il
    // valore assoluto più alto del reparto centrocampo in tutta la Serie B.
    name: "Sampdoria",
    prestigeTier: 2,
    players: [
      { name: "Nicola Ravaglia", nation: "Italia", birthDate: "1988-12-12", role: "POR", overall: 64 },
      { name: "Gaëtan Coucke", nation: "Belgio", birthDate: "1998-12-03", role: "POR", overall: 63 },
      { name: "Simone Ghidotti", nation: "Italia", birthDate: "2000-03-19", role: "POR", overall: 62 },
      { name: "Fabio Depaoli", nation: "Italia", birthDate: "1997-04-24", role: "TD", secondaryRoles: ["QD"], overall: 66 },
      { name: "Lorenzo Venuti", nation: "Italia", birthDate: "1995-04-12", role: "TD", secondaryRoles: ["QD"], overall: 64 },
      { name: "Mattia Viti", nation: "Italia", birthDate: "2002-01-24", role: "DC", secondaryRoles: ["TS"], overall: 68 },
      { name: "Alex Ferrari", nation: "Italia", birthDate: "1994-07-01", role: "DC", overall: 65 },
      { name: "Dennis Hadžikadunić", nation: "Bosnia ed Erzegovina", birthDate: "1998-07-09", role: "DC", overall: 65 },
      { name: "Alessandro Pio Riccio", nation: "Italia", birthDate: "2002-02-06", role: "DC", overall: 63 },
      { name: "Simone Giordano", nation: "Italia", birthDate: "2001-12-21", role: "TS", secondaryRoles: ["QS"], overall: 62 },
      { name: "Salvatore Esposito", nation: "Italia", birthDate: "2000-10-07", role: "MED", overall: 68 },
      { name: "Matteo Ricci", nation: "Italia", birthDate: "1994-05-27", role: "MED", overall: 67 },
      { name: "Oliver Abildgaard", nation: "Danimarca", birthDate: "1996-06-10", role: "MED", overall: 66 },
      { name: "Jordan Ferri", nation: "Francia", birthDate: "1992-03-12", role: "CC", overall: 65 },
      { name: "Liam Henderson", nation: "Scozia", birthDate: "1996-04-25", role: "CC", overall: 64 },
      { name: "Alessandro Di Pardo", nation: "Italia", birthDate: "1999-07-18", role: "ED", secondaryRoles: ["TD"], overall: 62 },
      { name: "Francesco Conti", nation: "Italia", birthDate: "2004-10-23", role: "ES", overall: 60 },
      { name: "Antonín Barák", nation: "Rep. Ceca", birthDate: "1994-12-03", role: "TRQ", secondaryRoles: ["CC"], overall: 72 },
      { name: "Simone Pafundi", nation: "Italia", birthDate: "2006-03-14", role: "TRQ", overall: 64 },
      { name: "Luigi Cherubini", nation: "Italia", birthDate: "2004-01-15", role: "TQS", overall: 63 },
      { name: "Nicholas Pierini", nation: "Italia", birthDate: "1998-08-06", role: "TQD", overall: 63 },
      { name: "Matteo Brunori", nation: "Brasile", birthDate: "1994-11-01", role: "ATT", overall: 70 },
      { name: "Massimo Coda", nation: "Italia", birthDate: "1988-11-10", role: "ATT", overall: 68 },
      { name: "Edoardo Soleri", nation: "Italia", birthDate: "1997-10-19", role: "ATT", overall: 65 },
    ],
  },
  {
    // Squadra da promozione diretta: Lapadula davanti e un centrocampo che in B è di
    // categoria superiore.
    name: "Spezia",
    prestigeTier: 2,
    players: [
      { name: "Boris Radunović", nation: "Serbia", birthDate: "1996-05-26", role: "POR", overall: 67 },
      { name: "Mouhamadou Sarr", nation: "Senegal", birthDate: "1997-01-05", role: "POR", overall: 63 },
      { name: "Leonardo Loria", nation: "Italia", birthDate: "1999-03-28", role: "POR", overall: 61 },
      { name: "Leonardo Sernicola", nation: "Italia", birthDate: "1997-07-30", role: "TD", secondaryRoles: ["QD", "ED"], overall: 65 },
      { name: "Luca Vignali", nation: "Italia", birthDate: "1996-01-11", role: "TD", secondaryRoles: ["QD"], overall: 64 },
      { name: "Petko Hristov", nation: "Bulgaria", birthDate: "1999-03-01", role: "DC", overall: 66 },
      { name: "Aleš Matějů", nation: "Rep. Ceca", birthDate: "1996-06-03", role: "DC", overall: 66 },
      { name: "Giovanni Bonfanti", nation: "Italia", birthDate: "2003-01-17", role: "DC", overall: 63 },
      { name: "Marco Ruggero", nation: "Italia", birthDate: "2000-06-01", role: "DC", overall: 61 },
      { name: "Pietro Beruatto", nation: "Italia", birthDate: "1998-12-21", role: "TS", secondaryRoles: ["QS"], overall: 66 },
      { name: "Giuseppe Aurelio", nation: "Italia", birthDate: "2000-03-22", role: "TS", secondaryRoles: ["QS"], overall: 63 },
      { name: "Ádám Nagy", nation: "Ungheria", birthDate: "1995-06-17", role: "MED", overall: 68 },
      { name: "Francesco Cassata", nation: "Italia", birthDate: "1997-07-16", role: "MED", overall: 65 },
      { name: "Szymon Żurkowski", nation: "Polonia", birthDate: "1997-09-25", role: "CC", overall: 68 },
      { name: "Filippo Bandinelli", nation: "Italia", birthDate: "1995-03-29", role: "CC", overall: 67 },
      { name: "Alessandro Bellemo", nation: "Italia", birthDate: "1995-08-07", role: "CC", overall: 65 },
      { name: "Emanuele Adamo", nation: "Italia", birthDate: "1998-07-19", role: "CC", overall: 63 },
      { name: "Alessandro Romano", nation: "Svizzera", birthDate: "2006-06-17", role: "CC", overall: 60 },
      { name: "Hamse Shagaxle", nation: "Svezia", birthDate: "2005-05-16", role: "ES", overall: 60 },
      { name: "Mattia Valoti", nation: "Italia", birthDate: "1993-09-06", role: "TRQ", overall: 67 },
      { name: "Vanja Vlahović", nation: "Serbia", birthDate: "2005-11-26", role: "TQS", overall: 63 },
      { name: "Laurs Skjellerup", nation: "Danimarca", birthDate: "2002-08-12", role: "TQD", overall: 62 },
      { name: "Gianluca Lapadula", nation: "Perù", birthDate: "1990-02-07", role: "ATT", overall: 71 },
      { name: "Gabriele Artistico", nation: "Italia", birthDate: "2002-07-14", role: "ATT", overall: 64 },
      { name: "Giuseppe Di Serio", nation: "Italia", birthDate: "2001-07-20", role: "ATT", overall: 64 },
    ],
  },
  {
    // La squadra più solida e meno spettacolare della categoria: pochi gol, pochi gol
    // subiti, e due ex Serie A (Cragno, Verdi) a fare da riferimento.
    name: "Südtirol",
    prestigeTier: 1,
    players: [
      { name: "Alessio Cragno", nation: "Italia", birthDate: "1994-06-28", role: "POR", overall: 67 },
      { name: "Marius Adamonis", nation: "Lituania", birthDate: "1997-05-13", role: "POR", overall: 62 },
      { name: "Daniele Borra", nation: "Italia", birthDate: "1995-07-28", role: "POR", overall: 60 },
      { name: "Federico Davi", nation: "Italia", birthDate: "2002-04-02", role: "TD", secondaryRoles: ["QD"], overall: 60 },
      { name: "Patrik Hofer", nation: "Italia", birthDate: "2006-03-19", role: "TD", secondaryRoles: ["QD"], overall: 60 },
      { name: "Frédéric Veseli", nation: "Albania", birthDate: "1992-11-20", role: "DC", overall: 63 },
      { name: "Nicola Pietrangeli", nation: "Italia", birthDate: "2000-07-19", role: "DC", overall: 61 },
      { name: "Hamza El Kaouakibi", nation: "Marocco", birthDate: "1998-05-22", role: "DC", overall: 61 },
      { name: "Filipe Bordon", nation: "Brasile", birthDate: "2005-06-24", role: "DC", overall: 60 },
      { name: "Raphael Kofler", nation: "Italia", birthDate: "2005-04-26", role: "DC", overall: 60 },
      { name: "Simone Davi", nation: "Italia", birthDate: "1999-09-16", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Mamadou Coulibaly", nation: "Senegal", birthDate: "1999-03-02", role: "MED", overall: 62 },
      { name: "Fabian Tait", nation: "Italia", birthDate: "1993-02-10", role: "MED", overall: 62 },
      { name: "Domen Črnigoj", nation: "Slovenia", birthDate: "1995-11-18", role: "CC", overall: 63 },
      { name: "Daniele Casiraghi", nation: "Italia", birthDate: "1993-03-10", role: "CC", overall: 63 },
      { name: "Marco Frigerio", nation: "Italia", birthDate: "2001-07-16", role: "CC", overall: 60 },
      { name: "Simone Tronchin", nation: "Italia", birthDate: "2002-10-17", role: "CC", overall: 60 },
      { name: "Salvatore Molina", nation: "Italia", birthDate: "1992-01-01", role: "ED", secondaryRoles: ["TD"], overall: 62 },
      { name: "Karim Zedadka", nation: "Italia", birthDate: "2000-06-09", role: "ES", secondaryRoles: ["TS"], overall: 61 },
      { name: "Simone Verdi", nation: "Italia", birthDate: "1992-07-12", role: "TQS", secondaryRoles: ["TRQ"], overall: 68 },
      { name: "Silvio Merkaj", nation: "Albania", birthDate: "1997-12-04", role: "ATT", overall: 62 },
      { name: "Raphael Odogwu", nation: "Italia", birthDate: "1991-01-28", role: "ATT", overall: 62 },
      { name: "Emanuele Pecorino", nation: "Italia", birthDate: "2001-07-15", role: "ATT", overall: 61 },
      { name: "Riccardo Tonin", nation: "Italia", birthDate: "2001-01-30", role: "ATT", overall: 60 },
    ],
  },
  {
    // Retrocessa dalla Serie A con una rosa internazionale rimasta quasi intatta: insieme a
    // Monza, Palermo ed Empoli è la squadra da battere.
    name: "Venezia",
    prestigeTier: 2,
    players: [
      { name: "Filip Stanković", nation: "Serbia", birthDate: "2002-02-25", role: "POR", overall: 70 },
      { name: "Alessandro Plizzari", nation: "Italia", birthDate: "2000-03-12", role: "POR", overall: 63 },
      { name: "Matteo Grandi", nation: "Italia", birthDate: "1992-10-12", role: "POR", overall: 60 },
      { name: "Michael Venturi", nation: "Italia", birthDate: "1999-01-23", role: "TD", secondaryRoles: ["QD"], overall: 63 },
      { name: "Ahmed Sidibe", nation: "Francia", birthDate: "2002-02-10", role: "TD", secondaryRoles: ["QD"], overall: 60 },
      { name: "Michael Svoboda", nation: "Austria", birthDate: "1998-10-15", role: "DC", overall: 66 },
      { name: "Marin Šverko", nation: "Croazia", birthDate: "1998-02-04", role: "DC", overall: 66 },
      { name: "Joël Schingtienne", nation: "Belgio", birthDate: "2002-08-14", role: "DC", overall: 63 },
      { name: "Seid Korač", nation: "Lussemburgo", birthDate: "2001-10-20", role: "DC", overall: 63 },
      { name: "Richie Sagrado", nation: "Belgio", birthDate: "2004-01-30", role: "DC", overall: 60 },
      { name: "Ridgeciano Haps", nation: "Suriname", birthDate: "1993-06-12", role: "TS", secondaryRoles: ["QS"], overall: 67 },
      { name: "Alfred Duncan", nation: "Ghana", birthDate: "1993-03-10", role: "MED", overall: 70 },
      { name: "Nunzio Lella", nation: "Italia", birthDate: "2000-07-28", role: "MED", overall: 63 },
      { name: "Gianluca Busio", nation: "Stati Uniti", birthDate: "2002-05-28", role: "CC", secondaryRoles: ["TRQ"], overall: 69 },
      { name: "Kike Pérez", nation: "Spagna", birthDate: "1997-02-14", role: "CC", overall: 65 },
      { name: "Issa Doumbia", nation: "Italia", birthDate: "2003-10-16", role: "CC", overall: 62 },
      { name: "Antoine Hainaut", nation: "Francia", birthDate: "2002-02-18", role: "CC", overall: 61 },
      { name: "Matteo Dagasso", nation: "Italia", birthDate: "2004-04-01", role: "CC", overall: 60 },
      { name: "Bjarki Steinn Bjarkason", nation: "Islanda", birthDate: "2000-05-11", role: "ES", overall: 62 },
      { name: "John Yeboah", nation: "Ecuador", birthDate: "2000-06-23", role: "TQS", overall: 65 },
      { name: "Marko Farji", nation: "Iraq", birthDate: "2004-03-16", role: "TQD", overall: 62 },
      { name: "Andrea Adorante", nation: "Italia", birthDate: "2000-02-05", role: "ATT", overall: 65 },
      { name: "Antonio Casas", nation: "Spagna", birthDate: "2000-03-30", role: "ATT", overall: 64 },
      { name: "Lion Lauberbach", nation: "Germania", birthDate: "1998-02-15", role: "ATT", overall: 63 },
    ],
  },
  {
    // Neopromossa e la rosa più modesta del campionato: nessun giocatore sopra 63, ed è il
    // pavimento con cui si misura tutta la banda editoriale della Serie B.
    name: "Virtus Entella",
    prestigeTier: 1,
    players: [
      { name: "Simone Colombi", nation: "Italia", birthDate: "1991-07-01", role: "POR", overall: 62 },
      { name: "Federico Del Frate", nation: "Italia", birthDate: "1995-12-21", role: "POR", overall: 60 },
      { name: "Ovidijus Šiaulys", nation: "Lituania", birthDate: "1999-07-19", role: "POR", overall: 60 },
      { name: "Luca Parodi", nation: "Italia", birthDate: "1995-04-06", role: "TD", secondaryRoles: ["QD"], overall: 61 },
      { name: "Antonio Boccadamo", nation: "Italia", birthDate: "1999-07-24", role: "TD", secondaryRoles: ["QD"], overall: 60 },
      { name: "Ivan Marconi", nation: "Italia", birthDate: "1989-10-25", role: "DC", overall: 62 },
      { name: "Andrea Tiritiello", nation: "Italia", birthDate: "1995-03-28", role: "DC", overall: 62 },
      { name: "Mattia Alborghetti", nation: "Italia", birthDate: "1998-10-01", role: "DC", overall: 61 },
      { name: "Alessandro Pilati", nation: "Italia", birthDate: "2000-03-26", role: "DC", overall: 60 },
      { name: "Riccardo Turicchia", nation: "Italia", birthDate: "2003-02-05", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Stefano Di Mario", nation: "Italia", birthDate: "2004-10-17", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Marco Nichetti", nation: "Italia", birthDate: "1996-12-22", role: "MED", overall: 61 },
      { name: "Andrea Franzoni", nation: "Italia", birthDate: "1997-03-24", role: "MED", overall: 61 },
      { name: "Nermin Karić", nation: "Svezia", birthDate: "1999-07-23", role: "CC", overall: 61 },
      { name: "Davide Bariti", nation: "Italia", birthDate: "1991-07-07", role: "CC", overall: 61 },
      { name: "Leonardo Benedetti", nation: "Italia", birthDate: "2000-06-06", role: "CC", overall: 60 },
      { name: "Niccolò Squizzato", nation: "Italia", birthDate: "2002-01-07", role: "CC", overall: 60 },
      { name: "Ernesto Matteazzi", nation: "Italia", birthDate: "2005-01-11", role: "CC", overall: 60 },
      { name: "Francesco Mezzoni", nation: "Italia", birthDate: "2000-05-27", role: "ED", overall: 60 },
      { name: "Marco Dalla Vecchia", nation: "Italia", birthDate: "2005-02-13", role: "ES", overall: 60 },
      { name: "Mattia Tirelli", nation: "Italia", birthDate: "2002-06-30", role: "TQD", overall: 60 },
      { name: "Luigi Cuppone", nation: "Italia", birthDate: "1997-08-06", role: "ATT", overall: 63 },
      { name: "Bernat Guiu", nation: "Spagna", birthDate: "2000-09-20", role: "ATT", overall: 60 },
      { name: "Davide Pio Stabile", nation: "Italia", birthDate: "2004-08-21", role: "ATT", overall: 60 },
    ],
  },
];
