import type { SerieBClub } from "./types";

/** Monza, Padova, Palermo, Pescara, Reggiana. */
export const CLUBS_03: SerieBClub[] = [
  {
    // La rosa più forte del campionato: metà squadra ha giocato in Serie A l'anno prima e
    // Pessina è il tetto della banda editoriale della categoria.
    name: "Monza",
    prestigeTier: 2,
    players: [
      { name: "Semuel Pizzignacco", nation: "Italia", birthDate: "2001-09-01", role: "POR", overall: 64 },
      { name: "Demba Thiam", nation: "Senegal", birthDate: "1998-03-09", role: "POR", overall: 62 },
      { name: "Andrea Vailati", nation: "Italia", birthDate: "2007-08-04", role: "POR", overall: 60 },
      { name: "Samuele Birindelli", nation: "Italia", birthDate: "1999-07-19", role: "TD", secondaryRoles: ["QD"], overall: 67 },
      { name: "Adam Bakoune", nation: "Italia", birthDate: "2006-02-06", role: "TD", secondaryRoles: ["QD"], overall: 60 },
      { name: "Andrea Carboni", nation: "Italia", birthDate: "2001-02-04", role: "DC", overall: 68 },
      { name: "Luca Ravanelli", nation: "Italia", birthDate: "1997-01-16", role: "DC", overall: 67 },
      { name: "Arvid Brorsson", nation: "Svezia", birthDate: "1999-05-08", role: "DC", overall: 65 },
      { name: "Valentin Antov", nation: "Bulgaria", birthDate: "2000-11-09", role: "DC", overall: 65 },
      { name: "Lorenzo Lucchesi", nation: "Italia", birthDate: "2003-05-09", role: "DC", overall: 63 },
      { name: "Paulo Azzi", nation: "Brasile", birthDate: "1994-07-15", role: "TS", secondaryRoles: ["QS"], overall: 66 },
      { name: "Samuele Capolupo", nation: "Italia", birthDate: "2006-04-08", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Pedro Obiang", nation: "Guinea Equatoriale", birthDate: "1992-03-27", role: "MED", overall: 69 },
      { name: "Hernani", nation: "Brasile", birthDate: "1994-03-27", role: "MED", overall: 66 },
      { name: "Matteo Pessina", nation: "Italia", birthDate: "1997-04-21", role: "CC", secondaryRoles: ["TRQ"], overall: 74 },
      { name: "Omari Forson", nation: "Inghilterra", birthDate: "2004-07-20", role: "ED", overall: 63 },
      { name: "Nicolas Galazzi", nation: "Italia", birthDate: "2000-12-18", role: "ES", overall: 64 },
      { name: "Andrea Colpani", nation: "Italia", birthDate: "1999-05-11", role: "TRQ", overall: 73 },
      { name: "Keita Baldé", nation: "Senegal", birthDate: "1995-03-08", role: "TQS", overall: 70 },
      { name: "Giuseppe Caso", nation: "Italia", birthDate: "1998-12-09", role: "TQS", overall: 66 },
      { name: "Patrick Ciurria", nation: "Italia", birthDate: "1995-02-09", role: "TQD", secondaryRoles: ["ED"], overall: 67 },
      { name: "Dany Mota", nation: "Portogallo", birthDate: "1998-05-02", role: "ATT", secondaryRoles: ["TQD"], overall: 71 },
      { name: "Patrick Cutrone", nation: "Italia", birthDate: "1998-01-03", role: "ATT", overall: 71 },
      { name: "Andrea Petagna", nation: "Italia", birthDate: "1995-06-30", role: "ATT", overall: 70 },
      { name: "Mirko Marić", nation: "Croazia", birthDate: "1995-05-16", role: "ATT", overall: 67 },
      { name: "Agustín Álvarez", nation: "Uruguay", birthDate: "2001-05-19", role: "ATT", overall: 65 },
    ],
  },
  {
    // Neopromossa che punta sull'esperienza: Gómez e Caprari sono qualità da categoria
    // superiore su gambe non più giovanissime.
    name: "Padova",
    prestigeTier: 1,
    players: [
      { name: "Mattia Fortin", nation: "Italia", birthDate: "2003-07-08", role: "POR", overall: 62 },
      { name: "Alessandro Sorrentino", nation: "Italia", birthDate: "2002-04-03", role: "POR", overall: 60 },
      { name: "Michele Voltan", nation: "Italia", birthDate: "2001-09-20", role: "POR", overall: 60 },
      { name: "Francesco Belli", nation: "Italia", birthDate: "1994-03-16", role: "TD", secondaryRoles: ["QD"], overall: 63 },
      { name: "Giulio Favale", nation: "Italia", birthDate: "1998-01-25", role: "TD", secondaryRoles: ["QD"], overall: 61 },
      { name: "Marco Perrotta", nation: "Italia", birthDate: "1994-02-14", role: "DC", overall: 63 },
      { name: "Filippo Sgarbi", nation: "Italia", birthDate: "1997-12-29", role: "DC", overall: 63 },
      { name: "Christian Pastina", nation: "Italia", birthDate: "2001-02-15", role: "DC", overall: 62 },
      { name: "Carlo Faedo", nation: "Italia", birthDate: "1999-05-18", role: "DC", overall: 61 },
      { name: "Antonio Barreca", nation: "Italia", birthDate: "1995-03-18", role: "TS", secondaryRoles: ["QS"], overall: 63 },
      { name: "Alessandro Boi", nation: "Italia", birthDate: "2005-03-01", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Lorenzo Crisetig", nation: "Italia", birthDate: "1993-01-20", role: "MED", overall: 64 },
      { name: "Pietro Fusi", nation: "Italia", birthDate: "1998-01-21", role: "MED", overall: 62 },
      { name: "Alessandro Capelli", nation: "Italia", birthDate: "1997-04-20", role: "CC", overall: 62 },
      { name: "Kevin Varas", nation: "Ecuador", birthDate: "1993-05-26", role: "CC", overall: 62 },
      { name: "Paolo Ghiglione", nation: "Italia", birthDate: "1997-02-02", role: "ED", secondaryRoles: ["TD"], overall: 64 },
      { name: "Luca Di Maggio", nation: "Italia", birthDate: "2005-03-31", role: "ES", overall: 60 },
      { name: "Alejandro Gómez", nation: "Argentina", birthDate: "1988-02-15", role: "TRQ", overall: 68 },
      { name: "Cristian Buonaiuto", nation: "Italia", birthDate: "1992-12-29", role: "TRQ", overall: 63 },
      { name: "Gianluca Caprari", nation: "Italia", birthDate: "1993-07-30", role: "TQS", overall: 68 },
      { name: "Francesco Di Mariano", nation: "Italia", birthDate: "1996-04-20", role: "TQS", overall: 65 },
      { name: "Kevin Lasagna", nation: "Italia", birthDate: "1992-08-10", role: "ATT", overall: 66 },
      { name: "Mattia Bortolussi", nation: "Italia", birthDate: "1996-05-02", role: "ATT", overall: 64 },
      { name: "Alessandro Seghetti", nation: "Italia", birthDate: "2004-01-11", role: "ATT", overall: 60 },
    ],
  },
  {
    // Rosa costruita per salire, con una spina dorsale intera di ex Serie A: Pohjanpalo è
    // il centravanti più forte della categoria.
    name: "Palermo",
    prestigeTier: 2,
    players: [
      { name: "Alfred Gomis", nation: "Senegal", birthDate: "1993-09-05", role: "POR", overall: 67 },
      { name: "Jesse Joronen", nation: "Finlandia", birthDate: "1993-03-21", role: "POR", overall: 64 },
      { name: "Francesco Di Bartolo", nation: "Italia", birthDate: "2005-03-18", role: "POR", overall: 60 },
      { name: "Bartosz Bereszyński", nation: "Polonia", birthDate: "1992-07-12", role: "TD", secondaryRoles: ["QD"], overall: 69 },
      { name: "Niccolò Pierozzi", nation: "Italia", birthDate: "2001-09-12", role: "TD", secondaryRoles: ["QD"], overall: 64 },
      { name: "Rui Modesto", nation: "Angola", birthDate: "1999-10-07", role: "TD", secondaryRoles: ["QD"], overall: 62 },
      { name: "Mattia Bani", nation: "Italia", birthDate: "1993-12-10", role: "DC", overall: 70 },
      { name: "Giangiacomo Magnani", nation: "Italia", birthDate: "1995-10-04", role: "DC", overall: 68 },
      { name: "Patryk Peda", nation: "Polonia", birthDate: "2002-04-16", role: "DC", overall: 64 },
      { name: "Davide Veroli", nation: "Italia", birthDate: "2003-01-29", role: "DC", overall: 62 },
      { name: "Pietro Ceccaroni", nation: "Italia", birthDate: "1995-12-21", role: "TS", secondaryRoles: ["QS"], overall: 67 },
      { name: "Tommaso Augello", nation: "Italia", birthDate: "1994-08-30", role: "TS", secondaryRoles: ["QS"], overall: 66 },
      { name: "Alexis Blin", nation: "Francia", birthDate: "1996-09-16", role: "MED", overall: 68 },
      { name: "Claudio Gomes", nation: "Francia", birthDate: "2000-07-23", role: "MED", overall: 65 },
      { name: "Jacopo Segre", nation: "Italia", birthDate: "1997-02-17", role: "CC", overall: 69 },
      { name: "Filippo Ranocchia", nation: "Italia", birthDate: "2001-05-14", role: "CC", overall: 67 },
      { name: "Samuel Giovane", nation: "Italia", birthDate: "2003-03-28", role: "CC", overall: 61 },
      { name: "Antonio Palumbo", nation: "Italia", birthDate: "1996-08-06", role: "TRQ", overall: 68 },
      { name: "Aljoša Vasić", nation: "Italia", birthDate: "2002-04-21", role: "TRQ", overall: 63 },
      { name: "Emmanuel Gyasi", nation: "Ghana", birthDate: "1994-01-11", role: "TQS", secondaryRoles: ["ES"], overall: 66 },
      { name: "Dennis Johnsen", nation: "Norvegia", birthDate: "1998-02-17", role: "TQD", overall: 64 },
      { name: "Joel Pohjanpalo", nation: "Finlandia", birthDate: "1994-09-13", role: "ATT", overall: 73 },
      { name: "Jérémy Le Douaron", nation: "Francia", birthDate: "1998-04-21", role: "ATT", overall: 66 },
      { name: "Giacomo Corona", nation: "Italia", birthDate: "2004-02-24", role: "ATT", overall: 61 },
    ],
  },
  {
    // Promossa dai playoff di Serie C: la rosa più leggera del campionato, tenuta su
    // dall'esperienza di Insigne e Faraoni.
    name: "Pescara",
    prestigeTier: 1,
    players: [
      { name: "Sebastiano Desplanches", nation: "Italia", birthDate: "2003-03-11", role: "POR", overall: 64 },
      { name: "Ivan Saio", nation: "Italia", birthDate: "2002-03-16", role: "POR", overall: 60 },
      { name: "Magnus Brøndbo", nation: "Norvegia", birthDate: "2005-03-02", role: "POR", overall: 60 },
      { name: "Davide Faraoni", nation: "Italia", birthDate: "1991-10-25", role: "TD", secondaryRoles: ["QD"], overall: 66 },
      { name: "Gaetano Letizia", nation: "Italia", birthDate: "1990-06-29", role: "TD", secondaryRoles: ["QD"], overall: 62 },
      { name: "Andrew Gravillon", nation: "Francia", birthDate: "1998-02-08", role: "DC", overall: 64 },
      { name: "Davide Bettella", nation: "Italia", birthDate: "2000-04-07", role: "DC", overall: 64 },
      { name: "Giorgio Altare", nation: "Italia", birthDate: "1998-08-09", role: "DC", overall: 63 },
      { name: "Riccardo Capellini", nation: "Italia", birthDate: "2000-03-01", role: "DC", overall: 62 },
      { name: "Gabriele Corbo", nation: "Italia", birthDate: "2000-01-11", role: "DC", overall: 62 },
      { name: "Filippo Pellacani", nation: "Italia", birthDate: "1998-02-26", role: "TS", secondaryRoles: ["QS"], overall: 61 },
      { name: "Jacopo La Barba", nation: "Italia", birthDate: "2006-12-13", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Gastón Brugman", nation: "Uruguay", birthDate: "1992-09-07", role: "MED", overall: 65 },
      { name: "Gennaro Acampora", nation: "Italia", birthDate: "1994-03-29", role: "MED", overall: 62 },
      { name: "Fabrizio Caligara", nation: "Italia", birthDate: "2000-04-12", role: "CC", overall: 64 },
      { name: "Luca Valzania", nation: "Italia", birthDate: "1996-03-05", role: "CC", overall: 63 },
      { name: "Lorenzo Meazzi", nation: "Italia", birthDate: "2001-05-28", role: "CC", overall: 61 },
      { name: "Leonardo Graziani", nation: "Italia", birthDate: "2005-05-21", role: "ED", overall: 60 },
      { name: "Julian Brandes", nation: "Paesi Bassi", birthDate: "2004-05-11", role: "ES", overall: 60 },
      { name: "Giacomo Olzer", nation: "Italia", birthDate: "2001-04-14", role: "TRQ", overall: 63 },
      { name: "Lorenzo Insigne", nation: "Italia", birthDate: "1991-06-04", role: "TQS", overall: 70 },
      { name: "Davide Merola", nation: "Italia", birthDate: "2000-03-27", role: "TQD", overall: 63 },
      { name: "Frank Tsadjout", nation: "Italia", birthDate: "1999-07-28", role: "ATT", overall: 63 },
      { name: "Orji Okwonkwo", nation: "Nigeria", birthDate: "1998-01-19", role: "ATT", overall: 62 },
      { name: "Flavio Russo", nation: "Italia", birthDate: "2004-08-31", role: "ATT", overall: 60 },
    ],
  },
  {
    // Metà classifica senza ambizioni dichiarate: Portanova è il solo profilo che in A
    // avrebbe giocato.
    name: "Reggiana",
    prestigeTier: 1,
    players: [
      { name: "Alessandro Micai", nation: "Italia", birthDate: "1993-07-24", role: "POR", overall: 64 },
      { name: "Andrea Seculin", nation: "Italia", birthDate: "1990-07-14", role: "POR", overall: 61 },
      { name: "Matteo Cardinali", nation: "Italia", birthDate: "2001-06-28", role: "POR", overall: 60 },
      { name: "Mario Sampirisi", nation: "Italia", birthDate: "1992-10-31", role: "TD", secondaryRoles: ["QD"], overall: 63 },
      { name: "Danilo Quaranta", nation: "Italia", birthDate: "1997-03-23", role: "TD", secondaryRoles: ["QD"], overall: 61 },
      { name: "Paolo Rozzio", nation: "Italia", birthDate: "1992-07-22", role: "DC", overall: 64 },
      { name: "Francesco Vicari", nation: "Italia", birthDate: "1994-08-03", role: "DC", overall: 64 },
      { name: "Andrea Papetti", nation: "Italia", birthDate: "2002-07-03", role: "DC", overall: 63 },
      { name: "Lorenzo Libutti", nation: "Italia", birthDate: "1997-09-17", role: "DC", overall: 62 },
      { name: "Yeferson Paz", nation: "Colombia", birthDate: "2002-06-13", role: "DC", overall: 61 },
      { name: "Alessandro Tripaldelli", nation: "Italia", birthDate: "1999-02-09", role: "TS", secondaryRoles: ["QS"], overall: 63 },
      { name: "Andrea Bozzolan", nation: "Italia", birthDate: "2004-02-23", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Massimo Bertagnoli", nation: "Italia", birthDate: "1999-02-26", role: "MED", overall: 63 },
      { name: "Luca Belardinelli", nation: "Italia", birthDate: "2001-03-14", role: "MED", overall: 62 },
      { name: "Manolo Portanova", nation: "Italia", birthDate: "2000-06-02", role: "CC", secondaryRoles: ["TRQ"], overall: 66 },
      { name: "Charlys", nation: "Brasile", birthDate: "2004-02-18", role: "CC", overall: 61 },
      { name: "Tobias Reinhart", nation: "Argentina", birthDate: "2000-05-21", role: "CC", overall: 60 },
      { name: "Kleis Bozhanaj", nation: "Albania", birthDate: "2001-03-01", role: "ES", overall: 62 },
      { name: "Natan Girma", nation: "Svizzera", birthDate: "2001-12-11", role: "TQS", overall: 61 },
      { name: "Matteo Rover", nation: "Italia", birthDate: "1999-02-20", role: "TQD", overall: 62 },
      { name: "Andrija Novakovich", nation: "Stati Uniti", birthDate: "1996-09-21", role: "ATT", overall: 65 },
      { name: "Cedric Gondo", nation: "Costa d'Avorio", birthDate: "1996-11-25", role: "ATT", overall: 63 },
      { name: "Tommaso Fumagalli", nation: "Italia", birthDate: "2000-02-20", role: "ATT", overall: 61 },
      { name: "Mathis Lambourde", nation: "Francia", birthDate: "2006-01-09", role: "ATT", overall: 60 },
    ],
  },
];
