import type { SerieBClub } from "./types";

/** Empoli, Frosinone, Juve Stabia, Mantova, Modena. */
export const CLUBS_02: SerieBClub[] = [
  {
    // Appena retrocessa dalla Serie A: è la rosa più attrezzata del campionato insieme a
    // Monza e Palermo, e i suoi Overall stanno in cima alla banda della categoria.
    name: "Empoli",
    prestigeTier: 2,
    players: [
      { name: "Andrea Fulignati", nation: "Italia", birthDate: "1994-10-31", role: "POR", overall: 69 },
      { name: "Samuele Perisan", nation: "Italia", birthDate: "1997-08-21", role: "POR", overall: 63 },
      { name: "Manuel Gasparini", nation: "Italia", birthDate: "2002-05-19", role: "POR", overall: 60 },
      { name: "Antonio Candela", nation: "Italia", birthDate: "2000-04-27", role: "TD", secondaryRoles: ["QD"], overall: 67 },
      { name: "Tyronne Ebuehi", nation: "Nigeria", birthDate: "1995-12-16", role: "TD", secondaryRoles: ["QD"], overall: 66 },
      { name: "Joseph Ceesay", nation: "Svezia", birthDate: "1998-06-03", role: "TD", secondaryRoles: ["QD"], overall: 63 },
      { name: "Matteo Lovato", nation: "Italia", birthDate: "2000-02-14", role: "DC", overall: 70 },
      { name: "Simone Romagnoli", nation: "Italia", birthDate: "1990-02-09", role: "DC", overall: 66 },
      { name: "Marco Curto", nation: "Italia", birthDate: "1999-01-05", role: "DC", overall: 65 },
      { name: "Nosa Edward Obaretin", nation: "Italia", birthDate: "2003-01-26", role: "DC", overall: 63 },
      { name: "Brando Moruzzi", nation: "Italia", birthDate: "2004-07-20", role: "TS", secondaryRoles: ["QS"], overall: 62 },
      { name: "Gabriele Guarino", nation: "Italia", birthDate: "2004-04-14", role: "TS", secondaryRoles: ["QS"], overall: 61 },
      { name: "Andrea Ghion", nation: "Italia", birthDate: "2000-02-23", role: "MED", overall: 65 },
      { name: "Luca Magnino", nation: "Italia", birthDate: "1997-08-13", role: "MED", overall: 64 },
      { name: "Nicolas Haas", nation: "Svizzera", birthDate: "1996-01-23", role: "CC", overall: 68 },
      { name: "Duccio Degli Innocenti", nation: "Italia", birthDate: "2003-04-28", role: "CC", overall: 67 },
      { name: "Gerard Yepes", nation: "Spagna", birthDate: "2002-08-25", role: "CC", overall: 63 },
      { name: "Lorenzo Ignacchiti", nation: "Italia", birthDate: "2004-04-25", role: "CC", overall: 62 },
      { name: "Edoardo Saporiti", nation: "Italia", birthDate: "2001-09-17", role: "TRQ", overall: 64 },
      { name: "Rareş Ilie", nation: "Romania", birthDate: "2003-04-19", role: "TQS", overall: 65 },
      { name: "Salvatore Elia", nation: "Italia", birthDate: "1999-06-30", role: "TQD", secondaryRoles: ["ED"], overall: 67 },
      { name: "Pietro Pellegri", nation: "Italia", birthDate: "2001-03-17", role: "ATT", overall: 71 },
      { name: "Marco Nasti", nation: "Italia", birthDate: "2003-09-17", role: "ATT", overall: 67 },
      { name: "Stiven Shpendi", nation: "Albania", birthDate: "2003-05-19", role: "ATT", overall: 67 },
      { name: "Flavio Bianchi", nation: "Italia", birthDate: "2000-01-24", role: "ATT", overall: 64 },
      { name: "Daniel Fila", nation: "Rep. Ceca", birthDate: "2002-08-21", role: "ATT", overall: 63 },
    ],
  },
  {
    // Rosa giovanissima costruita sul vivaio, con qualche innesto di mestiere: la classica
    // squadra che può stare a metà o rischiare, a seconda di quanto reggono i ragazzi.
    name: "Frosinone",
    prestigeTier: 2,
    players: [
      { name: "Matteo Pisseri", nation: "Italia", birthDate: "1991-11-21", role: "POR", overall: 65 },
      { name: "Lorenzo Palmisani", nation: "Italia", birthDate: "2004-06-01", role: "POR", overall: 60 },
      { name: "Eldin Lolić", nation: "Bosnia ed Erzegovina", birthDate: "2004-05-15", role: "POR", overall: 60 },
      { name: "Anthony Oyono", nation: "Gabon", birthDate: "2001-04-12", role: "TD", secondaryRoles: ["QD"], overall: 64 },
      { name: "Jérémy Oyono", nation: "Gabon", birthDate: "2001-04-12", role: "TD", secondaryRoles: ["QD"], overall: 62 },
      { name: "Riccardo Marchizza", nation: "Italia", birthDate: "1998-03-26", role: "DC", secondaryRoles: ["TS"], overall: 67 },
      { name: "Giorgio Cittadini", nation: "Italia", birthDate: "2002-04-18", role: "DC", overall: 66 },
      { name: "Jacopo Gelli", nation: "Italia", birthDate: "2001-05-11", role: "DC", overall: 62 },
      { name: "Gabriele Calvani", nation: "Italia", birthDate: "2004-01-12", role: "DC", overall: 61 },
      { name: "Niccolò Corrado", nation: "Italia", birthDate: "2000-03-19", role: "TS", secondaryRoles: ["QS"], overall: 64 },
      { name: "Edoardo Masciangelo", nation: "Italia", birthDate: "1996-07-08", role: "TS", secondaryRoles: ["QS"], overall: 63 },
      { name: "Giorgi Kvernadze", nation: "Georgia", birthDate: "2003-02-07", role: "QS", secondaryRoles: ["TS"], overall: 63 },
      { name: "Ilias Koutsoupias", nation: "Grecia", birthDate: "2001-05-10", role: "MED", overall: 63 },
      { name: "Ben Lhassine Kone", nation: "Costa d'Avorio", birthDate: "2000-03-14", role: "MED", overall: 63 },
      { name: "Francesco Gelli", nation: "Italia", birthDate: "1996-10-15", role: "CC", overall: 64 },
      { name: "Matteo Cichella", nation: "Italia", birthDate: "2005-10-04", role: "CC", overall: 60 },
      { name: "Filippo Grosso", nation: "Italia", birthDate: "2006-09-07", role: "CC", overall: 60 },
      { name: "Kevin Barcella", nation: "Italia", birthDate: "2006-06-17", role: "ES", overall: 60 },
      { name: "Giacomo Calò", nation: "Italia", birthDate: "1997-02-05", role: "TRQ", overall: 66 },
      { name: "Farès Ghedjemis", nation: "Algeria", birthDate: "2002-09-06", role: "TQS", overall: 65 },
      { name: "Antonio Fiori", nation: "Italia", birthDate: "2003-02-21", role: "TQD", overall: 60 },
      { name: "Lorenzo Gori", nation: "Italia", birthDate: "2004-04-08", role: "TQD", overall: 60 },
      { name: "Antonio Raimondo", nation: "Italia", birthDate: "2004-03-18", role: "ATT", overall: 66 },
      { name: "Edoardo Vergani", nation: "Italia", birthDate: "2001-02-06", role: "ATT", overall: 63 },
      { name: "Massimo Zilli", nation: "Italia", birthDate: "2002-07-17", role: "ATT", overall: 62 },
    ],
  },
  {
    // Piccola di provincia con una rosa onesta e nessun fuoriclasse: il metro con cui
    // misurare quanto la Serie B stia sotto la A.
    name: "Juve Stabia",
    prestigeTier: 1,
    players: [
      { name: "Alessandro Confente", nation: "Italia", birthDate: "1998-06-07", role: "POR", overall: 64 },
      { name: "Pietro Boer", nation: "Italia", birthDate: "2002-05-12", role: "POR", overall: 60 },
      { name: "Alessandro Signorini", nation: "Italia", birthDate: "1999-08-16", role: "POR", overall: 60 },
      { name: "Lorenzo Carissoni", nation: "Italia", birthDate: "1997-02-07", role: "TD", secondaryRoles: ["QD"], overall: 63 },
      { name: "Manuel Ricciardi", nation: "Italia", birthDate: "2000-04-17", role: "TD", secondaryRoles: ["QD"], overall: 60 },
      { name: "Marco Varnier", nation: "Italia", birthDate: "1998-06-08", role: "DC", overall: 64 },
      { name: "Marco Bellich", nation: "Italia", birthDate: "1999-05-05", role: "DC", overall: 62 },
      { name: "Salim Diakité", nation: "Francia", birthDate: "2000-07-03", role: "DC", overall: 62 },
      { name: "Christian Dalle Mura", nation: "Italia", birthDate: "2002-02-02", role: "DC", overall: 61 },
      { name: "Andrea Giorgini", nation: "Italia", birthDate: "2002-04-22", role: "DC", overall: 61 },
      { name: "Sheriff Kassama", nation: "Italia", birthDate: "2004-09-16", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Emanuele Torrasi", nation: "Italia", birthDate: "1999-03-16", role: "MED", overall: 64 },
      { name: "Giuseppe Leone", nation: "Italia", birthDate: "2001-05-05", role: "MED", overall: 60 },
      { name: "Nicola Mosti", nation: "Italia", birthDate: "1998-02-07", role: "CC", overall: 64 },
      { name: "Kevin Zeroli", nation: "Italia", birthDate: "2005-01-11", role: "CC", overall: 62 },
      { name: "Thomas Battistella", nation: "Italia", birthDate: "2001-07-29", role: "CC", overall: 61 },
      { name: "Aaron Ciammaglichella", nation: "Italia", birthDate: "2005-01-26", role: "CC", overall: 60 },
      { name: "Omar Correia", nation: "Francia", birthDate: "2000-04-10", role: "ED", overall: 60 },
      { name: "Christian Pierobon", nation: "Italia", birthDate: "2002-03-26", role: "ES", overall: 60 },
      { name: "Fabio Maistro", nation: "Italia", birthDate: "1998-04-05", role: "TRQ", overall: 65 },
      { name: "Gregorio Morachioli", nation: "Italia", birthDate: "2000-02-27", role: "TQD", overall: 62 },
      { name: "Rareș Burnete", nation: "Romania", birthDate: "2004-01-31", role: "TQS", overall: 61 },
      { name: "Alessandro Gabrielloni", nation: "Italia", birthDate: "1994-07-10", role: "ATT", overall: 63 },
      { name: "Leonardo Candellone", nation: "Italia", birthDate: "1997-09-15", role: "ATT", overall: 63 },
      { name: "Alvin Obinna Okoro", nation: "Nigeria", birthDate: "2005-03-26", role: "ATT", overall: 60 },
    ],
  },
  {
    // In lotta per non retrocedere: Falletti è il solo giocatore capace di decidere una
    // partita da solo.
    name: "Mantova",
    prestigeTier: 1,
    players: [
      { name: "Francesco Bardi", nation: "Italia", birthDate: "1992-01-18", role: "POR", overall: 64 },
      { name: "Lorenzo Andrenacci", nation: "Italia", birthDate: "1995-01-02", role: "POR", overall: 61 },
      { name: "Marco Festa", nation: "Italia", birthDate: "1992-06-06", role: "POR", overall: 60 },
      { name: "Tiago Gonçalves", nation: "Portogallo", birthDate: "2000-08-18", role: "TD", secondaryRoles: ["QD"], overall: 60 },
      { name: "Junior Ligue", nation: "Svizzera", birthDate: "2005-03-21", role: "TD", secondaryRoles: ["QD"], overall: 60 },
      { name: "Andrea Meroni", nation: "Italia", birthDate: "1997-01-09", role: "DC", overall: 63 },
      { name: "Stefano Cella", nation: "Italia", birthDate: "2000-07-22", role: "DC", overall: 62 },
      { name: "Alessio Castellini", nation: "Italia", birthDate: "2003-04-01", role: "DC", overall: 61 },
      { name: "Konstantinos Chrysopoulos", nation: "Grecia", birthDate: "2003-05-21", role: "DC", overall: 60 },
      { name: "Nicolò Radaelli", nation: "Italia", birthDate: "2003-01-24", role: "TS", secondaryRoles: ["QS"], overall: 61 },
      { name: "Côme Bianay Balcot", nation: "Francia", birthDate: "2005-05-13", role: "TS", secondaryRoles: ["QS"], overall: 60 },
      { name: "Simone Trimboli", nation: "Italia", birthDate: "2002-04-19", role: "MED", overall: 61 },
      { name: "Federico Zuccon", nation: "Italia", birthDate: "2003-04-01", role: "MED", overall: 60 },
      { name: "David Wieser", nation: "Italia", birthDate: "2002-02-13", role: "CC", overall: 61 },
      { name: "Flavio Paoletti", nation: "Italia", birthDate: "2003-01-16", role: "CC", overall: 60 },
      { name: "Francesco Ruocco", nation: "Italia", birthDate: "2001-03-23", role: "ES", overall: 62 },
      { name: "César Falletti", nation: "Uruguay", birthDate: "1992-12-02", role: "TRQ", overall: 66 },
      { name: "Rachid Kouda", nation: "Italia", birthDate: "2002-07-25", role: "TQS", overall: 62 },
      { name: "Nicolò Buso", nation: "Italia", birthDate: "2000-02-01", role: "TQD", overall: 62 },
      { name: "Davide Bragantini", nation: "Italia", birthDate: "2003-08-17", role: "TQD", overall: 60 },
      { name: "Leonardo Mancuso", nation: "Italia", birthDate: "1992-05-26", role: "ATT", overall: 64 },
      { name: "Davis Mensah", nation: "Ghana", birthDate: "1991-08-02", role: "ATT", overall: 63 },
      { name: "Nicholas Bonfanti", nation: "Italia", birthDate: "2002-03-28", role: "ATT", overall: 63 },
      { name: "Nikolas Muci", nation: "Svizzera", birthDate: "2003-02-08", role: "ATT", overall: 60 },
    ],
  },
  {
    // Molte punte e un centrocampo di categoria: candidata ai playoff, con Defrel a fare la
    // differenza sul piano tecnico.
    name: "Modena",
    prestigeTier: 1,
    players: [
      { name: "Leandro Chichizola", nation: "Argentina", birthDate: "1990-03-27", role: "POR", overall: 67 },
      { name: "Abdullah Laidani", nation: "Svizzera", birthDate: "2003-04-26", role: "POR", overall: 60 },
      { name: "Fabrizio Bagheria", nation: "Italia", birthDate: "2001-04-05", role: "POR", overall: 60 },
      { name: "Francesco Zampano", nation: "Italia", birthDate: "1993-09-30", role: "TD", secondaryRoles: ["QD"], overall: 64 },
      { name: "Gady Beyuku", nation: "Francia", birthDate: "2005-11-23", role: "TD", secondaryRoles: ["QD"], overall: 60 },
      { name: "Davide Adorni", nation: "Italia", birthDate: "1992-08-09", role: "DC", overall: 66 },
      { name: "Cristian Cauz", nation: "Italia", birthDate: "1996-08-15", role: "DC", overall: 64 },
      { name: "Bryant Nieling", nation: "Paesi Bassi", birthDate: "2002-10-31", role: "DC", overall: 63 },
      { name: "Alessandro Dellavalle", nation: "Italia", birthDate: "2004-05-11", role: "DC", overall: 62 },
      { name: "Matteo Cotali", nation: "Italia", birthDate: "1997-04-22", role: "TS", secondaryRoles: ["QS"], overall: 63 },
      { name: "Daniel Tonoli", nation: "Italia", birthDate: "2002-08-22", role: "TS", secondaryRoles: ["QS"], overall: 61 },
      { name: "Fabio Gerli", nation: "Italia", birthDate: "1996-12-23", role: "MED", overall: 66 },
      { name: "Simone Santoro", nation: "Italia", birthDate: "1999-09-20", role: "MED", overall: 64 },
      { name: "Alessandro Sersanti", nation: "Italia", birthDate: "2002-02-16", role: "CC", overall: 63 },
      { name: "Niklas Pyyhtiä", nation: "Finlandia", birthDate: "2003-09-25", role: "CC", overall: 63 },
      { name: "Antonio Imputato", nation: "Italia", birthDate: "2004-09-02", role: "ED", overall: 60 },
      { name: "Yanis Massolin", nation: "Francia", birthDate: "2002-09-20", role: "ES", overall: 62 },
      { name: "Luca Zanimacchia", nation: "Italia", birthDate: "1998-07-19", role: "TQD", overall: 65 },
      { name: "Grégoire Defrel", nation: "Francia", birthDate: "1991-06-17", role: "ATT", secondaryRoles: ["TQS"], overall: 69 },
      { name: "Ettore Gliozzi", nation: "Italia", birthDate: "1995-09-23", role: "ATT", overall: 67 },
      { name: "Pedro Mendes", nation: "Portogallo", birthDate: "1999-08-01", role: "ATT", overall: 65 },
      { name: "Manuel De Luca", nation: "Italia", birthDate: "1998-07-17", role: "ATT", overall: 65 },
      { name: "Giuseppe Ambrosino", nation: "Italia", birthDate: "2003-09-10", role: "ATT", overall: 64 },
      { name: "Luca Strizzolo", nation: "Italia", birthDate: "1992-04-29", role: "ATT", overall: 63 },
    ],
  },
];
