/**
 * Dati editoriali per l'import degli altri quattro campionati Big 5 dal foglio
 * `Cartel1.xlsx` (CLAUDE.md sez. 2.3).
 *
 * Perché servono elenchi di club **espliciti** invece di filtrare per `Campionato`: il
 * foglio usa il nome della lega, e più paesi usano lo stesso nome. Filtrando per
 * "Premier League" entrerebbero Dynamo Kyiv e Shakhtar Donetsk (Ucraina), e sotto
 * "Bundesliga" ci sono 30 club perché include quella **austriaca** (Salzburg, Rapid,
 * Sturm Graz…). È la stessa trappola già vista con la "Serie A" ecuadoriana.
 *
 * I `prestige_tier` (1-5) sono **stime editoriali dichiarate**, come per la Serie A:
 * riflettono storia, palmarès e valore della rosa, e alimentano il valore di mercato
 * (sez. 2.3) e la base Overall (`computeContextPrior`).
 */

export interface LeagueSeed {
  name: string;
  nation: string;
  prestigeTier: number;
  /** Nome del campionato nel foglio, per il filtro iniziale. */
  sheetLeague: string;
  /** Club → tier di prestigio. L'elenco è anche il filtro: fuori da qui non entra nessuno. */
  clubs: Record<string, number>;
}

export const BIG5_LEAGUES: LeagueSeed[] = [
  {
    name: "Premier League",
    nation: "Inghilterra",
    prestigeTier: 5,
    sheetLeague: "Premier League",
    clubs: {
      Liverpool: 5,
      "Manchester City": 5,
      Arsenal: 5,
      Chelsea: 5,
      "Manchester United": 5,
      "Tottenham Hotspur": 4,
      "Newcastle United": 4,
      "Aston Villa": 4,
      "Brighton & Hove Albion": 3,
      "Nottingham Forest": 3,
      "West Ham United": 3,
      Everton: 3,
      "Crystal Palace": 3,
      "Fulham FC": 3,
      Brentford: 3,
      "AFC Bournemouth": 3,
      "Wolverhampton Wanderers": 2,
      "Leeds United": 2,
      Sunderland: 2,
      Burnley: 2,
    },
  },
  {
    name: "La Liga",
    nation: "Spagna",
    prestigeTier: 5,
    sheetLeague: "La Liga",
    clubs: {
      "Real Madrid": 5,
      "FC Barcelona": 5,
      "Atlético Madrid": 5,
      "Athletic Club": 4,
      "Real Sociedad": 4,
      "Sevilla FC": 4,
      "Villarreal CF": 4,
      "Real Betis Balompié": 4,
      "Valencia CF": 3,
      "RC Celta": 3,
      "Girona FC": 3,
      "CA Osasuna": 3,
      "Rayo Vallecano": 3,
      "RCD Mallorca": 3,
      "Getafe CF": 2,
      "Deportivo Alavés": 2,
      "RCD Espanyol": 2,
      "Elche CF": 2,
      "Levante UD": 2,
      "Real Oviedo": 2,
    },
  },
  {
    name: "Bundesliga",
    nation: "Germania",
    prestigeTier: 4,
    sheetLeague: "Bundesliga",
    clubs: {
      "FC Bayern München": 5,
      "Borussia Dortmund": 5,
      "Bayer 04 Leverkusen": 4,
      "RB Leipzig": 4,
      "VfB Stuttgart": 4,
      "Eintracht Frankfurt": 4,
      "SV Werder Bremen": 3,
      "Borussia Mönchengladbach": 3,
      "VfL Wolfsburg": 3,
      "SC Freiburg": 3,
      "TSG 1899 Hoffenheim": 3,
      "1. FSV Mainz 05": 3,
      "1. FC Union Berlin": 3,
      "FC Augsburg": 2,
      "Hamburger SV": 3,
      "1. FC Köln": 3,
      "FC St. Pauli": 2,
      "1. FC Heidenheim 1846": 2,
    },
  },
  {
    name: "Ligue 1",
    nation: "Francia",
    prestigeTier: 4,
    sheetLeague: "Ligue 1",
    clubs: {
      "Paris Saint-Germain": 5,
      "Olympique de Marseille": 4,
      "AS Monaco": 4,
      "Olympique Lyonnais": 4,
      "Lille OSC": 4,
      "OGC Nice": 3,
      "RC Lens": 3,
      "Stade Rennais FC": 3,
      "RC Strasbourg Alsace": 3,
      "Stade Brestois 29": 3,
      "Toulouse FC": 2,
      "FC Nantes": 2,
      "AJ Auxerre": 2,
      "Angers SCO": 2,
      "Le Havre AC": 2,
      "FC Lorient": 2,
      "FC Metz": 2,
      "Paris FC": 2,
    },
  },
];

/**
 * Nazionalità dall'inglese del foglio all'italiano già usato in `player_pool`.
 *
 * Non è cosmetica: la **chemistry** confronta le stringhe di nazionalità (sez. 3.4), quindi
 * un inglese registrato come "England" non risulterebbe mai connazionale di uno registrato
 * come "Inghilterra" — le linee verdi sparirebbero tra giocatori di campionati diversi,
 * che è esattamente il tipo di collegamento che il draft misto deve premiare.
 */
export const NATION_IT: Record<string, string> = {
  Spain: "Spagna",
  France: "Francia",
  Germany: "Germania",
  England: "Inghilterra",
  Brazil: "Brasile",
  Netherlands: "Paesi Bassi",
  Argentina: "Argentina",
  Portugal: "Portogallo",
  Belgium: "Belgio",
  Senegal: "Senegal",
  Denmark: "Danimarca",
  Morocco: "Marocco",
  Switzerland: "Svizzera",
  Austria: "Austria",
  "Côte d'Ivoire": "Costa d'Avorio",
  Sweden: "Svezia",
  "United States": "Stati Uniti",
  Nigeria: "Nigeria",
  Norway: "Norvegia",
  Ghana: "Ghana",
  Italy: "Italia",
  Croatia: "Croazia",
  Algeria: "Algeria",
  Japan: "Giappone",
  Cameroon: "Camerun",
  Mali: "Mali",
  Uruguay: "Uruguay",
  Serbia: "Serbia",
  Scotland: "Scozia",
  Poland: "Polonia",
  Türkiye: "Turchia",
  "Congo DR": "Rep. Democratica del Congo",
  Wales: "Galles",
  Colombia: "Colombia",
  Czechia: "Rep. Ceca",
  Ukraine: "Ucraina",
  "Republic of Ireland": "Irlanda",
  Greece: "Grecia",
  Hungary: "Ungheria",
  "Korea Republic": "Corea del Sud",
  Georgia: "Georgia",
  "Burkina Faso": "Burkina Faso",
  Canada: "Canada",
  Guinea: "Guinea",
  Slovakia: "Slovacchia",
  Slovenia: "Slovenia",
  Romania: "Romania",
  Russia: "Russia",
  Mexico: "Messico",
  Chile: "Cile",
  Paraguay: "Paraguay",
  Venezuela: "Venezuela",
  Ecuador: "Ecuador",
  Peru: "Perù",
  Albania: "Albania",
  "Bosnia and Herzegovina": "Bosnia ed Erzegovina",
  "North Macedonia": "Macedonia del Nord",
  Montenegro: "Montenegro",
  Kosovo: "Kosovo",
  Finland: "Finlandia",
  Iceland: "Islanda",
  Israel: "Israele",
  Egypt: "Egitto",
  Tunisia: "Tunisia",
  "Northern Ireland": "Irlanda del Nord",
  Australia: "Australia",
  "New Zealand": "Nuova Zelanda",
  Jamaica: "Giamaica",
  Angola: "Angola",
  "Congo": "Congo",
  Gabon: "Gabon",
  Zambia: "Zambia",
  "Cape Verde Islands": "Capo Verde",
  "Guinea Bissau": "Guinea-Bissau",
  Togo: "Togo",
  Benin: "Benin",
  "Burundi": "Burundi",
  Gambia: "Gambia",
  "Sierra Leone": "Sierra Leone",
  Kenya: "Kenya",
  "South Africa": "Sudafrica",
  "Equatorial Guinea": "Guinea Equatoriale",
  "Central African Republic": "Rep. Centrafricana",
  Mozambique: "Mozambico",
  Madagascar: "Madagascar",
  Comoros: "Comore",
  Bulgaria: "Bulgaria",
  Estonia: "Estonia",
  Latvia: "Lettonia",
  Lithuania: "Lituania",
  Belarus: "Bielorussia",
  Armenia: "Armenia",
  Azerbaijan: "Azerbaigian",
  Uzbekistan: "Uzbekistan",
  "Korea DPR": "Corea del Nord",
  China: "Cina",
  Iran: "Iran",
  Iraq: "Iraq",
  "Saudi Arabia": "Arabia Saudita",
  Syria: "Siria",
  Jordan: "Giordania",
  Panama: "Panama",
  "Costa Rica": "Costa Rica",
  Honduras: "Honduras",
  Curacao: "Curaçao",
  Suriname: "Suriname",
  Bolivia: "Bolivia",
  "Trinidad and Tobago": "Trinidad e Tobago",
  Haiti: "Haiti",
  "Cuba": "Cuba",
  "Dominican Republic": "Rep. Dominicana",
  Turkey: "Turchia",
};
