/**
 * Overall editoriali della Premier League 2025/26 — **stima nostra e dichiarata**, stessa
 * scala e stesso metodo usati per la Serie A (`editorial-overalls-serie-a.ts`, CLAUDE.md
 * sez. 2.2).
 *
 * Differenza rispetto alla Serie A: qui vengono valutati individualmente **solo i giocatori
 * riconoscibili**. Il foglio include moltissimi ragazzi delle giovanili che nel campionato
 * non giocano — valutarli uno per uno sarebbe finta precisione. Chi non compare in questa
 * mappa riceve un valore da **fondo rosa** calcolato dal tier del club (vedi
 * `DEPTH_CAP_BY_TIER` in `applyEditorialBig5.ts`): sotto la soglia dei titolari, quindi
 * pescabile ma mai una scelta forte.
 *
 * Scala (identica alla Serie A): 88-92 fuoriclasse assoluti · 84-87 top da Champions ·
 * 80-83 titolari di alto livello · 76-79 ossatura da Europa · 72-75 media classifica ·
 * 68-71 rosa · 62-67 fondo rosa.
 */
export const EDITORIAL_PREMIER: Record<string, number> = {
  // --- Arsenal ---
  "Arsenal|Bukayo Saka": 88,
  "Arsenal|William Saliba": 87,
  "Arsenal|Declan Rice": 86,
  "Arsenal|Martin Ødegaard": 86,
  "Arsenal|Gabriel Magalhães": 85,
  "Arsenal|David Raya Martín": 84,
  "Arsenal|Viktor Einar Gyökeres": 84,
  "Arsenal|Martín Zubimendi Ibáñez": 83,
  "Arsenal|Eberechi Oluchi Eze": 83,
  "Arsenal|Jurriën Timber": 82,
  "Arsenal|Benjamin William White": 82,
  "Arsenal|Kai Lukas Havertz": 81,
  "Arsenal|Gabriel Silva": 80,
  "Arsenal|Mikel Merino Zazón": 80,
  "Arsenal|Leandro Trossard": 79,
  "Arsenal|Chukwunonso Tristan Madueke": 79,
  "Arsenal|Riccardo Calafiori": 79,
  "Arsenal|Gabriel Jesus": 78,
  "Arsenal|Kepa Arrizabalaga Revuelta": 76,
  "Arsenal|Myles Anthony Lewis-Skelly": 76,
  "Arsenal|Ethan Chidiebere Nwaneri": 75,
  "Arsenal|Christian Thers Nørgaard": 74,

  // --- Aston Villa ---
  "Aston Villa|Oliver Watkins": 82,
  "Aston Villa|Morgan Elliot Rogers": 82,
  "Aston Villa|Youri Tielemans": 81,
  "Aston Villa|Ezri Konsa Ngoyo": 80,
  "Aston Villa|Pau Francisco Torres": 80,
  "Aston Villa|Amadou Onana": 80,
  "Aston Villa|Boubacar Bernard Kamara": 79,
  "Aston Villa|John McGinn": 78,
  "Aston Villa|Donyell Malen": 78,
  "Aston Villa|Harvey Scott Elliott": 77,
  "Aston Villa|Tyrone Deon Mings": 76,
  "Aston Villa|Matthew Stuart Cash": 76,
  "Aston Villa|Lucas Digne": 76,
  "Aston Villa|Ian Ethan Maatsen": 76,
  "Aston Villa|Emiliano Buendía Stati": 76,
  "Aston Villa|Jadon Malik Sancho": 76,
  "Aston Villa|Evann Guessand": 76,
  "Aston Villa|Victor Lindelöf": 76,
  "Aston Villa|Ross Barkley": 75,
  "Aston Villa|Marco Bizot": 74,

  // --- AFC Bournemouth ---
  "AFC Bournemouth|Antoine Serlom Semenyo": 80,
  "AFC Bournemouth|Bafodé Diakité": 78,
  "AFC Bournemouth|Tyler Shaan Adams": 78,
  "AFC Bournemouth|Justin Dean Kluivert": 78,
  "AFC Bournemouth|Adrien Truffert": 77,
  "AFC Bournemouth|Amine Adli": 76,
  "AFC Bournemouth|Lewis John Cook": 76,
  "AFC Bournemouth|Ryan Christie": 76,
  "AFC Bournemouth|Đorđe Petrović": 76,
  "AFC Bournemouth|Marcus Joseph Tavernier": 76,
  "AFC Bournemouth|Enes Ünal": 74,
  "AFC Bournemouth|Veljko Milosavljević": 74,
  "AFC Bournemouth|David Robert Brooks": 74,
  "AFC Bournemouth|Ben Gannon Doak": 74,
  "AFC Bournemouth|Alex Jay Scott": 74,
  "AFC Bournemouth|Adam James Smith": 72,
  "AFC Bournemouth|Eli Kroupi": 72,

  // --- Brentford ---
  "Brentford|Nathan Michael Collins": 79,
  "Brentford|Mikkel Krogh Damsgaard": 79,
  "Brentford|Caoimhín Odhrán Kelleher": 78,
  "Brentford|Kevin Schade": 77,
  "Brentford|Dango Ouattara": 77,
  "Brentford|Ethan Rupert Pinnock": 76,
  "Brentford|Kristoffer Ajer": 76,
  "Brentford|Aaron Buchanan Hickey": 76,
  "Brentford|Michael Olabode Kayode": 76,
  "Brentford|Keane William Lewis-Potter": 76,
  "Brentford|Jordan Brian Henderson": 76,
  "Brentford|Mathias Jensen": 76,
  "Brentford|Vitaly Janelt": 75,
  "Brentford|Fábio Carvalho": 75,
  "Brentford|Yehor Yarmoliuk": 74,
  "Brentford|Ogochukwu Frank Onyeka": 74,
  "Brentford|Reiss Luke Nelson": 74,
  "Brentford|Rico Antonio Henry": 74,
  "Brentford|Antoni-Djibu Milambo": 73,
  "Brentford|Hákon Rafn Valdimarsson": 72,

  // --- Brighton & Hove Albion ---
  "Brighton & Hove Albion|Kaoru Mitoma": 81,
  "Brighton & Hove Albion|Carlos Baleba": 80,
  "Brighton & Hove Albion|Lewis Carl Dunk": 78,
  "Brighton & Hove Albion|Jan Hecke": 78,
  "Brighton & Hove Albion|Bart Verbruggen": 78,
  "Brighton & Hove Albion|Ferdi Erenay Kadıoğlu": 78,
  "Brighton & Hove Albion|Yankuba Minteh": 78,
  "Brighton & Hove Albion|Georginio Rutter": 78,
  "Brighton & Hove Albion|Maxim De Cuyper": 77,
  "Brighton & Hove Albion|Mats Wieffer": 77,
  "Brighton & Hove Albion|Olivier Maxime Boscagli": 77,
  "Brighton & Hove Albion|Joël Ivo Veltman": 76,
  "Brighton & Hove Albion|Yasin Abbas Ayari": 76,
  "Brighton & Hove Albion|Brajan Gruda": 76,
  "Brighton & Hove Albion|Daniel Welbeck": 76,
  "Brighton & Hove Albion|Jack Luca Hinshelwood": 75,
  "Brighton & Hove Albion|Adam Harry Webster": 74,
  "Brighton & Hove Albion|Diego Coppola": 74,
  "Brighton & Hove Albion|Solomon Benjamin March": 74,
  "Brighton & Hove Albion|Stefanos Tzimas": 74,
  "Brighton & Hove Albion|Charalampos Kostoulas": 73,
  "Brighton & Hove Albion|James Philip Milner": 70,

  // --- Burnley ---
  "Burnley|Kyle Andrew Walker": 76,
  "Burnley|Maxime Estève": 75,
  "Burnley|Florentino Luís": 75,
  "Burnley|Martin Dúbravka": 74,
  "Burnley|Joshua Jon Cullen": 74,
  "Burnley|Lesley Chimuanya Ugochukwu": 74,
  "Burnley|Quilindschy Hartman": 73,
  "Burnley|Jaidon Anthony": 73,
  "Burnley|Jacob Bruun Larsen": 73,
  "Burnley|Mike Trésor Ndayishimiye": 73,
  "Burnley|Marcus Edwards": 73,
  "Burnley|Loum Tchaouna": 73,
  "Burnley|Armando Broja": 73,
  "Burnley|Mohamed Zeki Amdouni": 73,
  "Burnley|Zian Flemming": 73,
  "Burnley|Hjalmar Ekdal": 72,
  "Burnley|Joseph Adrian Worrall": 72,
  "Burnley|Louis Jordan Beyer": 72,
  "Burnley|Hannes Delcroix": 72,
  "Burnley|Connor Roberts": 72,
  "Burnley|Hannibal Mejbri": 72,
  "Burnley|Lyle Brent Foster": 72,
  "Burnley|Axel Tuanzebe": 71,
  "Burnley|Bashir Humphreys": 71,
  "Burnley|Václav Hladký": 70,
  "Burnley|Max Weiß": 70,
  "Burnley|Ashley Luke Barnes": 68,

  // --- Chelsea ---
  "Chelsea|Cole Jermaine Palmer": 87,
  "Chelsea|Enzo Jeremías Fernández": 84,
  "Chelsea|Marc Cucurella Saseta": 82,
  "Chelsea|Reece James": 82,
  "Chelsea|Levi Colwill": 81,
  "Chelsea|Abdul-Nasir Adarabioyo": 80,
  "Chelsea|Wesley Fofana": 80,
  "Chelsea|Estêvão Willian Almeida": 80,
  "Chelsea|Malo Gusto": 79,
  "Chelsea|Jorrel Hato": 79,
  "Chelsea|Pedro Lomba Neto": 79,
  "Chelsea|Alejandro Garnacho Ferreyra": 79,
  "Chelsea|Robert Lynch Sánchez": 78,
  "Chelsea|Trevoh Thomas Chalobah": 78,
  "Chelsea|Roméo Lavia": 78,
  "Chelsea|Liam Rory Delap": 78,
  "Chelsea|Benoît Badiashile Mukinayi": 76,
  "Chelsea|Andrey Santos": 76,
  "Chelsea|Filip Jørgensen": 76,
  "Chelsea|Jamie Jermaine Bynoe-Gittens": 76,
  "Chelsea|Axel Arthur Disasi": 75,
  "Chelsea|Marc Guiu Paz": 74,
  "Chelsea|Raheem Shaquille Sterling": 74,
  "Chelsea|Facundo Valentín Buonanotte": 74,
  "Chelsea|Joshua Kofi Acheampong": 73,
  "Chelsea|Dário Essugo": 73,

  // --- Crystal Palace ---
  "Crystal Palace|Addji Guéhi": 82,
  "Crystal Palace|Daniel Muñoz Mejía": 80,
  "Crystal Palace|Adam James Wharton": 80,
  "Crystal Palace|Jean-Philippe Mateta": 80,
  "Crystal Palace|Guy Maxence Lacroix": 79,
  "Crystal Palace|Dean Bradley Henderson": 79,
  "Crystal Palace|Ismaïla Sarr": 79,
  "Crystal Palace|Cheick Oumar Doucouré": 78,
  "Crystal Palace|Tyrick Kwon Mitchell": 78,
  "Crystal Palace|Christopher Jeffrey Richards": 77,
  "Crystal Palace|William James Hughes": 77,
  "Crystal Palace|Daichi Kamada": 77,
  "Crystal Palace|Chadi Riad Dnanou": 75,
  "Crystal Palace|Edward Keddar Nketiah": 74,
  "Crystal Palace|Walter Daniel Benítez": 74,
  "Crystal Palace|Romain Esse": 74,
  "Crystal Palace|Christantus Uche": 73,
  "Crystal Palace|Borna Sosa": 73,
  "Crystal Palace|Naouirou Mohamed Ahamada": 72,
  "Crystal Palace|Justin Devenny": 72,
  "Crystal Palace|Nathaniel Edwin Clyne": 70,

  // --- Everton ---
  "Everton|Jordan Lee Pickford": 84,
  "Everton|Jarrad Paul Branthwaite": 81,
  "Everton|Jack Peter Grealish": 80,
  "Everton|James Alan Tarkowski": 79,
  "Everton|Iliman Ndiaye": 79,
  "Everton|Dwight McNeil": 77,
  "Everton|Idrissa Gana Gueye": 77,
  "Everton|Vitalii Mykolenko": 76,
  "Everton|Kiernan Frank Dewsbury-Hall": 76,
  "Everton|Jake O'Brien": 75,
  "Everton|Carlos Jonás Alcaraz": 75,
  "Everton|Tyler-Jay Robert Dibling": 75,
  "Everton|Michael Vincent Keane": 74,
  "Everton|James David Garner": 74,
  "Everton|Thierno Barry": 74,
  "Everton|Merlin Röhl": 74,
  "Everton|Nathan Kenneth Patterson": 73,
  "Everton|Timothy Emeka Iroegbunam": 73,
  "Everton|Mark Travers": 72,
  "Everton|Séamus Coleman": 70,

  // --- Fulham FC ---
  "Fulham FC|Bernd Leno": 80,
  "Fulham FC|Joachim Christian Andersen": 79,
  "Fulham FC|Antonee Robinson": 79,
  "Fulham FC|Alexander Chuka Iwobi": 79,
  "Fulham FC|Calvin Bassey Ughelumba": 78,
  "Fulham FC|Sander Berge": 78,
  "Fulham FC|Saša Lukić": 77,
  "Fulham FC|Harry Wilson": 77,
  "Fulham FC|Samuel Chimerenka Chukwueze": 77,
  "Fulham FC|Kenny Joelle Tete": 76,
  "Fulham FC|Timothy Castagne": 76,
  "Fulham FC|Adama Traoré Diarra": 76,
  "Fulham FC|Rodrigo Muniz Carvalho": 76,
  "Fulham FC|Emile Smith Rowe": 76,
  "Fulham FC|Issa Diop": 75,
  "Fulham FC|Jorge Cuenca Barreno": 74,
  "Fulham FC|Harrison James Reed": 74,
  "Fulham FC|Thomas Cairney": 74,
  "Fulham FC|Kouassi Ryan Sessegnon": 74,
  "Fulham FC|Joshua King": 72,
  "Fulham FC|Benjamin Lecomte": 72,

  // --- Leeds United ---
  "Leeds United|Anton Levi Stach": 76,
  "Leeds United|Ao Tanaka": 76,
  "Leeds United|Ethan Ampadu": 76,
  "Leeds United|Jaka Bijol": 76,
  "Leeds United|Daniel Owen James": 76,
  "Leeds United|Lucas Estella Perri": 75,
  "Leeds United|Joseph Peter Rodon": 75,
  "Leeds United|Pascal Augustus Struijk": 75,
  "Leeds United|Degnand Wilfried Gnonto": 75,
  "Leeds United|Jack David Harrison": 75,
  "Leeds United|Dominic Nathaniel Calvert-Lewin": 75,
  "Leeds United|Noah Arinzechukwu Okafor": 75,
  "Leeds United|Illan Stéphane Meslier": 74,
  "Leeds United|Sebastiaan Bornauw": 74,
  "Leeds United|Gabriel Gudmundsson": 74,
  "Leeds United|Ilia Iliev Gruev": 74,
  "Leeds United|Sean David Longstaff": 74,
  "Leeds United|Brenden Russell Aaronson": 74,
  "Leeds United|Joël Piroe": 74,
  "Leeds United|Jayden Ian Bogle": 73,
  "Leeds United|James Michael Justin": 73,
  "Leeds United|Lukas Okechukwu Nmecha": 73,
  "Leeds United|Samuel Mark Byram": 70,

  // --- Liverpool ---
  "Liverpool|Virgil van Dijk": 88,
  "Liverpool|Alisson Ramsés Becker": 87,
  "Liverpool|Alexander Isak": 87,
  "Liverpool|Florian Richard Wirtz": 86,
  "Liverpool|Alexis Mac Allister": 85,
  "Liverpool|Dominik Szoboszlai": 84,
  "Liverpool|Ryan Jiro Gravenberch": 84,
  "Liverpool|Cody Mathès Gakpo": 83,
  "Liverpool|Ibrahima Konaté": 83,
  "Liverpool|Hugo Ekitiké": 82,
  "Liverpool|Andrew Henry Robertson": 81,
  "Liverpool|Giorgi Mamardashvili": 81,
  "Liverpool|Milos Kerkez": 80,
  "Liverpool|Jeremie Agyekum Frimpong": 80,
  "Liverpool|Curtis Jones": 79,
  "Liverpool|Conor Bradley": 78,
  "Liverpool|Federico Chiesa": 78,
  "Liverpool|Joseph Dave Gomez": 77,
  "Liverpool|Wataru Endo": 75,
  "Liverpool|Giovanni Leoni": 74,
  "Liverpool|Stefan Bajčetić Maquieira": 73,

  // --- Manchester City ---
  "Manchester City|Erling Braut Håland": 91,
  "Manchester City|Rodrigo Hernández Cascante": 89,
  "Manchester City|Gianluigi Donnarumma": 87,
  "Manchester City|Rúben Dias": 86,
  "Manchester City|Philip Walter Foden": 85,
  "Manchester City|Joško Gvardiol": 85,
  "Manchester City|Bernardo Silva": 84,
  "Manchester City|Jérémy Doku": 83,
  "Manchester City|Omar Marmoush": 82,
  "Manchester City|Mateo Kovačić": 81,
  "Manchester City|Mathis Rayan Cherki": 81,
  "Manchester City|Sávio Oliveira": 81,
  "Manchester City|John Stones": 80,
  "Manchester City|Rayan Aït Nouri": 80,
  "Manchester City|Nathan Benjamin Aké": 79,
  "Manchester City|Nicolás González Iglesias": 79,
  "Manchester City|Abdukodir Khusanov": 77,
  "Manchester City|Rico Lewis": 77,
  "Manchester City|Matheus Luiz Nunes": 77,
  "Manchester City|Oscar Bobb": 76,
  "Manchester City|James Harrington Trafford": 76,
  "Manchester City|Stefan Ortega Moreno": 76,
  "Manchester City|Kalvin Mark Phillips": 72,

  // --- Manchester United ---
  "Manchester United|Bruno Fernandes": 86,
  "Manchester United|Matthijs de Ligt": 83,
  "Manchester United|Matheus Cunha": 82,
  "Manchester United|Bryan Mbeumo": 82,
  "Manchester United|Lisandro Martínez": 82,
  "Manchester United|Benjamin Šeško": 81,
  "Manchester United|Leny Yoro": 79,
  "Manchester United|Carlos Henrique Casimiro": 79,
  "Manchester United|Amad Diallo Traoré": 79,
  "Manchester United|Noussair Mazraoui": 78,
  "Manchester United|Kobbie Mainoo": 78,
  "Manchester United|Jacob Harry Maguire": 77,
  "Manchester United|Luke Shaw": 77,
  "Manchester United|Manuel Ugarte Ribeiro": 77,
  "Manchester United|Mason Tony Mount": 77,
  "Manchester United|Joshua Orobosa Zirkzee": 76,
  "Manchester United|Patrick Chinazaekpere Dorgu": 75,
  "Manchester United|Altay Bayındır": 74,
  "Manchester United|Senne Lammens": 74,
  "Manchester United|Tyrell Malacia": 73,
  "Manchester United|Ayden Edford Heaven": 72,
  "Manchester United|Thomas David Heaton": 70,

  // --- Newcastle United ---
  "Newcastle United|Bruno Moura": 85,
  "Newcastle United|Sandro Tonali": 84,
  "Newcastle United|Anthony Michael Gordon": 83,
  "Newcastle United|Joelinton Lira": 81,
  "Newcastle United|Sven Adriaan Botman": 80,
  "Newcastle United|Fabian Lukas Schär": 79,
  "Newcastle United|Malick Laye Thiaw": 79,
  "Newcastle United|Valentino Francisco Livramento": 79,
  "Newcastle United|Nicholas David Pope": 79,
  "Newcastle United|Harvey Lewis Barnes": 79,
  "Newcastle United|Anthony Elanga": 79,
  "Newcastle United|Nick Woltemade": 79,
  "Newcastle United|Yoane Wissa": 79,
  "Newcastle United|Lewis Kieran Hall": 78,
  "Newcastle United|Daniel Johnson Burn": 77,
  "Newcastle United|Kieran John Trippier": 77,
  "Newcastle United|Aaron Christopher Ramsdale": 76,
  "Newcastle United|Jacob Matthew Ramsey": 76,
  "Newcastle United|Joseph George Willock": 75,
  "Newcastle United|Jacob Kai Murphy": 75,
  "Newcastle United|Lewis Miley": 74,
  "Newcastle United|Jamaal Lascelles": 73,
  "Newcastle United|William Osula": 73,
  "Newcastle United|Emil Krafth": 72,

  // --- Nottingham Forest ---
  "Nottingham Forest|Morgan Anthony Gibbs-White": 82,
  "Nottingham Forest|Murillo Santos": 81,
  "Nottingham Forest|Nikola Milenković": 80,
  "Nottingham Forest|Elliot Junior Anderson": 80,
  "Nottingham Forest|Dan Assane Ndoye": 79,
  "Nottingham Forest|Christopher Grant Wood": 79,
  "Nottingham Forest|Callum James Hudson-Odoi": 78,
  "Nottingham Forest|Arnaud Kalimuendo Muinga": 78,
  "Nottingham Forest|Matz Sels": 78,
  "Nottingham Forest|James John McAtee": 77,
  "Nottingham Forest|Temitayo Aina": 76,
  "Nottingham Forest|Oleksandr Zinchenko": 76,
  "Nottingham Forest|Ibrahim Sangaré": 76,
  "Nottingham Forest|Nicolás Martín Domínguez": 76,
  "Nottingham Forest|Dilane Bakwa": 76,
  "Nottingham Forest|Nicolò Savona": 75,
  "Nottingham Forest|Neco Shay Williams": 75,
  "Nottingham Forest|Willy-Arnaud Zobo Boly": 74,
  "Nottingham Forest|Taiwo Michael Awoniyi": 74,
  "Nottingham Forest|Ryan James Yates": 73,
  "Nottingham Forest|Angus Gunn": 72,
  "Nottingham Forest|Zach MacFarlane Abbott": 71,

  // --- Sunderland ---
  "Sunderland|Granit Xhaka": 80,
  "Sunderland|Lutsharel Geertruida": 77,
  "Sunderland|Nordi Mukiele Mulere": 76,
  "Sunderland|Mouhamadou Habib Diarra": 76,
  "Sunderland|Simon Adingra": 76,
  "Sunderland|Brian Brobbey": 76,
  "Sunderland|Reinildo Isnard Mandava": 75,
  "Sunderland|Enzo Fée": 75,
  "Sunderland|Chemsdine Talbi": 75,
  "Sunderland|Bertrand Isidore Traoré": 75,
  "Sunderland|Wilson Isidor": 75,
  "Sunderland|Robin Roefs": 74,
  "Sunderland|Daniel George Ballard": 74,
  "Sunderland|Trai Hume": 74,
  "Sunderland|Dennis Cirkin": 74,
  "Sunderland|Noah Junior Sadiki": 74,
  "Sunderland|Daniel Neil": 74,
  "Sunderland|Eliezer Mayenda Dossou": 74,
  "Sunderland|Christopher John Rigg": 74,
  "Sunderland|Anthony Patterson": 73,
  "Sunderland|Fuka-Arthur Masuaku Kawela": 73,
  "Sunderland|Timothée Joseph Pembélé": 73,
  "Sunderland|Luke Terry O'Nien": 72,
  "Sunderland|Ian Carlo Poveda-Ocampo": 72,

  // --- Tottenham Hotspur ---
  "Tottenham Hotspur|Cristian Gabriel Romero": 84,
  "Tottenham Hotspur|Micky Ven": 83,
  "Tottenham Hotspur|Dejan Kulusevski": 82,
  "Tottenham Hotspur|Xavier Simons": 82,
  "Tottenham Hotspur|James Daniel Maddison": 81,
  "Tottenham Hotspur|Mohammed Kudus": 81,
  "Tottenham Hotspur|Dominic Ayodele Solanke-Mitchell": 80,
  "Tottenham Hotspur|Guglielmo Vicario": 79,
  "Tottenham Hotspur|Iyenoma Destiny Udogie": 79,
  "Tottenham Hotspur|Rodrigo Bentancur Colmán": 79,
  "Tottenham Hotspur|Pape Matar Sarr": 79,
  "Tottenham Hotspur|Brennan Price Johnson": 79,
  "Tottenham Hotspur|Randal Kolo Muani": 79,
  "Tottenham Hotspur|Lucas Bergvall": 78,
  "Tottenham Hotspur|Archie Gray": 77,
  "Tottenham Hotspur|Richarlison de Andrade": 77,
  "Tottenham Hotspur|Diop Spence": 77,
  "Tottenham Hotspur|Kevin Danso": 76,
  "Tottenham Hotspur|Yves Bissouma": 76,
  "Tottenham Hotspur|Mathys Henri Tel": 76,
  "Tottenham Hotspur|Radu Matei Drăgușin": 75,
  "Tottenham Hotspur|Wilson Odobert": 75,
  "Tottenham Hotspur|Antonín Kinský": 74,
  "Tottenham Hotspur|Benjamin Thomas Davies": 73,
  "Tottenham Hotspur|Kota Takai": 73,

  // --- West Ham United ---
  "West Ham United|Jarrod Bowen": 82,
  "West Ham United|Jean-Clair Todibo": 79,
  "West Ham United|Maximilian William Kilman": 78,
  "West Ham United|Aaron Wan-Bissaka": 78,
  "West Ham United|Crysencio Summerville": 78,
  "West Ham United|Tomáš Souček": 77,
  "West Ham United|James Ward-Prowse": 77,
  "West Ham United|Alphonse Francis Aréola": 77,
  "West Ham United|Konstantinos Mavropanos": 76,
  "West Ham United|Kyle Leonardus Walker-Peters": 76,
  "West Ham United|Mads Hermansen": 76,
  "West Ham United|Mateus Fernandes": 76,
  "West Ham United|Niclas Füllkrug": 75,
  "West Ham United|Guido Rodríguez": 75,
  "West Ham United|Soungoutou Magassa": 74,
  "West Ham United|Callum Wilson": 74,
  "West Ham United|Freddie Potts": 72,
  "West Ham United|George Robert Earthy": 71,
  "West Ham United|Łukasz Marek Fabiański": 70,

  // --- Wolverhampton Wanderers ---
  "Wolverhampton Wanderers|João Silva": 79,
  "Wolverhampton Wanderers|André Neto": 78,
  "Wolverhampton Wanderers|Jørgen Strand Larsen": 78,
  "Wolverhampton Wanderers|Ladislav Krejčí": 78,
  "Wolverhampton Wanderers|José Sá": 76,
  "Wolverhampton Wanderers|Marshall Nyasha Munetsi": 76,
  "Wolverhampton Wanderers|Jean-Ricner Bellegarde": 76,
  "Wolverhampton Wanderers|Yerson Mosquera Valdelamar": 75,
  "Wolverhampton Wanderers|Rodrigo Martins Gomes": 75,
  "Wolverhampton Wanderers|Toluwalase Emmanuel Arokodare": 75,
  "Wolverhampton Wanderers|Samuel Luke Johnstone": 75,
  "Wolverhampton Wanderers|Tote António Gomes": 74,
  "Wolverhampton Wanderers|Hugo Bueno López": 74,
  "Wolverhampton Wanderers|Jackson Tchatchoua": 74,
  "Wolverhampton Wanderers|Hee-chan Hwang": 74,
  "Wolverhampton Wanderers|Ki-Jana Delano Hoever": 73,
  "Wolverhampton Wanderers|David Møller Wolfe": 73,
  "Wolverhampton Wanderers|Matthew James Doherty": 72,
  "Wolverhampton Wanderers|Daniel Ian Bentley": 71,
  "Wolverhampton Wanderers|Tawanda Blessing Chirewa": 71,
};
