/**
 * Overall editoriali de La Liga 2025/26 — **stima nostra e dichiarata**, stessa scala e
 * stesso metodo di Serie A e Premier (CLAUDE.md sez. 2.2).
 *
 * Come per la Premier, sono valutati individualmente i giocatori riconoscibili; chi non
 * compare qui riceve il valore da fondo rosa per tier di club (`DEPTH_CAP_BY_TIER`).
 *
 * Scala: 88-92 fuoriclasse assoluti · 84-87 top da Champions · 80-83 titolari di alto
 * livello · 76-79 ossatura da Europa · 72-75 media classifica · 68-71 rosa · 62-67 fondo rosa.
 *
 * Nota sui nomi: il foglio usa l'anagrafica legale, quindi alcune chiavi non sono il nome
 * d'uso — "Federico Dipetta" è Valverde, "Jorge Resurrección Merodio" è Koke,
 * "Pedro González López" è Pedri, "Raphael Dias Belloli" è Raphinha.
 */
export const EDITORIAL_LIGA: Record<string, number> = {
  // --- Real Madrid ---
  "Real Madrid|Kylian Mbappé Lottin": 91,
  "Real Madrid|Jude Bellingham": 88,
  "Real Madrid|Thibaut Courtois": 88,
  "Real Madrid|Vinicius Junior": 88,
  "Real Madrid|Federico Dipetta": 86,
  "Real Madrid|Trent John Alexander-Arnold": 85,
  "Real Madrid|Rodrygo Goes": 84,
  "Real Madrid|Éder Gabriel Militão": 84,
  "Real Madrid|Eduardo Celmi Camavinga": 84,
  "Real Madrid|Aurélien Djani Tchouameni": 84,
  "Real Madrid|Antonio Rüdiger": 83,
  "Real Madrid|Daniel Carvajal Ramos": 82,
  "Real Madrid|Arda Güler": 82,
  "Real Madrid|Dean Donny Huijsen": 81,
  "Real Madrid|Brahim Abdelkader Díaz": 80,
  "Real Madrid|David Olatukunbo Alaba": 79,
  "Real Madrid|Ferland Sinna Mendy": 79,
  "Real Madrid|Daniel Ceballos Fernández": 78,
  "Real Madrid|Franco Mastantuono": 78,
  "Real Madrid|Endrick Sousa": 77,
  "Real Madrid|Andriy Lunin": 76,
  "Real Madrid|Álvaro Fernández Carreras": 76,
  "Real Madrid|Gonzalo García Torres": 75,

  // --- FC Barcelona ---
  "FC Barcelona|Raphael Dias Belloli": 87,
  "FC Barcelona|Pedro González López": 87,
  "FC Barcelona|Robert Lewandowski": 85,
  "FC Barcelona|Frenkie de Jong": 85,
  "FC Barcelona|Jules Olivier Koundé": 84,
  "FC Barcelona|Marc-André ter Stegen": 84,
  "FC Barcelona|Daniel Olmo Carvajal": 84,
  "FC Barcelona|Pau Cubarsí Paredes": 83,
  "FC Barcelona|Joan García Pons": 82,
  "FC Barcelona|Pablo Gavira": 81,
  "FC Barcelona|Alejandro Balde Martínez": 81,
  "FC Barcelona|Ferran Torres García": 80,
  "FC Barcelona|Fermín López Marín": 80,
  "FC Barcelona|Marcus Rashford": 80,
  "FC Barcelona|Andreas Bødtker Christensen": 78,
  "FC Barcelona|Wojciech Tomasz Szczęsny": 78,
  "FC Barcelona|Marc Casadó Torras": 77,
  "FC Barcelona|Eric García Martret": 76,
  "FC Barcelona|Marc Bernal Casas": 75,
  "FC Barcelona|Roony Bardghji": 74,
  "FC Barcelona|Gerard Martín Langreo": 74,

  // --- Atlético Madrid ---
  "Atlético Madrid|Julián Álvarez": 87,
  "Atlético Madrid|Jan Oblak": 85,
  "Atlético Madrid|Antoine Griezmann": 84,
  "Atlético Madrid|Robin Le Normand": 82,
  "Atlético Madrid|Dávid Hancko": 81,
  "Atlético Madrid|Alexander Sørloth": 80,
  "Atlético Madrid|Thiago Ezequiel Almada": 80,
  "Atlético Madrid|Nicolás Iván González": 80,
  "Atlético Madrid|Jorge Resurrección Merodio": 79,
  "Atlético Madrid|Pablo Barrios Rivas": 79,
  "Atlético Madrid|Giuliano Simeone Baldini": 79,
  "Atlético Madrid|Marcos Llorente Moreno": 79,
  "Atlético Madrid|Alejandro Baena Rodríguez": 79,
  "Atlético Madrid|Conor Gallagher": 78,
  "Atlético Madrid|Nahuel Molina Lucero": 78,
  "Atlético Madrid|Clément Lenglet": 77,
  "Atlético Madrid|Matteo Ruggeri": 77,
  "Atlético Madrid|Giacomo Raspadori": 77,
  "Atlético Madrid|Marc Pubill Pagés": 76,
  "Atlético Madrid|Javier Galán Gil": 74,
  "Atlético Madrid|Juan Agustín Musso": 74,

  // --- Athletic Club ---
  "Athletic Club|Nicholas Williams Arthuer": 85,
  "Athletic Club|Unai Simón Mendibil": 83,
  "Athletic Club|Oihan Sancet Tirapu": 81,
  "Athletic Club|Iñaki Williams Arthuer": 80,
  "Athletic Club|Daniel Vivian Moreno": 80,
  "Athletic Club|Aymeric Laporte": 80,
  "Athletic Club|Aitor Paredes Casamichana": 77,
  "Athletic Club|Gorka Guruzeta Rodríguez": 76,
  "Athletic Club|Mikel Jauregizar Alboniga": 76,
  "Athletic Club|Yuri Berchiche Izeta": 75,
  "Athletic Club|Alejandro Berenguer Remiro": 75,
  "Athletic Club|Jesús Areso Blanco": 75,
  "Athletic Club|Mikel Vesga Arruti": 74,
  "Athletic Club|Beñat Prados Díaz": 74,
  "Athletic Club|Unai Gómez Etxebarria": 74,
  "Athletic Club|Maroan Sannadi Harrouch": 73,
  "Athletic Club|Andoni Gorosabel Espinosa": 73,
  "Athletic Club|Iñigo Lekue Martínez": 73,

  // --- Real Sociedad ---
  "Real Sociedad|Mikel Oyarzabal Ugarte": 83,
  "Real Sociedad|Takefusa Kubo": 83,
  "Real Sociedad|Igor Zubeldía Elorza": 79,
  "Real Sociedad|Alejandro Remiro Gargallo": 79,
  "Real Sociedad|Brais Méndez Portela": 79,
  "Real Sociedad|Carlos Soler Barragán": 77,
  "Real Sociedad|Luka Sučić": 77,
  "Real Sociedad|Ander Barrenetxea Muguruza": 77,
  "Real Sociedad|Duje Ćaleta-Car": 77,
  "Real Sociedad|Orri Steinn Óskarsson": 76,
  "Real Sociedad|Gonçalo Guedes": 76,
  "Real Sociedad|Sergio Gómez Martín": 76,
  "Real Sociedad|Aritz Elustondo Irribaria": 75,
  "Real Sociedad|Aihen Muñoz Capellán": 75,
  "Real Sociedad|Beñat Turrientes Imaz": 75,
  "Real Sociedad|Álvaro Odriozola Arzallus": 74,
  "Real Sociedad|Pablo Marín Tejada": 74,
  "Real Sociedad|Umar Sadiq Mesbah": 74,
  "Real Sociedad|Arsen Zakharyan": 74,
  "Real Sociedad|Jon Gorrotxategi Etxaniz": 74,

  // --- Villarreal CF ---
  "Villarreal CF|Daniel Parejo Muñoz": 80,
  "Villarreal CF|Juan Marcos Foyth": 79,
  "Villarreal CF|Gerard Moreno Balagueró": 79,
  "Villarreal CF|Georges Mikautadze": 79,
  "Villarreal CF|Thomas Teye Partey": 79,
  "Villarreal CF|Ayoze Pérez Gutiérrez": 78,
  "Villarreal CF|Pape Alassane Gueye": 77,
  "Villarreal CF|Renato Veiga": 77,
  "Villarreal CF|Alberto Moleiro González": 77,
  "Villarreal CF|Nicolas Pépé": 76,
  "Villarreal CF|Logan Evans Costa": 76,
  "Villarreal CF|Luiz Júnior": 76,
  "Villarreal CF|Santiago Comesaña Veiga": 75,
  "Villarreal CF|Rafael Marín Zamora": 75,
  "Villarreal CF|Alfonso Pedraza Sag": 75,
  "Villarreal CF|Tajon Trevor Buchanan": 75,
  "Villarreal CF|Manor Solomon": 75,
  "Villarreal CF|Sergi Cardona Bermúdez": 74,
  "Villarreal CF|Ilias Akhomach Chakkour": 74,
  "Villarreal CF|Álvaro González": 73,
  "Villarreal CF|Willy Kambwala Ndengushi": 73,
  "Villarreal CF|Arnau Tenas Ureña": 73,

  // --- Real Betis Balompié ---
  "Real Betis Balompié|Antony Santos": 82,
  "Real Betis Balompié|Giovani Lo Celso": 80,
  "Real Betis Balompié|Pablo Fornals Malla": 79,
  "Real Betis Balompié|Abdessamad Ezzalzouli": 78,
  "Real Betis Balompié|Sofyan Amrabat": 77,
  "Real Betis Balompié|Rodrigo Riquelme Reche": 77,
  "Real Betis Balompié|Pau López Sabata": 77,
  "Real Betis Balompié|Marc Bartra Aregall": 76,
  "Real Betis Balompié|Natan Souza": 76,
  "Real Betis Balompié|Héctor Bellerín Moruno": 76,
  "Real Betis Balompié|Marc Roca Junqué": 76,
  "Real Betis Balompié|Cédric Bakambu": 75,
  "Real Betis Balompié|Sergi Altimira Clavell": 74,
  "Real Betis Balompié|Álvaro Vallés Rosa": 74,
  "Real Betis Balompié|Aitor Ruibal García": 74,
  "Real Betis Balompié|Ángel Ortiz Monterrey": 73,

  // --- Sevilla FC ---
  "Sevilla FC|César Azpilicueta Tanco": 77,
  "Sevilla FC|Tanguy-Austin Nianzou Kouassi": 76,
  "Sevilla FC|Lucien Jefferson Agoume": 76,
  "Sevilla FC|Nemanja Gudelj": 75,
  "Sevilla FC|Adnan Januzaj": 75,
  "Sevilla FC|Chidera Ejuke": 75,
  "Sevilla FC|Isaac Romero Bernal": 75,
  "Sevilla FC|Odysseas Vlachodimos": 75,
  "Sevilla FC|Fábio Cardoso": 74,
  "Sevilla FC|Alexis Sánchez": 74,
  "Sevilla FC|Ørjan Håskjold Nyland": 74,
  "Sevilla FC|Joan Jordán Moreno": 74,
  "Sevilla FC|Batista Adelino Mendy": 74,
  "Sevilla FC|Akor Jerome Adams": 74,

  // --- Valencia CF ---
  "Valencia CF|Javier Guerra Moreno": 78,
  "Valencia CF|Mouctar Diakhaby": 76,
  "Valencia CF|Hugo Duro Perales": 76,
  "Valencia CF|Lucas Beltrán": 76,
  "Valencia CF|Julen Agirrezabala Astúlez": 76,
  "Valencia CF|César Tárrega Requeni": 75,
  "Valencia CF|Baptiste Santamaria": 75,
  "Valencia CF|Largie Ramazani": 75,
  "Valencia CF|José Copete": 74,
  "Valencia CF|Dimitri Foulquier": 74,
  "Valencia CF|Thierry Rendall Correia": 74,
  "Valencia CF|Daniel Raba Antolín": 74,
  "Valencia CF|Arnaut Groeneveld": 74,
  "Valencia CF|Stole Dimitrievski": 74,
  "Valencia CF|Filip Ugrinić": 74,
  "Valencia CF|Jesús Vázquez Alcalde": 73,

  // --- RC Celta ---
  "RC Celta|Iago Aspas Juncal": 80,
  "RC Celta|Óscar Mingueza García": 77,
  "RC Celta|Borja Iglesias Quintas": 76,
  "RC Celta|Ferran Jutglà Blanch": 76,
  "RC Celta|Carl Starfelt": 75,
  "RC Celta|Ionuț Andrei Radu": 75,
  "RC Celta|Moriba Kourouma Kourouma": 75,
  "RC Celta|Bryan Zaragoza Martínez": 75,
  "RC Celta|Marcos Alonso Mendoza": 74,
  "RC Celta|Hugo Sotelo Gómez": 74,
  "RC Celta|Damián Rodríguez Sousa": 74,
  "RC Celta|Pablo Durán Fernández": 74,
  "RC Celta|Williot Theo Swedberg": 74,
  "RC Celta|Hugo Álvarez Antúnez": 74,
  "RC Celta|Iván Villar Martínez": 73,
  "RC Celta|Mihailo Ristić": 73,
  "RC Celta|Sergio Carreira Vilariño": 73,
  "RC Celta|Franco Emanuel Cervi": 73,

  // --- Girona FC ---
  "Girona FC|Viktor Tsygankov": 78,
  "Girona FC|Axel Witsel": 76,
  "Girona FC|Azzedine Ounahi": 76,
  "Girona FC|Iván Martín Núñez": 76,
  "Girona FC|Dominik Livaković": 76,
  "Girona FC|Vitor Reis": 76,
  "Girona FC|Vladyslav Vanat": 76,
  "Girona FC|Thomas Lemar": 75,
  "Girona FC|Arnau Martínez López": 75,
  "Girona FC|Bryan Gil Salvatierra": 75,
  "Girona FC|Daley Blind": 74,
  "Girona FC|Alejandro Francés Torrijo": 74,
  "Girona FC|Alexandre Moreno Lopera": 74,
  "Girona FC|Abel Ruiz Ortega": 74,
  "Girona FC|Cristian Portugués Manzanera": 74,
  "Girona FC|David López Silva": 72,
  "Girona FC|Joel Roca Casals": 72,

  // --- CA Osasuna ---
  "CA Osasuna|Ante Budimir": 77,
  "CA Osasuna|Aimar Oroz Huarte": 77,
  "CA Osasuna|Jon Moncayola Tollar": 76,
  "CA Osasuna|Jorge Herrando Oroz": 74,
  "CA Osasuna|Alejandro Catena Marugán": 74,
  "CA Osasuna|Flavien Boyomo": 74,
  "CA Osasuna|Sergio Herrera Pirón": 74,
  "CA Osasuna|Rubén García Santos": 74,
  "CA Osasuna|Sheraldo Rudi Becker": 74,
  "CA Osasuna|Lucas Torró Marset": 73,
  "CA Osasuna|Aitor Fernández Abarisketa": 73,
  "CA Osasuna|Abel Bretones Cruz": 73,
  "CA Osasuna|Valentin Rosier": 73,
  "CA Osasuna|Enrique Barja Alfonso": 73,
  "CA Osasuna|Iker Muñoz Cameros": 73,

  // --- Rayo Vallecano ---
  "Rayo Vallecano|Isaac Palazón Camacho": 77,
  "Rayo Vallecano|Andrei Florin Rațiu": 77,
  "Rayo Vallecano|Sergio Camello Pérez": 76,
  "Rayo Vallecano|Florian Lejeune": 75,
  "Rayo Vallecano|Álvaro García Rivera": 75,
  "Rayo Vallecano|Óscar Guido Trejo": 74,
  "Rayo Vallecano|Iván Balliu Campeny": 74,
  "Rayo Vallecano|Pathé Ismaël Ciss": 74,
  "Rayo Vallecano|Unai López Cabrera": 74,
  "Rayo Vallecano|Randy Nteka": 74,
  "Rayo Vallecano|Daniel Cárdenas Lindez": 73,
  "Rayo Vallecano|Pedro Díaz Fanjul": 73,
  "Rayo Vallecano|Gerard Gumbau Garriga": 73,

  // --- RCD Mallorca ---
  "RCD Mallorca|Vedat Muriqi": 78,
  "RCD Mallorca|Sergi Darder Moll": 77,
  "RCD Mallorca|Martin Valjent": 76,
  "RCD Mallorca|Samuel Costa": 76,
  "RCD Mallorca|Pablo Torre Carral": 76,
  "RCD Mallorca|Marash Kumbulla": 74,
  "RCD Mallorca|Manuel Morlanes Ariño": 74,
  "RCD Mallorca|Takuma Asano": 74,
  "RCD Mallorca|Leonardo Román Riquelme": 74,
  "RCD Mallorca|Jan Virgili Tenas": 74,
  "RCD Mallorca|Antonio Sánchez Navarro": 73,
  "RCD Mallorca|Omar Mascarell González": 73,
  "RCD Mallorca|Antonio Latorre Grueso": 73,
  "RCD Mallorca|Javier Llabrés Exposito": 73,

  // --- RCD Espanyol ---
  "RCD Espanyol|Javier Puado Díaz": 76,
  "RCD Espanyol|Marko Dmitrović": 75,
  "RCD Espanyol|Fernando Calero Villa": 75,
  "RCD Espanyol|Omar El Hilali": 75,
  "RCD Espanyol|Tyrhys Dolan": 74,
  "RCD Espanyol|Roberto Fernández Jaén": 74,
  "RCD Espanyol|Pol Lozano Vizuete": 74,
  "RCD Espanyol|Ramón Terrats Espacio": 74,
  "RCD Espanyol|Clemens Riedel": 74,
  "RCD Espanyol|Carlos Romero Serrano": 74,
  "RCD Espanyol|Luca Koleosho": 74,
  "RCD Espanyol|Pere Milla Peña": 73,
  "RCD Espanyol|Eduardo Expósito Jaén": 73,
  "RCD Espanyol|Charles Monginda Pickel": 73,

  // --- Deportivo Alavés ---
  "Deportivo Alavés|Antonio Sivera Salvá": 75,
  "Deportivo Alavés|Carlos Vicente Robles": 75,
  "Deportivo Alavés|Jon Pacheco Dozagarat": 74,
  "Deportivo Alavés|Facundo Tomás Garcés": 74,
  "Deportivo Alavés|Jon Guridi Aldalur": 74,
  "Deportivo Alavés|Denis Suárez Fernández": 74,
  "Deportivo Alavés|Lucas Ariel Boyé": 74,
  "Deportivo Alavés|Moussa Diarra": 73,
  "Deportivo Alavés|Facundo Nahuel Tenaglia": 73,
  "Deportivo Alavés|Antonio Blanco Conde": 73,
  "Deportivo Alavés|Carles Aleñá Castillo": 73,
  "Deportivo Alavés|Abderrahman Rebbach": 73,
  "Deportivo Alavés|Mariano Díaz Mejía": 71,

  // --- Getafe CF ---
  "Getafe CF|David Soria Solís": 76,
  "Getafe CF|Borja Mayoral Moya": 75,
  "Getafe CF|Dakonam Ortega Djené": 74,
  "Getafe CF|Domingos Duarte": 74,
  "Getafe CF|Luis Milla Manzanares": 74,
  "Getafe CF|Abdelkabir Abqar": 73,
  "Getafe CF|Yvan Neyou Noupa": 73,
  "Getafe CF|Abu Kamara": 73,
  "Getafe CF|Francisco Femenía Far": 72,
  "Getafe CF|Diego Rico Salguero": 72,
  "Getafe CF|Adrián Liso Lahoz": 72,

  // --- Elche CF ---
  "Elche CF|André Silva": 75,
  "Elche CF|Federico Redondo Solari": 74,
  "Elche CF|Rafael Mir Vicente": 73,
  "Elche CF|Aleix Febas Pérez": 73,
  "Elche CF|David Leopold Affengruber": 73,
  "Elche CF|Víctor Chust García": 73,
  "Elche CF|Ignacio Peña Sotorres": 73,
  "Elche CF|Grady George Diangana": 73,
  "Elche CF|Héctor Fort García": 73,
  "Elche CF|Marc Aguado Pallarés": 73,
  "Elche CF|Pedro Bigas Rigo": 72,
  "Elche CF|Bambo Diaby Diaby": 72,
  "Elche CF|Léo Pétrot": 72,
  "Elche CF|Álvaro Núñez Cobo": 72,
  "Elche CF|José Pomares": 72,

  // --- Levante UD ---
  "Levante UD|Mathew David Ryan": 74,
  "Levante UD|Carlos Álvarez Rivera": 74,
  "Levante UD|Roger Brugué Ayguadé": 73,
  "Levante UD|Unai Elgezabal Udondo": 72,
  "Levante UD|Matías Agustín Moreno": 72,
  "Levante UD|Goduine Koyalipou": 72,
  "Levante UD|Jeremy Toljan": 72,
  "Levante UD|Unai Vencedor Paris": 72,
  "Levante UD|Oriol Rey Erenas": 72,
  "Levante UD|Iker Losada Aragunde": 72,
  "Levante UD|Carlos Espí Escrihuela": 71,

  // --- Real Oviedo ---
  "Real Oviedo|Leander Dendoncker": 74,
  "Real Oviedo|David Carmo": 74,
  "Real Oviedo|Eric Bertrand Bailly": 73,
  "Real Oviedo|Horațiu Alexandru Moldovan": 73,
  "Real Oviedo|Josip Brekalo": 73,
  "Real Oviedo|Luka Ilić": 73,
  "Real Oviedo|Santiago Cazorla González": 72,
  "Real Oviedo|David Costas Cordal": 72,
  "Real Oviedo|Santiago Colombatto": 72,
  "Real Oviedo|Haissem Hassan": 72,
  "Real Oviedo|Ilyas Chaira Oihi": 72,
  "Real Oviedo|Aarón Escandell Banacloche": 72,
  "Real Oviedo|Kwasi Sibo": 72,
  "Real Oviedo|Oviemuno Dominic Ejaria": 72,
  "Real Oviedo|Álex Forés Mendoza": 71,
};
