/**
 * Overall editoriali della Bundesliga 2025/26 — **stima nostra e dichiarata**, stessa scala
 * e stesso metodo di Serie A, Premier e Liga (CLAUDE.md sez. 2.2).
 *
 * Scala: 88-92 fuoriclasse assoluti · 84-87 top da Champions · 80-83 titolari di alto
 * livello · 76-79 ossatura da Europa · 72-75 media classifica · 68-71 rosa · 62-67 fondo rosa.
 *
 * Nota sulla forma del campionato (richiesta esplicita dell'utente): il Bayern è un club
 * top-5 mondiale e la sua fascia alta va allineata a quella di Real/Barça/City, ma sotto di
 * lui la Bundesliga è meno profonda della Premier — la distanza tra la prima e la decima è
 * volutamente più ampia che in Inghilterra.
 *
 * Nota sui nomi: il foglio usa l'anagrafica legale, quindi alcune chiavi non sono il nome
 * d'uso — "Waldemar Anton -" ha il trattino nel sorgente, "Dayotchanculle Oswald
 * Upamecano" è Dayot Upamecano, "Sepe Elye Wahi" è Elye Wahi.
 */
export const EDITORIAL_BUNDESLIGA: Record<string, number> = {
  // --- FC Bayern München ---
  "FC Bayern München|Harry Edward Kane": 91,
  "FC Bayern München|Jamal Musiala": 88,
  "FC Bayern München|Michael Akpovie Olise": 87,
  "FC Bayern München|Joshua Walter Kimmich": 87,
  "FC Bayern München|Alphonso Boyle Davies": 84,
  "FC Bayern München|Jonathan Glao Tah": 84,
  "FC Bayern München|Dayotchanculle Oswald Upamecano": 84,
  "FC Bayern München|Manuel Peter Neuer": 84,
  "FC Bayern München|Min-jae Kim": 82,
  "FC Bayern München|Serge David Gnabry": 82,
  "FC Bayern München|Nicolas Jackson": 81,
  "FC Bayern München|Leon Christoph Goretzka": 81,
  "FC Bayern München|Konrad Laimer": 81,
  "FC Bayern München|Aleksandar Pavlović": 80,
  "FC Bayern München|Josip Stanišić": 78,
  "FC Bayern München|Raphaël Guerreiro": 78,
  "FC Bayern München|Sacha Boey": 76,
  "FC Bayern München|Hiroki Ito": 76,
  "FC Bayern München|Tom Bischof": 75,
  "FC Bayern München|Jonas Kurt Urbig": 74,
  "FC Bayern München|Lennart Karl": 74,
  "FC Bayern München|Sven Ulreich": 71,
  "FC Bayern München|Luis Marulanda": 68,
  "FC Bayern München|David Daiber": 66,
  "FC Bayern München|Jannis Bärtl": 64,
  "FC Bayern München|Leon Klanac": 64,

  // --- Bayer 04 Leverkusen ---
  "Bayer 04 Leverkusen|Patrik Schick": 84,
  "Bayer 04 Leverkusen|Alejandro Grimaldo García": 84,
  "Bayer 04 Leverkusen|Edmond Fayçal Tapsoba": 82,
  "Bayer 04 Leverkusen|Robert Andrich": 80,
  "Bayer 04 Leverkusen|Malik Leon Tillman": 80,
  "Bayer 04 Leverkusen|Exequiel Alejandro Palacios": 79,
  "Bayer 04 Leverkusen|Mark Flekken": 79,
  "Bayer 04 Leverkusen|Jarell Amorin Quansah": 79,
  "Bayer 04 Leverkusen|Loïc Badé": 79,
  "Bayer 04 Leverkusen|Lucas Vázquez Iglesias": 78,
  "Bayer 04 Leverkusen|Nathan Tella": 78,
  "Bayer 04 Leverkusen|Martin Terrier": 78,
  "Bayer 04 Leverkusen|Eliesse Ben Seghir": 78,
  "Bayer 04 Leverkusen|Aleix García Serrano": 78,
  "Bayer 04 Leverkusen|Jonas Hofmann": 77,
  "Bayer 04 Leverkusen|Ibrahim Maza": 76,
  "Bayer 04 Leverkusen|Claudio Jeremías Echeverri": 76,
  "Bayer 04 Leverkusen|Jeanuël Belocian": 75,
  "Bayer 04 Leverkusen|Ernest Poku": 75,
  "Bayer 04 Leverkusen|Arthur Soares": 74,
  "Bayer 04 Leverkusen|Janis Jonathan Blaswich": 73,
  "Bayer 04 Leverkusen|Christian Michel Kofane": 72,
  "Bayer 04 Leverkusen|Alejo Sarco": 71,
  "Bayer 04 Leverkusen|Axel Tape-Kobrissa": 68,
  "Bayer 04 Leverkusen|Niklas Lomb": 68,
  "Bayer 04 Leverkusen|Jeremiah Mensah": 66,
  "Bayer 04 Leverkusen|Ignacio Carballo": 66,

  // --- Borussia Dortmund ---
  "Borussia Dortmund|Serhou Yadaly Guirassy": 84,
  "Borussia Dortmund|Gregor Kobel": 84,
  "Borussia Dortmund|Nico Cedric Schlotterbeck": 83,
  "Borussia Dortmund|Julian Brandt": 80,
  "Borussia Dortmund|Karim-David Adeyemi": 80,
  "Borussia Dortmund|Pascal Groß": 79,
  "Borussia Dortmund|Waldemar Anton -": 79,
  "Borussia Dortmund|Maximilian Beier": 79,
  "Borussia Dortmund|Marcel Sabitzer": 79,
  "Borussia Dortmund|Ramy Bensebaini": 78,
  "Borussia Dortmund|Niklas Süle": 78,
  "Borussia Dortmund|Felix Kalu Nmecha": 78,
  "Borussia Dortmund|Emre Can": 77,
  "Borussia Dortmund|Jobe Bellingham": 77,
  "Borussia Dortmund|Julian Ryerson": 77,
  "Borussia Dortmund|Yan Bueno Couto": 76,
  "Borussia Dortmund|Fábio Silva": 76,
  "Borussia Dortmund|Daniel Svensson": 75,
  "Borussia Dortmund|Carney Chibueze Chukwuemeka": 75,
  "Borussia Dortmund|Salih Özcan": 74,
  "Borussia Dortmund|Julien Duranville": 73,
  "Borussia Dortmund|Aarón Anselmino": 73,
  "Borussia Dortmund|William Cole Campbell": 72,
  "Borussia Dortmund|Filippo Calixte Mané": 70,
  "Borussia Dortmund|Almugera Kabar": 69,
  "Borussia Dortmund|Patrick Drewes": 69,
  "Borussia Dortmund|Silas Ostrzinski": 66,
  "Borussia Dortmund|Alexander Niklas Meyer-Schade": 64,

  // --- RB Leipzig ---
  "RB Leipzig|Castello Junior Lukeba": 80,
  "RB Leipzig|Xaver Schlager": 79,
  "RB Leipzig|David Raum": 79,
  "RB Leipzig|Antonio Nusa": 79,
  "RB Leipzig|Péter Gulácsi": 78,
  "RB Leipzig|Christoph Baumgartner": 78,
  "RB Leipzig|Nicolas Seiwald": 78,
  "RB Leipzig|Benjamin Henrichs": 77,
  "RB Leipzig|Saint-Cyr Johan Bakayoko": 77,
  "RB Leipzig|Timo Werner": 76,
  "RB Leipzig|Amadou Haïdara": 76,
  "RB Leipzig|El Chadaille Bitshiabu": 76,
  "RB Leipzig|Vilmos Tamás Orbán": 76,
  "RB Leipzig|Lukas Manuel Klostermann": 75,
  "RB Leipzig|Forzan Assan Ouédraogo": 75,
  "RB Leipzig|Kevin Kampl": 74,
  "RB Leipzig|Maarten Vandevoordt": 74,
  "RB Leipzig|Kosta Nedeljkovic": 74,
  "RB Leipzig|Bote Baku": 74,
  "RB Leipzig|Ezechiel Banzuzi": 73,
  "RB Leipzig|Yan Diomande": 73,
  "RB Leipzig|Andrija Maksimović": 72,
  "RB Leipzig|Max Finkgräfe": 72,
  "RB Leipzig|Rômulo Cruz": 70,
  "RB Leipzig|Viggo Gebel": 68,
  "RB Leipzig|Joyeux Masanka Bungi": 66,
  "RB Leipzig|Tidiam Gomis": 66,
  "RB Leipzig|Conrad Schandorf": 65,
  "RB Leipzig|Leopold Zingerle": 65,

  // --- Eintracht Frankfurt ---
  "Eintracht Frankfurt|Robin Leon Koch": 80,
  "Eintracht Frankfurt|Jonathan Michael Burkardt": 79,
  "Eintracht Frankfurt|Hugo Emanuel Larsson": 79,
  "Eintracht Frankfurt|Ritsu Doan": 78,
  "Eintracht Frankfurt|Mario Götze": 77,
  "Eintracht Frankfurt|Ellyes Joris Skhiri": 77,
  "Eintracht Frankfurt|Arthur Nicolas Theate": 77,
  "Eintracht Frankfurt|Michael Zetterer": 76,
  "Eintracht Frankfurt|Ansgar Knauff": 76,
  "Eintracht Frankfurt|Rasmus Nissen Kristensen": 76,
  "Eintracht Frankfurt|Sepe Elye Wahi": 76,
  "Eintracht Frankfurt|Jean-Mattéo Bahoya Négoce": 76,
  "Eintracht Frankfurt|Can Yılmaz Uzun": 75,
  "Eintracht Frankfurt|Aurèle Florian Amenda": 75,
  "Eintracht Frankfurt|Nathaniel Brown": 75,
  "Eintracht Frankfurt|Farès Chaïbi": 74,
  "Eintracht Frankfurt|Mahmoud Dahoud": 74,
  "Eintracht Frankfurt|Aurélio Buta": 73,
  "Eintracht Frankfurt|Michy Batshuayi-Atunga": 73,
  "Eintracht Frankfurt|Kauã Santos": 73,
  "Eintracht Frankfurt|Oscar Winther Højlund": 72,
  "Eintracht Frankfurt|Ngankam Ngankam": 71,
  "Eintracht Frankfurt|Timothy Chandler": 70,
  "Eintracht Frankfurt|Pharrell Nnamdi Collins": 69,
  "Eintracht Frankfurt|Elias Niklas Baum": 68,
  "Eintracht Frankfurt|Fousseny Doumbia": 66,
  "Eintracht Frankfurt|Fenyő Noah Gabriel": 65,
  "Eintracht Frankfurt|Jens Grahl": 65,
  "Eintracht Frankfurt|Amil Siljevic": 63,

  // --- VfB Stuttgart ---
  "VfB Stuttgart|Alexander Nübel": 81,
  "VfB Stuttgart|Angelo Stiller": 81,
  "VfB Stuttgart|Deniz Undav": 81,
  "VfB Stuttgart|Ermedin Demirović": 78,
  "VfB Stuttgart|Maximilian Mittelstädt": 78,
  "VfB Stuttgart|Jamie Leweling": 77,
  "VfB Stuttgart|Chris Jan Führich": 77,
  "VfB Stuttgart|Bilal El Khannouss": 77,
  "VfB Stuttgart|Atakan Karazor": 76,
  "VfB Stuttgart|Jeffrey Chabot": 76,
  "VfB Stuttgart|Finn Jeltsch": 75,
  "VfB Stuttgart|Ameen Al Dakhil": 75,
  "VfB Stuttgart|Lorenz Assignon": 75,
  "VfB Stuttgart|Dan-Axel Zagadou": 74,
  "VfB Stuttgart|Josha Vagnoman": 74,
  "VfB Stuttgart|Tiago Tomás": 74,
  "VfB Stuttgart|Ramon Hendriks": 74,
  "VfB Stuttgart|Badredine Bouanani": 74,
  "VfB Stuttgart|Silas Katompa-Mvumpa": 74,
  "VfB Stuttgart|Luca Antony Jaquez": 73,
  "VfB Stuttgart|Leonidas Stergiou": 73,
  "VfB Stuttgart|Justin Diehl": 72,
  "VfB Stuttgart|Pascal Stenzel": 72,
  "VfB Stuttgart|Yannik Keitel": 72,
  "VfB Stuttgart|Nikolas Terkelsen Nartey": 71,
  "VfB Stuttgart|Noah Yanis Darvich": 70,
  "VfB Stuttgart|Fabian Bredlow": 70,
  "VfB Stuttgart|Lazar Jovanović": 68,
  "VfB Stuttgart|Stefan Drljača": 66,
  "VfB Stuttgart|Mirza Ćatović": 65,
  "VfB Stuttgart|José Baixauli": 64,
  "VfB Stuttgart|Florian Pascal Hellstern": 63,

  // --- SC Freiburg ---
  "SC Freiburg|Vincenzo Grifo": 78,
  "SC Freiburg|Noah Atubolu": 77,
  "SC Freiburg|Matthias Lukas Ginter": 76,
  "SC Freiburg|Philipp Lienhart": 76,
  "SC Freiburg|Christian Günter": 75,
  "SC Freiburg|Maximilian Eggestein": 75,
  "SC Freiburg|Eren Sami Dinkçi": 75,
  "SC Freiburg|Nicolas Höfler": 74,
  "SC Freiburg|Johan Manzambi": 74,
  "SC Freiburg|Igor Matanović": 74,
  "SC Freiburg|Jan-Niklas Beste": 74,
  "SC Freiburg|Lucas Höler": 73,
  "SC Freiburg|Maximilian Marcus Philipp": 73,
  "SC Freiburg|Maximilian Rosenfelder": 73,
  "SC Freiburg|Patrick Osterhage": 73,
  "SC Freiburg|Yuito Suzuki": 73,
  "SC Freiburg|Lukas Kübler": 72,
  "SC Freiburg|Chukwubuike Junior Adamu": 72,
  "SC Freiburg|Philipp Treu": 72,
  "SC Freiburg|Daniel-Kofi Kyereh": 72,
  "SC Freiburg|Cyriaque Irié": 71,
  "SC Freiburg|Anthony Jung": 71,
  "SC Freiburg|Florian Müller": 71,
  "SC Freiburg|Derry Lionel Scherhant": 70,
  "SC Freiburg|Jordy Makengo Basambundu": 68,
  "SC Freiburg|Jannik Huth": 67,
  "SC Freiburg|Bruno Ifechukwu Ogbus": 65,

  // --- SV Werder Bremen ---
  "SV Werder Bremen|Victor Okoh Boniface": 76,
  "SV Werder Bremen|Marco Friedl": 75,
  "SV Werder Bremen|Romano Christian Schmid": 75,
  "SV Werder Bremen|Mitchell-Elijah Weiser": 75,
  "SV Werder Bremen|Karl Jakob Hein": 74,
  "SV Werder Bremen|Maximilian Wöber": 74,
  "SV Werder Bremen|Jens Dalsgaard Stage": 74,
  "SV Werder Bremen|Niklas Stark": 73,
  "SV Werder Bremen|Leonardo Bittencourt": 73,
  "SV Werder Bremen|Marco Grüll": 73,
  "SV Werder Bremen|Amos Pieper": 73,
  "SV Werder Bremen|Senne Maaike Lynen": 73,
  "SV Werder Bremen|Yukinari Sugawara": 73,
  "SV Werder Bremen|Keke Maximilian Topp": 73,
  "SV Werder Bremen|Skelly Alvero": 73,
  "SV Werder Bremen|Justin Gideon Njinmah": 72,
  "SV Werder Bremen|Isak Hansen-Aarøen": 72,
  "SV Werder Bremen|Isaac Osa's Schmidt": 72,
  "SV Werder Bremen|Felix Agu": 71,
  "SV Werder Bremen|Julián Malatini": 71,
  "SV Werder Bremen|Olivier Deman": 71,
  "SV Werder Bremen|Mio Backhaus": 71,
  "SV Werder Bremen|Patrice Čović": 68,
  "SV Werder Bremen|Dikeni-Rafid Salifou": 68,
  "SV Werder Bremen|Abdoul Karim Coulibaly": 68,
  "SV Werder Bremen|Wesley Adeh": 67,
  "SV Werder Bremen|Cameron Castro": 65,
  "SV Werder Bremen|Salim Amani Musah": 65,
  "SV Werder Bremen|Markus Kolke": 65,
  "SV Werder Bremen|Mick Schmetgens": 64,
  "SV Werder Bremen|Stefan Smarkalev": 63,

  // --- TSG 1899 Hoffenheim ---
  "TSG 1899 Hoffenheim|Oliver Baumann": 78,
  "TSG 1899 Hoffenheim|Andrej Kramarić": 77,
  "TSG 1899 Hoffenheim|Ozan Muhammed Kabak": 76,
  "TSG 1899 Hoffenheim|Adam Hložek": 75,
  "TSG 1899 Hoffenheim|Vladimír Coufal": 74,
  "TSG 1899 Hoffenheim|Grischa Prömel": 74,
  "TSG 1899 Hoffenheim|Fisnik Asllani": 74,
  "TSG 1899 Hoffenheim|Alexander Prass": 74,
  "TSG 1899 Hoffenheim|Tim Lemperle": 74,
  "TSG 1899 Hoffenheim|Leon Avdullahu": 73,
  "TSG 1899 Hoffenheim|Wouter Burger": 73,
  "TSG 1899 Hoffenheim|Ihlas Bebou": 73,
  "TSG 1899 Hoffenheim|Koki Machida": 73,
  "TSG 1899 Hoffenheim|Robin Hranáč": 73,
  "TSG 1899 Hoffenheim|Umut Deger Tohumcu": 72,
  "TSG 1899 Hoffenheim|Bazoumana Touré": 72,
  "TSG 1899 Hoffenheim|Albian Hajdari": 72,
  "TSG 1899 Hoffenheim|Mërgim Berisha": 72,
  "TSG 1899 Hoffenheim|Kevin Akpoguma": 71,
  "TSG 1899 Hoffenheim|Dennis Geiger": 71,
  "TSG 1899 Hoffenheim|Arthur Largura Chaves": 71,
  "TSG 1899 Hoffenheim|Valentin Gendrey": 71,
  "TSG 1899 Hoffenheim|Max Moerstedt": 70,
  "TSG 1899 Hoffenheim|Bernardo Junior": 70,
  "TSG 1899 Hoffenheim|Muhammed Mehmet Damar": 68,
  "TSG 1899 Hoffenheim|Luka Đurić": 66,
  "TSG 1899 Hoffenheim|Hennes Behrens": 65,
  "TSG 1899 Hoffenheim|David Ntusu": 64,
  "TSG 1899 Hoffenheim|Deniz Zeitler": 64,
  "TSG 1899 Hoffenheim|Kelven Olagie Frees": 64,
  "TSG 1899 Hoffenheim|Precious Benjamin": 63,
  "TSG 1899 Hoffenheim|Luca Dante Philipp": 63,
  "TSG 1899 Hoffenheim|Lúkas Blöndal Petersson": 63,

  // --- VfL Wolfsburg ---
  "VfL Wolfsburg|Christian Dannemann Eriksen": 77,
  "VfL Wolfsburg|Mohamed Amoura": 77,
  "VfL Wolfsburg|Kamil Mieczysław Grabara": 75,
  "VfL Wolfsburg|Maximilian Arnold": 75,
  "VfL Wolfsburg|Lovro Majer": 74,
  "VfL Wolfsburg|Andreas Skov Olsen": 74,
  "VfL Wolfsburg|Jesper Grænge Lindstrøm": 74,
  "VfL Wolfsburg|Konstantinos Koulierakis": 74,
  "VfL Wolfsburg|Mattias Olof Svanberg": 74,
  "VfL Wolfsburg|Jonas Older Wind": 74,
  "VfL Wolfsburg|Joakim Mæhle Pedersen": 73,
  "VfL Wolfsburg|Patrick Wimmer": 73,
  "VfL Wolfsburg|Denis Vavro": 73,
  "VfL Wolfsburg|Moritz Jenz": 72,
  "VfL Wolfsburg|Saël Kumbedi Nseke": 72,
  "VfL Wolfsburg|Kilian Fischer": 71,
  "VfL Wolfsburg|Yannick Gerhardt": 71,
  "VfL Wolfsburg|Kevin Alexander Paredes": 71,
  "VfL Wolfsburg|Adam Daghim": 70,
  "VfL Wolfsburg|Bence Dárdai": 70,
  "VfL Wolfsburg|Jenson Seelt": 70,
  "VfL Wolfsburg|Rogério Silva": 70,
  "VfL Wolfsburg|Marius Müller": 70,
  "VfL Wolfsburg|Dženan Pejčinović": 68,
  "VfL Wolfsburg|Pavao Pervan": 67,
  "VfL Wolfsburg|Aaron Zehnter": 66,
  "VfL Wolfsburg|Vinicius Costa": 65,
  "VfL Wolfsburg|Mathys Angély": 64,
  "VfL Wolfsburg|Jakub Zieliński": 63,

  // --- 1. FSV Mainz 05 ---
  "1. FSV Mainz 05|Nadiem Amiri": 75,
  "1. FSV Mainz 05|Robin Zentner": 74,
  "1. FSV Mainz 05|Silvan Dominic Widmer": 73,
  "1. FSV Mainz 05|Andreas Schjølberg Hanche-Olsen": 73,
  "1. FSV Mainz 05|Benedict Hollerbach": 73,
  "1. FSV Mainz 05|Paul Nebel": 73,
  "1. FSV Mainz 05|Jae-sung Lee": 73,
  "1. FSV Mainz 05|Kaishu Sano": 73,
  "1. FSV Mainz 05|Dominik Kohr": 72,
  "1. FSV Mainz 05|Phillipp Mwene": 72,
  "1. FSV Mainz 05|Anthony Caci": 72,
  "1. FSV Mainz 05|Nelson Weiper": 72,
  "1. FSV Mainz 05|Armindo Sieb": 72,
  "1. FSV Mainz 05|Sota Kawasaki": 72,
  "1. FSV Mainz 05|Maxim Leitsch": 72,
  "1. FSV Mainz 05|Arnaud Dominique Nordin": 71,
  "1. FSV Mainz 05|Lennard Patrick Maloney": 71,
  "1. FSV Mainz 05|Stefan Bell": 70,
  "1. FSV Mainz 05|Nikolas Konrad Veratschnig": 70,
  "1. FSV Mainz 05|Ben Bobzien": 70,
  "1. FSV Mainz 05|William Bøving Wick": 70,
  "1. FSV Mainz 05|Danny Costa": 69,
  "1. FSV Mainz 05|Niklas Tauer": 69,
  "1. FSV Mainz 05|Kacper Potulski": 66,
  "1. FSV Mainz 05|Daniel Batz": 66,
  "1. FSV Mainz 05|Daniel Gleiber": 65,
  "1. FSV Mainz 05|Kasey Bos": 65,
  "1. FSV Mainz 05|Maxim Bora Dal": 64,
  "1. FSV Mainz 05|Konstantin Schopp": 64,
  "1. FSV Mainz 05|Lasse Finn Rieß": 63,

  // --- 1. FC Union Berlin ---
  "1. FC Union Berlin|Frederik Riis Rønnow": 74,
  "1. FC Union Berlin|Diogo Leite": 73,
  "1. FC Union Berlin|Danilho Raimundo Doekhi": 73,
  "1. FC Union Berlin|Rani Khedira": 72,
  "1. FC Union Berlin|Josip Juranović": 72,
  "1. FC Union Berlin|Leopold Querfeld": 72,
  "1. FC Union Berlin|Andrej Ilić": 72,
  "1. FC Union Berlin|Oliver Jasen Burke": 72,
  "1. FC Union Berlin|Woo-yeong Jeong": 72,
  "1. FC Union Berlin|Janik Haberer": 72,
  "1. FC Union Berlin|Robert Faxe Skov": 72,
  "1. FC Union Berlin|Stanley Pierre Nsoki": 72,
  "1. FC Union Berlin|Tom Alexander Rothe": 72,
  "1. FC Union Berlin|Marin Ljubičić": 71,
  "1. FC Union Berlin|Ilyas Ansah": 71,
  "1. FC Union Berlin|Derrick Arthur Köhn": 71,
  "1. FC Union Berlin|András Schäfer": 71,
  "1. FC Union Berlin|Alex Král": 71,
  "1. FC Union Berlin|Christopher Trimmel": 70,
  "1. FC Union Berlin|Aljoscha Kemlein": 70,
  "1. FC Union Berlin|Tim Skarke": 69,
  "1. FC Union Berlin|Matheo Raab": 68,
  "1. FC Union Berlin|Dmytro Bogdanov": 66,
  "1. FC Union Berlin|Livan Baha Burcu": 65,
  "1. FC Union Berlin|David Preu": 64,
  "1. FC Union Berlin|Oluwaseun Ogbemudia": 64,
  "1. FC Union Berlin|Andrik Markgraf": 64,
  "1. FC Union Berlin|Carl Klaus": 64,

  // --- Borussia Mönchengladbach ---
  "Borussia Mönchengladbach|Nico Elvedi": 74,
  "Borussia Mönchengladbach|Tim Kleindienst": 74,
  "Borussia Mönchengladbach|Franck Honorat": 73,
  "Borussia Mönchengladbach|Kevin Stöger": 73,
  "Borussia Mönchengladbach|Rocco Reitz": 73,
  "Borussia Mönchengladbach|Kevin Diks Bakarbessy": 73,
  "Borussia Mönchengladbach|Jonas Omlin": 73,
  "Borussia Mönchengladbach|Florian Christian Neuhaus": 72,
  "Borussia Mönchengladbach|Joseph Michael Scally": 72,
  "Borussia Mönchengladbach|Luca Netz": 72,
  "Borussia Mönchengladbach|Shuto Machino": 72,
  "Borussia Mönchengladbach|Giovanni Alejandro Reyna": 72,
  "Borussia Mönchengladbach|Marvin Friedrich": 71,
  "Borussia Mönchengladbach|Robin Hack": 71,
  "Borussia Mönchengladbach|Nathan Ngoumou Minpole": 71,
  "Borussia Mönchengladbach|Jens Castrop": 71,
  "Borussia Mönchengladbach|Haris Tabaković": 71,
  "Borussia Mönchengladbach|Fabio Cristian Chiarodia": 70,
  "Borussia Mönchengladbach|Philipp Sander": 70,
  "Borussia Mönchengladbach|Yannik Engelhardt": 69,
  "Borussia Mönchengladbach|Lukas Ullrich": 69,
  "Borussia Mönchengladbach|Moritz Nicolas": 69,
  "Borussia Mönchengladbach|Grant-Leon Ranos": 68,
  "Borussia Mönchengladbach|Oscar Luigi Fraulo": 67,
  "Borussia Mönchengladbach|Charles Kwablan Herrmann": 66,
  "Borussia Mönchengladbach|Tiago Pereira Cardoso": 65,
  "Borussia Mönchengladbach|Niklas Swider": 64,
  "Borussia Mönchengladbach|Tobias Sippel": 64,

  // --- FC Augsburg ---
  "FC Augsburg|Finn Gilbert Dahmen": 73,
  "FC Augsburg|Jeffrey Gouweleeuw": 72,
  "FC Augsburg|Kristijan Jakić": 72,
  "FC Augsburg|Alexis Claude-Maurice": 72,
  "FC Augsburg|Elias Saad": 72,
  "FC Augsburg|Fabian Rieder": 72,
  "FC Augsburg|Phillip Tietz": 71,
  "FC Augsburg|Marius Wolf": 71,
  "FC Augsburg|Mads Pedersen": 71,
  "FC Augsburg|Arne Maier": 71,
  "FC Augsburg|Cédric Zesiger": 71,
  "FC Augsburg|Chrislain Matsima": 71,
  "FC Augsburg|Dimitris Giannoulis": 70,
  "FC Augsburg|Maximilian Bauer": 70,
  "FC Augsburg|Keven Schlotterbeck": 70,
  "FC Augsburg|Elvis Rexhbeçaj": 70,
  "FC Augsburg|Han-Noah Massengo": 70,
  "FC Augsburg|Mert Kömür": 70,
  "FC Augsburg|Anton Kade": 69,
  "FC Augsburg|Ismaël Gharbi Álvarez": 69,
  "FC Augsburg|Nediljko Labrović": 69,
  "FC Augsburg|Robin Fellhauer": 67,
  "FC Augsburg|Aiman Dardari": 66,
  "FC Augsburg|Oliver Sorg": 66,
  "FC Augsburg|Noahkai Dominic Banks": 65,
  "FC Augsburg|Samuel Mbongu": 64,
  "FC Augsburg|Felix Meiser": 64,
  "FC Augsburg|Mahmut Kücüksahin": 63,
  "FC Augsburg|Daniel Klein": 63,

  // --- 1. FC Köln ---
  "1. FC Köln|Saïd El Mala": 73,
  "1. FC Köln|Marvin Schwäbe": 72,
  "1. FC Köln|Marius Bülter": 72,
  "1. FC Köln|Ragnar Ache": 72,
  "1. FC Köln|Florian Kainz": 72,
  "1. FC Köln|Jakub Kamiński": 72,
  "1. FC Köln|Timo Bernd Hübers": 71,
  "1. FC Köln|Eric Martel": 71,
  "1. FC Köln|Luca Jannis Kilian": 71,
  "1. FC Köln|Tom Krauß": 71,
  "1. FC Köln|Linton Maina": 71,
  "1. FC Köln|Gian-Luca Waldschmidt": 71,
  "1. FC Köln|Ísak Bergmann Jóhannesson": 71,
  "1. FC Köln|Denis Huseinbašić": 70,
  "1. FC Köln|Dominique Heintz": 70,
  "1. FC Köln|Jan Uwe Thielmann": 70,
  "1. FC Köln|Cenk Özkaçar": 70,
  "1. FC Köln|Jusuf Gazibegović": 70,
  "1. FC Köln|Kristoffer Lund Hansen": 70,
  "1. FC Köln|Alessio Daniel Castro-Montes": 70,
  "1. FC Köln|Sargis Adamyan": 69,
  "1. FC Köln|Ron-Robert Zieler": 69,
  "1. FC Köln|Sebastian Søraas Sebulonsen": 68,
  "1. FC Köln|Malek El Mala": 67,
  "1. FC Köln|Joël Pascal Schmied": 67,
  "1. FC Köln|Rav Berg": 64,
  "1. FC Köln|Neo Joshua Telle": 64,
  "1. FC Köln|Emin Kujovic": 64,
  "1. FC Köln|Fayssal Harchaoui": 64,
  "1. FC Köln|Matthias Köbbing": 63,

  // --- Hamburger SV ---
  "Hamburger SV|Yussuf Yurary Poulsen": 73,
  "Hamburger SV|Albert Lokonga": 73,
  "Hamburger SV|Fábio Vieira": 73,
  "Hamburger SV|Jean-Luc Dompé": 72,
  "Hamburger SV|Luka Vušković": 72,
  "Hamburger SV|Ransford Yeboah Königsdörffer": 72,
  "Hamburger SV|Rayan Philippe": 72,
  "Hamburger SV|Robert Nesta Glatzel": 72,
  "Hamburger SV|Daniel Heuer Fernandes": 71,
  "Hamburger SV|Jonas Meffert": 71,
  "Hamburger SV|Jordan Torunarigha": 71,
  "Hamburger SV|Miro Muheim": 71,
  "Hamburger SV|Nicolás Capaldo Taboas": 71,
  "Hamburger SV|Daniel Peretz": 71,
  "Hamburger SV|Immanuël-Johannes Pherai": 71,
  "Hamburger SV|Silvan Hefti": 70,
  "Hamburger SV|Warmed Omari": 70,
  "Hamburger SV|Bakery Jatta": 70,
  "Hamburger SV|Guilherme Ramos": 70,
  "Hamburger SV|Daniel Elfadli": 70,
  "Hamburger SV|Nicolai Remberg": 70,
  "Hamburger SV|Levin Mete Öztunali": 69,
  "Hamburger SV|Giorgi Gocholeishvili": 69,
  "Hamburger SV|Emir Sahiti": 68,
  "Hamburger SV|Noah Katterbach": 68,
  "Hamburger SV|William Mikelbrencis": 67,
  "Hamburger SV|Fabio Baldé": 65,
  "Hamburger SV|Alexander Røssing-Lelesiit": 64,
  "Hamburger SV|Bilal Yalcinkaya": 64,
  "Hamburger SV|Aboubaka Soumahoro": 64,
  "Hamburger SV|Fernando Dickes": 63,
  "Hamburger SV|Hannes Steffen Hermann": 63,

  // --- FC St. Pauli ---
  "FC St. Pauli|Nikola Vasilj": 71,
  "FC St. Pauli|Jackson Alexander Irvine": 71,
  "FC St. Pauli|Hauke Finn Wahl": 70,
  "FC St. Pauli|Danel Sinani": 70,
  "FC St. Pauli|Manolis Saliakas": 70,
  "FC St. Pauli|Oladapo Joshua Afolayan": 70,
  "FC St. Pauli|Eric Anders Smith": 70,
  "FC St. Pauli|Connor Isaac Metcalfe": 70,
  "FC St. Pauli|Joel Chima Fujita": 70,
  "FC St. Pauli|Karol Mets": 70,
  "FC St. Pauli|Mathias Pereira Lage": 70,
  "FC St. Pauli|James Hoban Sands": 70,
  "FC St. Pauli|Martijn Kaars": 70,
  "FC St. Pauli|Andreas Hountondji": 69,
  "FC St. Pauli|David Nemeth": 69,
  "FC St. Pauli|Louis Oppie": 69,
  "FC St. Pauli|Lars Ritzka": 69,
  "FC St. Pauli|Adam Dźwigała": 68,
  "FC St. Pauli|Ricky-Jade Jones": 68,
  "FC St. Pauli|Erik Melker Ahlstrand": 68,
  "FC St. Pauli|Arkadiusz Pyrka": 67,
  "FC St. Pauli|Abdoulie Ceesay": 66,
  "FC St. Pauli|Finley John Stevens": 65,
  "FC St. Pauli|Jannik Thomas Robatsch": 64,
  "FC St. Pauli|Marwin Schmitz": 64,
  "FC St. Pauli|Romeo Aigbekaen": 63,
  "FC St. Pauli|Ben Alexander Voll": 63,
  "FC St. Pauli|Simon Emil Spari": 63,

  // --- 1. FC Heidenheim 1846 ---
  "1. FC Heidenheim 1846|Diant Ramaj": 71,
  "1. FC Heidenheim 1846|Patrick Mainka": 70,
  "1. FC Heidenheim 1846|Jan Schöppner": 70,
  "1. FC Heidenheim 1846|Adrian Beck": 70,
  "1. FC Heidenheim 1846|Mathias Honsak": 70,
  "1. FC Heidenheim 1846|Niklas Bernd Dorsch": 70,
  "1. FC Heidenheim 1846|Budu Zivzivadze": 70,
  "1. FC Heidenheim 1846|Arijon Ibrahimović": 70,
  "1. FC Heidenheim 1846|Marvin Pieringer": 69,
  "1. FC Heidenheim 1846|Leart Shukri Paqarada": 69,
  "1. FC Heidenheim 1846|Mikkel Kaufmann Sørensen": 69,
  "1. FC Heidenheim 1846|Benedikt Steffen Gimber": 69,
  "1. FC Heidenheim 1846|Tim Siersleben": 69,
  "1. FC Heidenheim 1846|Omar Haktab Traorè": 68,
  "1. FC Heidenheim 1846|Marnon-Thomas Busch": 68,
  "1. FC Heidenheim 1846|Jonas Föhrenbach": 68,
  "1. FC Heidenheim 1846|Sirlord Calvin Conteh": 68,
  "1. FC Heidenheim 1846|Julian Niehues": 68,
  "1. FC Heidenheim 1846|Kevin Müller": 68,
  "1. FC Heidenheim 1846|Luca Kerber": 67,
  "1. FC Heidenheim 1846|Yannik Wagner": 67,
  "1. FC Heidenheim 1846|Thomas Leon Keller": 66,
  "1. FC Heidenheim 1846|Stefan Schimmer": 66,
  "1. FC Heidenheim 1846|Nick Rothweiler": 64,
  "1. FC Heidenheim 1846|Adam Kölle": 64,
  "1. FC Heidenheim 1846|Paul Tschernuth": 63,
  "1. FC Heidenheim 1846|Frank Feller": 63,
};
