/**
 * Overall editoriali della Ligue 1 2025/26 — **stima nostra e dichiarata**, stessa scala e
 * stesso metodo degli altri Big 5 (CLAUDE.md sez. 2.2).
 *
 * Scala: 88-92 fuoriclasse assoluti · 84-87 top da Champions · 80-83 titolari di alto
 * livello · 76-79 ossatura da Europa · 72-75 media classifica · 68-71 rosa · 62-67 fondo rosa.
 *
 * Forma del campionato (richiesta esplicita dell'utente): il PSG, vincitore di due Champions
 * consecutive, è **il club più forte del database** — la sua fascia alta sta sopra a quella
 * di City, Real e Bayern. Sotto di lui però la Ligue 1 è il torneo meno profondo dei Big 5:
 * la distanza tra la prima e la seconda è la più ampia d'Europa, ed è voluta.
 *
 * Nota sui nomi: il foglio usa l'anagrafica legale — "Masour Ousmane Dembélé" è Ousmane
 * Dembélé, "Vítor Machado Ferreira" è Vitinha, "Marcos Aoás Corrêa" è Marquinhos.
 */
export const EDITORIAL_LIGUE1: Record<string, number> = {
  // --- Paris Saint-Germain ---
  "Paris Saint-Germain|Masour Ousmane Dembélé": 92,
  "Paris Saint-Germain|Achraf Hakimi Mouh": 89,
  "Paris Saint-Germain|Vítor Machado Ferreira": 90,
  "Paris Saint-Germain|Nuno Mendes": 88,
  "Paris Saint-Germain|Khvicha Kvaratskhelia": 89,
  "Paris Saint-Germain|João Neves": 88,
  "Paris Saint-Germain|Désiré Doué": 87,
  "Paris Saint-Germain|Fabián Ruiz Peña": 86,
  "Paris Saint-Germain|Marcos Aoás Corrêa": 85,
  "Paris Saint-Germain|Bradley Barcola": 86,
  "Paris Saint-Germain|Warren Zaïre-Emery": 84,
  "Paris Saint-Germain|Gonçalo Matias Ramos": 84,
  "Paris Saint-Germain|Illia Zabarnyi": 84,
  "Paris Saint-Germain|Lucas Chevalier": 85,
  "Paris Saint-Germain|Kang-in Lee": 82,
  "Paris Saint-Germain|Lucas Lopes Beraldo": 80,
  "Paris Saint-Germain|Senny Mayulu": 78,
  "Paris Saint-Germain|Matvey Safonov": 75,
  "Paris Saint-Germain|Ibrahim Mbaye": 73,
  "Paris Saint-Germain|Willian Tenorio": 68,
  "Paris Saint-Germain|Noham Kamara": 66,
  "Paris Saint-Germain|Lucas Pi": 65,
  "Paris Saint-Germain|Renato Bellucci Marin": 64,

  // --- Olympique de Marseille ---
  "Olympique de Marseille|Pierre-Emile Kordt Højbjerg": 81,
  "Olympique de Marseille|Mason Greenwood": 81,
  "Olympique de Marseille|Amine Ferid Gouiri": 80,
  "Olympique de Marseille|Igor Paixão": 80,
  "Olympique de Marseille|Benjamin Pavard": 79,
  "Olympique de Marseille|Nayef Aguerd": 78,
  "Olympique de Marseille|Pierre-Emerick Aubameyang": 78,
  "Olympique de Marseille|Geoffrey Edwin Kondogbia": 77,
  "Olympique de Marseille|Matthew Sean O'Riley": 77,
  "Olympique de Marseille|Gerónimo Rulli": 77,
  "Olympique de Marseille|Timothy Tarpeh Weah": 76,
  "Olympique de Marseille|Arthur Denis Vermeeren": 76,
  "Olympique de Marseille|Facundo Axel Medina": 76,
  "Olympique de Marseille|Hamed Junior Traoré": 75,
  "Olympique de Marseille|Conrad Jaden Egan-Riley": 74,
  "Olympique de Marseille|Neal Maupay": 74,
  "Olympique de Marseille|Emerson Santos": 74,
  "Olympique de Marseille|Bilal Nadir": 72,
  "Olympique de Marseille|Robinio Vaz": 72,
  "Olympique de Marseille|Rubén Blanco Veiga": 71,
  "Olympique de Marseille|Michael Bermúdez": 69,
  "Olympique de Marseille|Darryl Bakola": 69,
  "Olympique de Marseille|François Régis Mughe": 69,
  "Olympique de Marseille|Keyliane Hikram Abdallah": 68,
  "Olympique de Marseille|Jeffrey de Lange": 68,
  "Olympique de Marseille|Leonardo Rossa": 66,
  "Olympique de Marseille|Adilson Gomes": 65,
  "Olympique de Marseille|Ulisses Lopes": 65,
  "Olympique de Marseille|Yanis Sellami": 65,
  "Olympique de Marseille|Pol Kosok": 64,
  "Olympique de Marseille|Jelle Van Neck": 63,
  "Olympique de Marseille|Théo Vermot": 63,

  // --- AS Monaco ---
  "AS Monaco|Maghnes Akliouche": 79,
  "AS Monaco|Folarin Balogun": 77,
  "AS Monaco|Paul Labile Pogba": 77,
  "AS Monaco|Eric Dier": 76,
  "AS Monaco|Jan Thilo Kehrer": 76,
  "AS Monaco|Takumi Minamino": 76,
  "AS Monaco|Lamine Camara": 76,
  "AS Monaco|Aleksandr Golovin": 76,
  "AS Monaco|Mika Miles Biereth": 76,
  "AS Monaco|Lukáš Hrádecký": 76,
  "AS Monaco|Vanderson Campos": 76,
  "AS Monaco|Anssumane Fati Vieira": 75,
  "AS Monaco|Krépin Diatta": 75,
  "AS Monaco|Jordan Teze": 75,
  "AS Monaco|Philipp François Köhn": 73,
  "AS Monaco|Christian Mawissa Elebi": 73,
  "AS Monaco|George Osrzehmen Ilenikhena": 73,
  "AS Monaco|Caio Silva": 72,
  "AS Monaco|Kassoum Ouattara": 71,
  "AS Monaco|Stanis Idumbo Muzambo": 71,
  "AS Monaco|Lucas Michal": 68,
  "AS Monaco|Denis Lado": 67,
  "AS Monaco|Mohamed Karim": 66,
  "AS Monaco|Aladji Bamba": 66,
  "AS Monaco|Mamadou Coulibaly": 66,
  "AS Monaco|Paris Josua Brunner": 64,
  "AS Monaco|Jules Stawiecki": 63,
  "AS Monaco|Yann François Lienard": 63,

  // --- Lille OSC ---
  "Lille OSC|Olivier Jonathan Giroud": 76,
  "Lille OSC|Benjamin André": 75,
  "Lille OSC|Chancel Mbemba Mangulu": 75,
  "Lille OSC|Alexsandro Ribeiro": 75,
  "Lille OSC|Osame Sahraoui": 75,
  "Lille OSC|Nabil Bentaleb": 74,
  "Lille OSC|Thomas Meunier": 74,
  "Lille OSC|Aïssa Mandi": 74,
  "Lille OSC|Hákon Arnar Haraldsson": 74,
  "Lille OSC|Berke Özer": 74,
  "Lille OSC|Ngal'ayel Mukau": 74,
  "Lille OSC|Hamza Igamane": 74,
  "Lille OSC|Félix Correia": 73,
  "Lille OSC|Matias Fernandez-Pardo": 73,
  "Lille OSC|Calvin Ronald Verdonk": 73,
  "Lille OSC|Ayyoub Bouaddi": 73,
  "Lille OSC|Romain Perraud": 72,
  "Lille OSC|André Gomes": 72,
  "Lille OSC|Nathan Ngoy": 72,
  "Lille OSC|Ethan Mbappé Lottin": 72,
  "Lille OSC|Marius Sivertsen Broholm": 71,
  "Lille OSC|Arnaud Bodart": 71,
  "Lille OSC|Tiago Carvalho Santos": 70,
  "Lille OSC|Trévis Dago": 69,
  "Lille OSC|Rafael Fernandes": 67,
  "Lille OSC|Ousmane Touré": 66,
  "Lille OSC|Marc-Aurèle Caillard": 66,
  "Lille OSC|Ugo Raghouber": 65,
  "Lille OSC|Maxima Goffi": 64,

  // --- Olympique Lyonnais ---
  "Olympique Lyonnais|Corentin Tolisso": 76,
  "Olympique Lyonnais|Malick Martin Fofana": 76,
  "Olympique Lyonnais|Nicolás Alejandro Tagliafico": 75,
  "Olympique Lyonnais|Moussa Niakhaté": 75,
  "Olympique Lyonnais|Pavel Šulc": 75,
  "Olympique Lyonnais|Orel Johnson Mangala": 74,
  "Olympique Lyonnais|Ruben Caine Kluivert": 74,
  "Olympique Lyonnais|Dominik Greif": 74,
  "Olympique Lyonnais|Tyler Scott Morton": 74,
  "Olympique Lyonnais|Ainsley Cory Maitland-Niles": 73,
  "Olympique Lyonnais|Ernest Nuamah Appiah": 73,
  "Olympique Lyonnais|Abner Santos": 73,
  "Olympique Lyonnais|Rachid Ghezzal": 72,
  "Olympique Lyonnais|Adam Karabec": 72,
  "Olympique Lyonnais|Afonso Bastardo Moreira": 71,
  "Olympique Lyonnais|Khalis Merah": 71,
  "Olympique Lyonnais|Enzo Molebe": 71,
  "Olympique Lyonnais|Rémy Descamps": 70,
  "Olympique Lyonnais|Téo Barišić": 69,
  "Olympique Lyonnais|Martín Costa": 68,
  "Olympique Lyonnais|Alejandro Rodríguez": 67,
  "Olympique Lyonnais|Achraf Laâziri": 67,
  "Olympique Lyonnais|Clinton Lourenço": 66,
  "Olympique Lyonnais|Mathys De Carvalho": 65,
  "Olympique Lyonnais|Francis Tessmann": 64,
  "Olympique Lyonnais|Lassine Diarra": 63,

  // --- OGC Nice ---
  "OGC Nice|Terem Igobor Moffi": 76,
  "OGC Nice|Jonathan Clauss": 75,
  "OGC Nice|Dante Santos": 74,
  "OGC Nice|Jérémie Boga": 74,
  "OGC Nice|Sofiane Diop": 74,
  "OGC Nice|Melvin Bard": 73,
  "OGC Nice|Morgan Sanson": 73,
  "OGC Nice|Moïse Bombito Lumpungu": 73,
  "OGC Nice|Salis Abdul Samed": 73,
  "OGC Nice|Yehvann Diouf": 73,
  "OGC Nice|Hicham Boudaoui": 72,
  "OGC Nice|Mohamed-Ali Cho": 72,
  "OGC Nice|Tanguy Ndombélé Alvaro": 72,
  "OGC Nice|Charles Vanhoutte": 72,
  "OGC Nice|Ali Abdi": 72,
  "OGC Nice|Mohamed Abdelmonem": 72,
  "OGC Nice|Abdulai Juma Bah": 72,
  "OGC Nice|Youssouf Ndayishimiye": 71,
  "OGC Nice|Isak Jansson": 71,
  "OGC Nice|Antoine Mendy": 70,
  "OGC Nice|Tiago Gouveia": 70,
  "OGC Nice|Maxime Dupé": 69,
  "OGC Nice|Kojo Peprah Oppong": 66,
  "OGC Nice|Tom Alexis Louchet": 66,
  "OGC Nice|Bernard Nguene": 64,
  "OGC Nice|Kevin Benjamin": 64,
  "OGC Nice|Gabin Bernardeau": 64,
  "OGC Nice|Bartosz Żelazowski": 63,

  // --- RC Lens ---
  "RC Lens|Florian Thauvin": 76,
  "RC Lens|Odsonne Édouard": 73,
  "RC Lens|Florian Sotoca": 73,
  "RC Lens|Jonathan Gradit": 72,
  "RC Lens|Adrien Thomasson": 72,
  "RC Lens|Matthieu Udol": 72,
  "RC Lens|Malang Sarr": 72,
  "RC Lens|Abdallah Dipo Sima": 72,
  "RC Lens|Samson Baidoo": 72,
  "RC Lens|Mamadou Sangaré": 72,
  "RC Lens|Ruben Aguilar": 71,
  "RC Lens|Régis Gurtner": 71,
  "RC Lens|Robin Risser Birckel": 71,
  "RC Lens|Wesley Saïd": 71,
  "RC Lens|Morgan Guilavogui": 71,
  "RC Lens|Alpha Diallo": 71,
  "RC Lens|Anthony Bermont": 70,
  "RC Lens|Deiver Mena": 70,
  "RC Lens|Jhoanner Quintero": 70,
  "RC Lens|Fodé Sanassy Sylla": 69,
  "RC Lens|Rayan Fofana": 69,
  "RC Lens|Pierre-Ismaëlo Ganiou": 68,
  "RC Lens|Kyllian Anderson Antonio": 67,
  "RC Lens|Saud Hamid": 66,
  "RC Lens|Andrija Bulatovic": 65,
  "RC Lens|Nidal Čelik": 64,
  "RC Lens|Hamzat-Basit Ojediran": 64,
  "RC Lens|Ilan Jourdren": 63,

  // --- RC Strasbourg Alsace ---
  "RC Strasbourg Alsace|Emmanuel Esseh Emegha": 75,
  "RC Strasbourg Alsace|Joaquín Panichelli": 74,
  "RC Strasbourg Alsace|Valentín Barco": 73,
  "RC Strasbourg Alsace|Diego Moreira": 73,
  "RC Strasbourg Alsace|Mamadou Sarr": 73,
  "RC Strasbourg Alsace|Guéla Doué": 73,
  "RC Strasbourg Alsace|Benjamin James Chilwell": 73,
  "RC Strasbourg Alsace|Mike Louis Penders": 72,
  "RC Strasbourg Alsace|Ismaël Landry Doukouré": 72,
  "RC Strasbourg Alsace|Félix Lemaréchal": 72,
  "RC Strasbourg Alsace|Algot Sebastian Nanasi": 72,
  "RC Strasbourg Alsace|Abakar Loubadhe Sylla": 72,
  "RC Strasbourg Alsace|Andrew Abiola Omobamidele": 71,
  "RC Strasbourg Alsace|Maximillian Oyedele": 71,
  "RC Strasbourg Alsace|Samuel Amo-Ameyaw": 71,
  "RC Strasbourg Alsace|Soumaïla Coulibaly": 70,
  "RC Strasbourg Alsace|Mathis Amougou": 70,
  "RC Strasbourg Alsace|Saïdou Sow": 70,
  "RC Strasbourg Alsace|Eduard Sobol": 69,
  "RC Strasbourg Alsace|Julio Espínola": 69,
  "RC Strasbourg Alsace|Karl-Johan Anton Johnsson": 69,
  "RC Strasbourg Alsace|Rafael Luís": 68,
  "RC Strasbourg Alsace|Abdoul Guemissongui Ouattara": 68,
  "RC Strasbourg Alsace|Becket Fabrice-Martial Godo": 67,
  "RC Strasbourg Alsace|Lucas Høgsberg": 66,
  "RC Strasbourg Alsace|Ray Andrade": 65,
  "RC Strasbourg Alsace|Stefan Bajić": 65,
  "RC Strasbourg Alsace|Samir El Mourabet": 64,
  "RC Strasbourg Alsace|Rabby Nzingoula": 64,

  // --- Stade Rennais FC ---
  "Stade Rennais FC|Brice Lauriche Samba": 76,
  "Stade Rennais FC|Valentin Rongier": 74,
  "Stade Rennais FC|Breel Donald Embolo": 74,
  "Stade Rennais FC|Seko Mohamed Fofana": 74,
  "Stade Rennais FC|Glen Adjei Kamara": 73,
  "Stade Rennais FC|Ludovic Blas": 73,
  "Stade Rennais FC|Estéban Lepaul": 73,
  "Stade Rennais FC|Quentin Merlin": 72,
  "Stade Rennais FC|Przemysław Frankowski": 72,
  "Stade Rennais FC|Anthony Rouault": 72,
  "Stade Rennais FC|Mousa Tamari": 72,
  "Stade Rennais FC|Lilian Brassier": 71,
  "Stade Rennais FC|Hans Hateboer": 71,
  "Stade Rennais FC|Alidu Seidu": 71,
  "Stade Rennais FC|Jérémy Jacquet": 71,
  "Stade Rennais FC|Abdelhamid Ait Boudlal": 70,
  "Stade Rennais FC|Djaoui Cissé": 70,
  "Stade Rennais FC|Mahdi Camara": 70,
  "Stade Rennais FC|Mohamed Kader Meïté": 69,
  "Stade Rennais FC|Gauthier Gallon": 68,
  "Stade Rennais FC|Mahamadou Aboubakar Nagida": 64,

  // --- Toulouse FC ---
  "Toulouse FC|Guillaume Restes": 73,
  "Toulouse FC|Charlie Richard Cresswell": 72,
  "Toulouse FC|Mark Alexander McKenzie": 71,
  "Toulouse FC|Frank Mario Magri": 71,
  "Toulouse FC|Yann-Alexandre Gboho Gnantin": 71,
  "Toulouse FC|Aron Leonard Dønnum": 71,
  "Toulouse FC|Emersonn Silva": 71,
  "Toulouse FC|Djibril Sidibé": 70,
  "Toulouse FC|Rasmus Schmidt Nicolaisen": 70,
  "Toulouse FC|Warren Kamanzi": 70,
  "Toulouse FC|Cristian Yépes": 70,
  "Toulouse FC|Niklas Uwe Schmidt": 70,
  "Toulouse FC|Mario Sauer": 70,
  "Toulouse FC|Abu Francis": 70,
  "Toulouse FC|Santiago Hidalgo Massa": 69,
  "Toulouse FC|Noah Edjouma": 69,
  "Toulouse FC|Alexis Vossah": 68,
  "Toulouse FC|Dayann Methalie": 68,
  "Toulouse FC|Ilyas Azizi": 68,
  "Toulouse FC|Rafik Messali": 68,
  "Toulouse FC|Darris Zema": 67,
  "Toulouse FC|Julián Vignolo": 67,
  "Toulouse FC|Noah Lahmadi": 66,
  "Toulouse FC|Christian Kjetil Haug": 66,
  "Toulouse FC|Enzo Faty": 65,
  "Toulouse FC|Gaëtan Bakhouche": 65,
  "Toulouse FC|Nicolas Wasbauer": 65,
  "Toulouse FC|Frédéric Efuele Ngoyala": 64,
  "Toulouse FC|Seny Koumbassa": 64,
  "Toulouse FC|Alejandro Domínguez Romero": 64,
  "Toulouse FC|Naïme Saïd Mchindra": 63,

  // --- Stade Brestois 29 ---
  "Stade Brestois 29|Ludovic Ajorque": 72,
  "Stade Brestois 29|Romain Del Castillo": 71,
  "Stade Brestois 29|Lucas Tousart": 71,
  "Stade Brestois 29|Brendan Chardonnet": 71,
  "Stade Brestois 29|Radosław Majecki": 71,
  "Stade Brestois 29|Bradley Locko Banzouzi": 71,
  "Stade Brestois 29|Kamory Doumbia": 70,
  "Stade Brestois 29|Hugo Magnetti": 70,
  "Stade Brestois 29|Joris Chotard": 70,
  "Stade Brestois 29|Kenny Lala": 70,
  "Stade Brestois 29|Mama Samba Baldé": 70,
  "Stade Brestois 29|Éric Ebimbe": 70,
  "Stade Brestois 29|Rémy Labeau Lascary": 70,
  "Stade Brestois 29|Julien Le Cardinal": 69,
  "Stade Brestois 29|Grégoire Coudert": 69,
  "Stade Brestois 29|Daouda Guindo": 68,
  "Stade Brestois 29|Hamidou Makalou": 68,
  "Stade Brestois 29|Pathé Mboup": 67,
  "Stade Brestois 29|Michel Junior Diaz": 66,
  "Stade Brestois 29|Serigne Saliou Diop": 66,
  "Stade Brestois 29|Raphaël Le Guen": 65,
  "Stade Brestois 29|Tolikpaley Zogbé": 65,
  "Stade Brestois 29|Justin Bourgault": 64,
  "Stade Brestois 29|Noah Jauny": 63,

  // --- Paris FC ---
  "Paris FC|Kevin Christian Trapp": 72,
  "Paris FC|Pierre Lees-Melou": 71,
  "Paris FC|Hamari Traoré": 71,
  "Paris FC|Nanitamo Jonathan Ikoné": 71,
  "Paris FC|Moses Daddy-Ajala Simon": 71,
  "Paris FC|Ilan Kais Kebbal": 71,
  "Paris FC|Timothée Christian Kolodziejczak": 70,
  "Paris FC|Willem Geubbels": 70,
  "Paris FC|Jean-Philippe Krasso": 70,
  "Paris FC|Otávio Silva": 70,
  "Paris FC|Mathieu Cafaro": 70,
  "Paris FC|Thibault De Smet": 69,
  "Paris FC|Samir Sophian Chergui": 69,
  "Paris FC|Vincent Marchetti": 69,
  "Paris FC|Adama Mohamed Camara": 68,
  "Paris FC|Mamadou Moustapha Mbow": 68,
  "Paris FC|Alimami Gory": 68,
  "Paris FC|Sofiane Alakouch": 68,
  "Paris FC|Obed Nkambadio": 68,
  "Paris FC|Nouha Dicko": 67,
  "Paris FC|Rémy Riou": 66,
  "Paris FC|Pierre-Yves Hamel": 66,
  "Paris FC|Mamadou Lamine Gueye": 66,
  "Paris FC|Andy Pembélé": 65,
  "Paris FC|Lohann Doucet": 65,
  "Paris FC|Nhoa Ryan Sangui": 64,
  "Paris FC|Maxime Baila Lopez": 64,
  "Paris FC|Julien Baila": 64,
  "Paris FC|Tuomas Ollila": 63,

  // --- FC Nantes ---
  "FC Nantes|Matthis Abline": 72,
  "FC Nantes|Anthony Lopes": 71,
  "FC Nantes|Francis Coquelin": 70,
  "FC Nantes|Youssef El Arabi": 70,
  "FC Nantes|Johann Lepenant": 70,
  "FC Nantes|Nicolas Cozza": 70,
  "FC Nantes|Chidozie Collins Awaziem": 70,
  "FC Nantes|Kelvin Amian Adou": 70,
  "FC Nantes|Hyeon-seok Hong": 70,
  "FC Nantes|Hyeok-kyu Kwon": 69,
  "FC Nantes|Junior Mwanga": 69,
  "FC Nantes|Fabien Centonze": 69,
  "FC Nantes|Tylel Tati": 69,
  "FC Nantes|Uroš Radaković": 69,
  "FC Nantes|Louis Leroux": 68,
  "FC Nantes|Mayckel Lahdo": 68,
  "FC Nantes|Bahereba Guirassy": 68,
  "FC Nantes|Patrik Carlgren": 67,
  "FC Nantes|Sékou Doucouré": 67,
  "FC Nantes|Adel Mahamoud": 66,
  "FC Nantes|Yassine Benhattab": 66,
  "FC Nantes|Amady Camara": 65,
  "FC Nantes|Mostafa Abdalla": 65,
  "FC Nantes|Dehmaine Tabibou Assoumani": 64,
  "FC Nantes|Bahmed Deuff": 64,
  "FC Nantes|Alexis Mirbach": 63,

  // --- Angers SCO ---
  "Angers SCO|Himad Abdelli": 71,
  "Angers SCO|Kouakou Hervé Koffi": 70,
  "Angers SCO|Haris Belkebla": 69,
  "Angers SCO|Jim Allevinah": 69,
  "Angers SCO|Abdoulaye Bamba": 68,
  "Angers SCO|Pierrick Capelle": 68,
  "Angers SCO|Jacques Ekomié": 68,
  "Angers SCO|Jordan Lefort": 68,
  "Angers SCO|Ousmane Camara": 68,
  "Angers SCO|Carlens Arcus": 68,
  "Angers SCO|Florent Hanin": 67,
  "Angers SCO|Yassin Belkhdim": 67,
  "Angers SCO|Amine Moussaoui": 67,
  "Angers SCO|Marius Courcoul": 67,
  "Angers SCO|Emmanuel Bayiha": 67,
  "Angers SCO|Sidiki Chérif": 67,
  "Angers SCO|Louis Mouton": 67,
  "Angers SCO|Justin-Noël Ngongo": 66,
  "Angers SCO|Ilann Garin": 66,
  "Angers SCO|Dan Sinaté": 66,
  "Angers SCO|Lionel Ngangué": 65,
  "Angers SCO|Prosper Peter": 65,
  "Angers SCO|Lilian Raolisoa": 65,
  "Angers SCO|Marius Louër": 64,
  "Angers SCO|Jibril El Baraka": 64,
  "Angers SCO|Guédé Noah Nadje": 64,
  "Angers SCO|Lanroy Machine": 63,
  "Angers SCO|Melvin Zinga": 63,
  "Angers SCO|Oumar Kalifa Pona": 63,

  // --- AJ Auxerre ---
  "AJ Auxerre|Lassine Sinayoko": 70,
  "AJ Auxerre|Donovan René Léon": 69,
  "AJ Auxerre|Sinaly Diomandé": 69,
  "AJ Auxerre|Elisha Owusu": 69,
  "AJ Auxerre|Sékou Mara": 69,
  "AJ Auxerre|Gideon Mensah": 68,
  "AJ Auxerre|Oussama El Azzouzi": 68,
  "AJ Auxerre|Marvin Senaya": 68,
  "AJ Auxerre|Assane Hadji": 68,
  "AJ Auxerre|Josué Casimir": 68,
  "AJ Auxerre|Fredrik Oppegård": 68,
  "AJ Auxerre|Clément Akpa": 67,
  "AJ Auxerre|Lasso Coulibaly": 67,
  "AJ Auxerre|Kévin Danois": 67,
  "AJ Auxerre|Rayan Mandengue": 66,
  "AJ Auxerre|Daniel Loader": 66,
  "AJ Auxerre|Lamine Sy": 66,
  "AJ Auxerre|Osman Ibrahim Abrahim": 66,
  "AJ Auxerre|Telli Siwe": 65,
  "AJ Auxerre|Tidiane Devernois": 65,
  "AJ Auxerre|Ryan Rodin": 65,
  "AJ Auxerre|Francisco Carvallo": 65,
  "AJ Auxerre|Elikya Legros": 64,
  "AJ Auxerre|Nathan Buayi-Kiala": 64,
  "AJ Auxerre|Rudy Nzingoula Matondo": 64,
  "AJ Auxerre|Théo Percin": 64,
  "AJ Auxerre|Louis Mezerette": 63,
  "AJ Auxerre|Tom Negrel": 63,

  // --- FC Metz ---
  "FC Metz|Habibou Mouhamadou Diallo": 70,
  "FC Metz|Gauthier Hein": 69,
  "FC Metz|Boubacar Traoré": 68,
  "FC Metz|Maxime Jean-Yves Colin": 68,
  "FC Metz|Benjamin Stambouli": 68,
  "FC Metz|Fodé Ballo-Touré": 68,
  "FC Metz|Jean-Philippe Gbamin": 68,
  "FC Metz|Jessy Deminguet": 68,
  "FC Metz|Joel Joshoghene Asoro": 68,
  "FC Metz|Cheikh Tidiane Sabaly": 67,
  "FC Metz|Koffi Franck Kouao": 67,
  "FC Metz|Sadibou Sané": 67,
  "FC Metz|Terry Yegbe": 67,
  "FC Metz|Ibou Sané": 67,
  "FC Metz|Georgiy Tsitaishvili": 67,
  "FC Metz|Pape Mamadou Sy": 67,
  "FC Metz|Ismaël Guerti": 66,
  "FC Metz|Alpha Amadou Touré": 66,
  "FC Metz|Morgan Bokele Mputu": 65,
  "FC Metz|Giorgi Abuashvili": 65,
  "FC Metz|Malick Mbaye": 65,
  "FC Metz|Jonathan Frost Fischer": 65,
  "FC Metz|Yannis Lawson": 64,
  "FC Metz|Cléo Mélières": 64,
  "FC Metz|Urie-Michel Mboula": 64,
  "FC Metz|Lima Joseph Mangondo": 63,

  // --- FC Lorient ---
  "FC Lorient|Montassar Omar Talbi": 69,
  "FC Lorient|Jean-Victor Makengo": 69,
  "FC Lorient|Laurent Abergel": 68,
  "FC Lorient|Théo Le Bris": 68,
  "FC Lorient|Sambou Soumano": 68,
  "FC Lorient|Bingourou Kamara": 68,
  "FC Lorient|Igor Almeida": 67,
  "FC Lorient|Souleymane Isaak Touré": 67,
  "FC Lorient|Bamo Abdoul Meïté": 67,
  "FC Lorient|Panos Katseris": 67,
  "FC Lorient|Mohamed Bamba": 67,
  "FC Lorient|Nathaniel Adjei": 67,
  "FC Lorient|Joel Mugisha Mvuka": 67,
  "FC Lorient|Bandiougou Fadiga": 66,
  "FC Lorient|Arsène Kouassi": 66,
  "FC Lorient|Abdoulaye Faye": 66,
  "FC Lorient|Benjamin Leroy": 66,
  "FC Lorient|Cheikh Dieng": 66,
  "FC Lorient|Oluwatosin Aiyegun": 65,
  "FC Lorient|Trevan Sanusi": 65,
  "FC Lorient|Pablo Pagis": 65,
  "FC Lorient|Arthur Avom Ebong": 64,
  "FC Lorient|Darlin Ngameni": 64,
  "FC Lorient|Dermane Karim": 64,
  "FC Lorient|Noah Cadiou": 63,
  "FC Lorient|Yvon Nganoma": 63,

  // --- Le Havre AC ---
  "Le Havre AC|Abdoulaye Touré": 69,
  "Le Havre AC|Arouna Sangante": 69,
  "Le Havre AC|Gautier Lloris": 68,
  "Le Havre AC|Mbwana Ally Samatta": 68,
  "Le Havre AC|Mory Diaw": 68,
  "Le Havre AC|Ayumu Seko": 68,
  "Le Havre AC|Loïc Négo": 68,
  "Le Havre AC|Yassine Kechta": 68,
  "Le Havre AC|Rassoul Ndiaye": 67,
  "Le Havre AC|Issa Soumaré": 67,
  "Le Havre AC|Thomas Delaine": 67,
  "Le Havre AC|Etienne Kinkoué": 67,
  "Le Havre AC|Reda Jousef Khadra": 67,
  "Le Havre AC|Younes Namli": 67,
  "Le Havre AC|Lionel M'Pasi N'Zau": 67,
  "Le Havre AC|Fodé Doucouré": 66,
  "Le Havre AC|Godson Kyeremeh": 66,
  "Le Havre AC|Felix Khonde Mambimbi": 66,
  "Le Havre AC|Andy Elysée Logbo": 65,
  "Le Havre AC|Damián Huenuqueo": 65,
  "Le Havre AC|Simon Ebonog": 64,
  "Le Havre AC|Guy-Noël Prince Zohouri": 64,
  "Le Havre AC|Daren Nbenbege Mosengo": 64,
  "Le Havre AC|Yanis Zouaoui": 64,
  "Le Havre AC|Paul Argney": 63,
};
