/**
 * Overall di base della Serie A 2025/26 — **stima editoriale nostra e dichiarata**
 * (CLAUDE.md sez. 2.2, "fallback editoriale dichiarato").
 *
 * Cosa sono: la nostra valutazione dello standing di ogni giocatore, scritta da zero.
 * Non sono la riproduzione dei valori di nessun altro database: sono un giudizio, come
 * quello di qualunque redazione sportiva, e come tale va dichiarato in app e non spacciato
 * per misura oggettiva.
 *
 * Scala usata (dichiarata perché sia ripetibile e criticabile):
 * - **88-92** fuoriclasse assoluti, riferimenti mondiali del ruolo
 * - **84-87** top di categoria, titolari fissi da Champions
 * - **80-83** titolari di alto livello nelle prime della classe
 * - **76-79** titolari solidi, ossatura delle squadre da Europa
 * - **72-75** titolari di media classifica / rotazioni nelle grandi
 * - **68-71** giocatori di rosa, giovani in crescita
 * - **62-67** terzi portieri, fondo rosa, ragazzi della primavera
 *
 * Chiave `Club|Nome` perché diversi cognomi si ripetono tra club (Ibrahim Sulemana,
 * Giovanni Fabbian, Emil Holm, Pietro Terracciano...).
 *
 * Questi valori sono la **base di partenza**: `applySeasonAdjustment` li corregge poi con
 * il rendimento reale della stagione (±8) man mano che minutaggio e statistiche arrivano.
 */
export const EDITORIAL_OVERALLS: Record<string, number> = {
  // --- Atalanta ---
  "Atalanta|Éderson": 84,
  "Atalanta|Marco Carnesecchi": 82,
  "Atalanta|Charles De Ketelaere": 82,
  "Atalanta|Gianluca Scamacca": 80,
  "Atalanta|Isak Hien": 80,
  "Atalanta|Nikola Krstović": 79,
  "Atalanta|Giorgio Scalvini": 79,
  "Atalanta|Marten de Roon": 79,
  "Atalanta|Raoul Bellanova": 79,
  "Atalanta|Giacomo Raspadori": 78,
  "Atalanta|Berat Djimsiti": 78,
  "Atalanta|Mario Pašalić": 77,
  "Atalanta|Lazar Samardžić": 77,
  "Atalanta|Odilon Kossounou": 77,
  "Atalanta|Yunus Musah": 75,
  "Atalanta|Sead Kolašinac": 75,
  "Atalanta|Davide Zappacosta": 75,
  "Atalanta|Nicola Zalewski": 75,
  "Atalanta|Kamaldeen Sulemana": 74,
  "Atalanta|Marco Sportiello": 72,
  "Atalanta|Mitchel Bakker": 72,
  "Atalanta|Honest Ahanor": 66,
  "Atalanta|Francesco Rossi": 64,
  "Atalanta|Lorenzo Bernasconi": 63,

  // --- Bologna ---
  "Bologna|Riccardo Orsolini": 82,
  "Bologna|Lewis Ferguson": 80,
  "Bologna|Łukasz Skorupski": 78,
  "Bologna|Jhon Lucumí": 78,
  "Bologna|Remo Freuler": 78,
  "Bologna|Santiago Castro": 78,
  "Bologna|Jens Odgaard": 77,
  "Bologna|Ciro Immobile": 76,
  "Bologna|Giovanni Fabbian": 76,
  "Bologna|Nikola Moro": 75,
  "Bologna|Nicolò Casale": 74,
  "Bologna|Juan Miranda": 74,
  "Bologna|Thijs Dallinga": 74,
  "Bologna|Emil Holm": 73,
  "Bologna|Nadir Zortea": 73,
  "Bologna|Benjamín Domínguez": 73,
  "Bologna|Tommaso Pobega": 73,
  "Bologna|Federico Bernardeschi": 72,
  "Bologna|Nicolò Cambiaghi": 72,
  "Bologna|Lorenzo De Silvestri": 72,
  "Bologna|Charalampos Lykogiannis": 72,
  "Bologna|Martin Vitík": 70,
  "Bologna|Jonathan Rowe": 70,
  "Bologna|Torbjørn Heggem": 69,
  "Bologna|Federico Ravaglia": 68,
  "Bologna|Ibrahim Sulemana": 66,
  "Bologna|Massimo Pessina": 62,

  // --- Cagliari ---
  "Cagliari|Elia Caprile": 77,
  "Cagliari|Andrea Belotti": 74,
  "Cagliari|Yerry Mina": 74,
  "Cagliari|Marco Palestra": 74,
  "Cagliari|Gianluca Gaetano": 74,
  "Cagliari|Luca Mazzitelli": 73,
  "Cagliari|Sebastiano Esposito": 73,
  "Cagliari|Michael Folorunsho": 73,
  "Cagliari|Alessandro Deiola": 72,
  "Cagliari|Alberto Dossena": 72,
  "Cagliari|Gabriele Zappa": 72,
  "Cagliari|Michel Adopo": 71,
  "Cagliari|Gennaro Borrelli": 70,
  "Cagliari|Leonardo Pavoletti": 70,
  "Cagliari|Semih Kılıçsoy": 70,
  "Cagliari|Adam Obert": 70,
  "Cagliari|Juan Rodríguez": 68,
  "Cagliari|Alen Sherri": 68,
  "Cagliari|Mattia Felici": 68,
  "Cagliari|Ibrahim Sulemana": 66,
  "Cagliari|Zé Pedro": 66,
  "Cagliari|Giuseppe Ciocci": 63,
  "Cagliari|Agustin Albarracin": 63,
  "Cagliari|Othniël Raterink": 63,
  "Cagliari|Riyad Idrissi": 63,
  "Cagliari|Yael Trepy": 62,
  "Cagliari|Joseph Liteta": 62,

  // --- Como ---
  "Como|Nico Paz": 82,
  "Como|Álvaro Morata": 78,
  "Como|Anastasios Douvikas": 76,
  "Como|Maxence Caqueret": 76,
  "Como|Martin Baturina": 76,
  "Como|Nicolas Kühn": 76,
  "Como|Diego Carlos": 76,
  "Como|Jean Butez": 75,
  "Como|Assane Diao": 74,
  "Como|Sergi Roberto": 74,
  "Como|Marc-Oliver Kempf": 74,
  "Como|Lucas Da Cunha": 73,
  "Como|Máximo Perrone": 73,
  "Como|Edoardo Goldaniga": 73,
  "Como|Mërgim Vojvoda": 73,
  "Como|Jesús Rodríguez": 72,
  "Como|Álex Valle": 72,
  "Como|Alberto Moreno": 72,
  "Como|Ignace Van Der Brempt": 72,
  "Como|Jayden Addai": 68,
  "Como|Jacobo Ramón": 67,
  "Como|Ivan Smolčić": 67,
  "Como|Mauro Vigorito": 66,
  "Como|Nikola Čavlina": 64,
  "Como|Adrian Lahdo": 63,
  "Como|Henrique Menke": 62,
  "Como|Noel Törnqvist": 62,

  // --- Cremonese ---
  "Cremonese|Jamie Vardy": 74,
  "Cremonese|Emil Audero": 73,
  "Cremonese|Federico Baschirotto": 73,
  "Cremonese|Sebastiano Luperto": 73,
  "Cremonese|Antonio Sanabria": 72,
  "Cremonese|Federico Bonazzoli": 72,
  "Cremonese|Martín Payero": 72,
  "Cremonese|Michele Collocolo": 71,
  "Cremonese|Morten Thorsby": 71,
  "Cremonese|Youssef Maleh": 71,
  "Cremonese|Warren Bondo": 71,
  "Cremonese|David Okereke": 70,
  "Cremonese|Faris Moumbagna": 70,
  "Cremonese|Alberto Grassi": 70,
  "Cremonese|Jari Vandeputte": 70,
  "Cremonese|Federico Ceccherini": 70,
  "Cremonese|Matteo Bianchetti": 70,
  "Cremonese|Mikayil Faye": 70,
  "Cremonese|Alessio Zerbin": 70,
  "Cremonese|Giuseppe Pezzella": 70,
  "Cremonese|Marco Silvestri": 70,
  "Cremonese|Milan Djurić": 69,
  "Cremonese|Tommaso Barbieri": 68,
  "Cremonese|Filippo Terracciano": 68,
  "Cremonese|Romano Floriani": 66,
  "Cremonese|Lapo Nava": 64,
  "Cremonese|Adrian Lickunas": 62,
  "Cremonese|Francesco Folino": 62,
  "Cremonese|Simone Lottici Tessadri": 62,
  "Cremonese|Adrián Malovec": 62,
  "Cremonese|Marco Cassin": 62,
  "Cremonese|Tommaso Vigilati": 62,
  "Cremonese|Davide Pavesi": 62,

  // --- Fiorentina ---
  "Fiorentina|Moise Kean": 82,
  "Fiorentina|David de Gea": 82,
  "Fiorentina|Albert Guðmundsson": 78,
  "Fiorentina|Nicolò Fagioli": 77,
  "Fiorentina|Dodô": 77,
  "Fiorentina|Robin Gosens": 77,
  "Fiorentina|Rolando Mandragora": 76,
  "Fiorentina|Luca Ranieri": 76,
  "Fiorentina|Pietro Comuzzo": 76,
  "Fiorentina|Marco Brescianini": 75,
  "Fiorentina|Giovanni Fabbian": 75,
  "Fiorentina|Marin Pongračić": 75,
  "Fiorentina|Daniele Rugani": 74,
  "Fiorentina|Jack Harrison": 74,
  "Fiorentina|Roberto Piccoli": 73,
  "Fiorentina|Manor Solomon": 73,
  "Fiorentina|Tariq Lamptey": 73,
  "Fiorentina|Jacopo Fazzini": 73,
  "Fiorentina|Fabiano Parisi": 72,
  "Fiorentina|Abdelhamid Sabiri": 71,
  "Fiorentina|Cher Ndour": 70,
  "Fiorentina|Mattia Viti": 70,
  "Fiorentina|Oliver Christensen": 70,
  "Fiorentina|Niccolò Fortini": 66,
  "Fiorentina|Eman Košpo": 64,
  "Fiorentina|Eddy Kouadio": 63,
  "Fiorentina|Luca Lezzerini": 63,
  "Fiorentina|Giorgio Puzzoli": 62,
  "Fiorentina|Riccardo Braschi": 62,
  "Fiorentina|Luis Balbo": 62,

  // --- Genoa ---
  "Genoa|Ruslan Malinovskyi": 76,
  "Genoa|Morten Frendrup": 76,
  "Genoa|Johan Vásquez": 75,
  "Genoa|Leo Østigård": 75,
  "Genoa|Vitinha": 73,
  "Genoa|Nicola Leali": 73,
  "Genoa|Aarón Martín": 73,
  "Genoa|Tommaso Baldanzi": 73,
  "Genoa|Lorenzo Colombo": 72,
  "Genoa|Jean Onana": 72,
  "Genoa|Junior Messias": 72,
  "Genoa|Maxwel Cornet": 72,
  "Genoa|Justin Bijlow": 72,
  "Genoa|Brooke Norton-Cuffy": 71,
  "Genoa|Stefano Sabelli": 71,
  "Genoa|Caleb Ekuban": 70,
  "Genoa|Alessandro Marcandalli": 69,
  "Genoa|Mikael Egill Ellertsson": 68,
  "Genoa|Jeff Ekhator": 66,
  "Genoa|Sebastian Otoa": 66,
  "Genoa|Amorim": 66,
  "Genoa|Benjamin Siegrist": 66,
  "Genoa|Patrizio Masini": 65,
  "Genoa|Nils Zätterström": 63,
  "Genoa|Daniel Ndulue": 62,
  "Genoa|Elia Spicuglia": 62,
  "Genoa|Joi Nuredini": 62,
  "Genoa|Filippo Carbone": 62,
  "Genoa|Jacopo Grossi": 62,
  "Genoa|Lukas Klišys": 62,
  "Genoa|Daniele Sommariva": 62,
  "Genoa|Ernestas Lysionok": 62,
  "Genoa|Rendijs Mihelsons": 62,
  "Genoa|Latif Ouedraogo": 62,
  "Genoa|Kris Gecaj": 62,
  "Genoa|Mamedi Doucouré": 62,

  // --- Hellas Verona ---
  "Hellas Verona|Sandi Lovrič": 73,
  "Hellas Verona|Tomáš Suslov": 73,
  "Hellas Verona|Suat Serdar": 72,
  "Hellas Verona|Lorenzo Montipò": 72,
  "Hellas Verona|Amin Sarr": 71,
  "Hellas Verona|Gift Orban": 71,
  "Hellas Verona|Nicolás Valentini": 71,
  "Hellas Verona|Victor Nelsson": 71,
  "Hellas Verona|Pol Lirola": 71,
  "Hellas Verona|Abdou Harroui": 70,
  "Hellas Verona|Armel Bella-Kotchap": 70,
  "Hellas Verona|Roberto Gagliardini": 70,
  "Hellas Verona|Al-Musrati": 70,
  "Hellas Verona|Domagoj Bradarić": 69,
  "Hellas Verona|Kieron Bowie": 68,
  "Hellas Verona|Jean-Daniel Akpa Akpro": 68,
  "Hellas Verona|Rafik Belghali": 68,
  "Hellas Verona|Martin Frese": 68,
  "Hellas Verona|Daniel Oyegoke": 67,
  "Hellas Verona|Antoine Bernède": 65,
  "Hellas Verona|Cheikh Niasse": 65,
  "Hellas Verona|Daniel Mosquera": 64,
  "Hellas Verona|Junior Ajayi": 64,
  "Hellas Verona|Simone Perilli": 64,
  "Hellas Verona|Mel Akalé": 63,
  "Hellas Verona|Fallou Cham": 63,
  "Hellas Verona|Ioan Vermeșan": 62,
  "Hellas Verona|Isaac": 62,
  "Hellas Verona|Tobias Slotsager": 62,
  "Hellas Verona|William Feola": 62,
  "Hellas Verona|Luca Szimionaș": 62,
  "Hellas Verona|Jurgen Peci": 62,
  "Hellas Verona|Arthur Borghi": 62,
  "Hellas Verona|Giacomo Toniolo": 62,
  "Hellas Verona|Mirko Castagnini": 62,
  "Hellas Verona|Andrej Popović": 62,
  "Hellas Verona|Davide De Battisti": 62,
  "Hellas Verona|Andrias Edmundsson": 62,
  "Hellas Verona|Luca Monticelli": 62,

  // --- Inter ---
  "Inter|Lautaro Martínez": 86,
  "Inter|Alessandro Bastoni": 85,
  "Inter|Federico Dimarco": 84,
  "Inter|Hakan Çalhanoğlu": 84,
  "Inter|Nicolò Barella": 85,
  "Inter|Marcus Thuram": 84,
  "Inter|Manuel Akanji": 83,
  "Inter|Denzel Dumfries": 82,
  "Inter|Yann Sommer": 80,
  "Inter|Francesco Acerbi": 77,
  "Inter|Piotr Zieliński": 76,
  "Inter|Davide Frattesi": 77,
  "Inter|Yann Bisseck": 77,
  "Inter|Henrikh Mkhitaryan": 76,
  "Inter|Carlos Augusto": 76,
  "Inter|Stefan de Vrij": 75,
  "Inter|Francesco Pio Esposito": 76,
  "Inter|Josep Martínez": 76,
  "Inter|Matteo Darmian": 75,
  "Inter|Petar Sučić": 74,
  "Inter|Ange-Yoan Bonny": 74,
  "Inter|Luis Henrique": 73,
  "Inter|Andy Diouf": 70,
  "Inter|Raffaele Di Gennaro": 66,

  // --- Juventus ---
  "Juventus|Bremer": 84,
  "Juventus|Kenan Yıldız": 83,
  "Juventus|Dušan Vlahović": 82,
  "Juventus|Andrea Cambiaso": 80,
  "Juventus|Loïs Openda": 79,
  "Juventus|Jonathan David": 79,
  "Juventus|Francisco Conceição": 79,
  "Juventus|Khéphren Thuram": 79,
  "Juventus|Federico Gatti": 79,
  "Juventus|Michele Di Gregorio": 79,
  "Juventus|Teun Koopmeiners": 78,
  "Juventus|Manuel Locatelli": 78,
  "Juventus|Pierre Kalulu": 78,
  "Juventus|Weston McKennie": 77,
  "Juventus|Edon Zhegrova": 75,
  "Juventus|Mattia Perin": 74,
  "Juventus|Lloyd Kelly": 74,
  "Juventus|Fabio Miretti": 73,
  "Juventus|Juan Cabal": 73,
  "Juventus|Filip Kostić": 73,
  "Juventus|Emil Holm": 73,
  "Juventus|Jérémie Boga": 71,
  "Juventus|Arkadiusz Milik": 70,
  "Juventus|Vasilije Adžić": 66,
  "Juventus|Carlo Pinsoglio": 63,

  // --- Lazio ---
  "Lazio|Mattia Zaccagni": 80,
  "Lazio|Nicolò Rovella": 79,
  "Lazio|Alessio Romagnoli": 78,
  "Lazio|Mario Gila": 78,
  "Lazio|Ivan Provedel": 78,
  "Lazio|Pedro": 76,
  "Lazio|Danilo Cataldi": 75,
  "Lazio|Gustav Isaksen": 75,
  "Lazio|Nuno Tavares": 75,
  "Lazio|Boulaye Dia": 74,
  "Lazio|Adam Marušić": 74,
  "Lazio|Kenneth Taylor": 74,
  "Lazio|Patric Gabarrón": 73,
  "Lazio|Manuel Lazzari": 73,
  "Lazio|Daniel Maldini": 73,
  "Lazio|Tijjani Noslin": 72,
  "Lazio|Reda Belahyane": 72,
  "Lazio|Samuel Gigot": 72,
  "Lazio|Matteo Cancellieri": 72,
  "Lazio|Fisayo Dele-Bashiru": 72,
  "Lazio|Luca Pellegrini": 71,
  "Lazio|Elseid Hysaj": 70,
  "Lazio|Toma Bašić": 69,
  "Lazio|Oliver Provstgaard": 68,
  "Lazio|Petar Ratkov": 66,
  "Lazio|Alessio Furlanetto": 65,
  "Lazio|Adrian Przyborek": 63,
  "Lazio|Saná Fernandes": 62,
  "Lazio|Edoardo Motta": 62,

  // --- Lecce ---
  "Lecce|Wladimiro Falcone": 74,
  "Lecce|Ylber Ramadani": 73,
  "Lecce|Lassana Coulibaly": 72,
  "Lecce|Francesco Camarda": 71,
  "Lecce|Walid Cheddira": 71,
  "Lecce|Kialonda Gaspar": 71,
  "Lecce|Lameck Banda": 71,
  "Lecce|Riccardo Sottil": 71,
  "Lecce|Antonino Gallo": 71,
  "Lecce|Medon Berisha": 70,
  "Lecce|Tiago Gabriel": 70,
  "Lecce|Santiago Pierotti": 70,
  "Lecce|Nikola Štulić": 69,
  "Lecce|Álex Sala": 69,
  "Lecce|Omri Gandelman": 69,
  "Lecce|Þórir Jóhann Helgason": 69,
  "Lecce|Jamil Siebert": 69,
  "Lecce|Christian Früchtl": 69,
  "Lecce|Filip Marchwiński": 68,
  "Lecce|Matías Pérez": 66,
  "Lecce|Konan N'Dri": 66,
  "Lecce|Danilo Veiga": 66,
  "Lecce|Corrie Ndaba": 66,
  "Lecce|Daniele Bleve": 64,
  "Lecce|Gaby Jean": 63,
  "Lecce|Niko Kovač": 63,
  "Lecce|Oumar Ngom": 63,
  "Lecce|Sadik Fofana": 63,
  "Lecce|Fabiano Pacia": 63,
  "Lecce|Paco Esteban": 62,
  "Lecce|Jasper Samooja": 62,
  "Lecce|Plamen Penev": 62,
  "Lecce|Olaf Gorter": 62,

  // --- Milan ---
  "Milan|Luka Modrić": 85,
  "Milan|Mike Maignan": 85,
  "Milan|Rafael Leão": 84,
  "Milan|Christian Pulisic": 84,
  "Milan|Adrien Rabiot": 82,
  "Milan|Fikayo Tomori": 80,
  "Milan|Christopher Nkunku": 79,
  "Milan|Strahinja Pavlović": 78,
  "Milan|Youssouf Fofana": 78,
  "Milan|Santiago Giménez": 77,
  "Milan|Samuele Ricci": 77,
  "Milan|Alexis Saelemaekers": 77,
  "Milan|Pervis Estupiñán": 77,
  "Milan|Ardon Jashari": 76,
  "Milan|Matteo Gabbia": 76,
  "Milan|Ruben Loftus-Cheek": 76,
  "Milan|Koni De Winter": 75,
  "Milan|Niclas Füllkrug": 74,
  "Milan|Davide Bartesaghi": 72,
  "Milan|Zachary Athekame": 71,
  "Milan|Pietro Terracciano": 68,
  "Milan|David Odogu": 67,
  "Milan|Lorenzo Torriani": 65,

  // --- Napoli ---
  "Napoli|Kevin De Bruyne": 87,
  "Napoli|Scott McTominay": 84,
  "Napoli|André-Frank Zambo Anguissa": 82,
  "Napoli|Stanislav Lobotka": 82,
  "Napoli|Giovanni Di Lorenzo": 82,
  "Napoli|Romelu Lukaku": 81,
  "Napoli|Alessandro Buongiorno": 81,
  "Napoli|Amir Rrahmani": 80,
  "Napoli|David Neres": 80,
  "Napoli|Rasmus Højlund": 79,
  "Napoli|Matteo Politano": 79,
  "Napoli|Alex Meret": 78,
  "Napoli|Sam Beukema": 77,
  "Napoli|Leonardo Spinazzola": 76,
  "Napoli|Mathías Olivera": 76,
  "Napoli|Eljif Elmas": 76,
  "Napoli|Billy Gilmour": 75,
  "Napoli|Vanja Milinković-Savić": 75,
  "Napoli|Miguel Gutiérrez": 74,
  "Napoli|Juan Jesus": 72,
  "Napoli|Pasquale Mazzocchi": 71,
  "Napoli|Antonio Vergara": 68,
  "Napoli|Giovane": 68,
  "Napoli|Nikita Contini": 65,
  "Napoli|Alisson Santos": 65,

  // --- Parma ---
  "Parma|Zion Suzuki": 76,
  "Parma|Adrián Bernabé": 74,
  "Parma|Alessandro Circati": 73,
  "Parma|Gabriel Strefezza": 73,
  "Parma|Mateo Pellegrino": 72,
  "Parma|Gaetano Oristanio": 72,
  "Parma|Hans Nicolussi Caviglia": 72,
  "Parma|Mandela Keita": 72,
  "Parma|Enrico Delprato": 72,
  "Parma|Lautaro Valenti": 71,
  "Parma|Pontus Almqvist": 71,
  "Parma|Mariano Troilo": 70,
  "Parma|Nahuel Estévez": 70,
  "Parma|Benjamin Cremaschi": 70,
  "Parma|Jacob Ondrejka": 70,
  "Parma|Emanuele Valeri": 70,
  "Parma|Franco Carboni": 69,
  "Parma|Matija Frigan": 68,
  "Parma|Christian Ordóñez": 68,
  "Parma|Oliver Sørensen": 68,
  "Parma|Sascha Britschgi": 68,
  "Parma|Abdoulaye Ndiaye": 66,
  "Parma|Mama Opoku": 64,
  "Parma|Dominik Drobnič": 64,
  "Parma|Afonso Semedo": 63,
  "Parma|Bernardo Conde": 63,
  "Parma|Edoardo Corvi": 63,
  "Parma|Alessandro Mazzocchi": 62,

  // --- Pisa ---
  "Pisa|Calvin Stengs": 74,
  "Pisa|Michel Aebischer": 73,
  "Pisa|Juan Cuadrado": 72,
  "Pisa|Raúl Albiol": 72,
  "Pisa|Simone Canestrelli": 72,
  "Pisa|Simone Scuffet": 72,
  "Pisa|Samuel Iling-Junior": 71,
  "Pisa|Marius Marin": 71,
  "Pisa|Lisandru Tramoni": 70,
  "Pisa|Idrissa Touré": 70,
  "Pisa|Mehdi Léris": 70,
  "Pisa|Adrian Šemper": 70,
  "Pisa|Henrik Meister": 69,
  "Pisa|Stefano Moreo": 69,
  "Pisa|Ebenezer Akinsanmiro": 69,
  "Pisa|Antonio Caracciolo": 69,
  "Pisa|Felipe Loyola": 69,
  "Pisa|Rafiu Durosinmi": 68,
  "Pisa|Arturo Calabresi": 68,
  "Pisa|Samuele Angori": 68,
  "Pisa|Malthe Højholt": 67,
  "Pisa|Filip Stojilković": 66,
  "Pisa|İsak Vural": 66,
  "Pisa|Lorran": 66,
  "Pisa|Gabriele Piccinini": 64,
  "Pisa|Nícolas Andrade": 64,
  "Pisa|Daniel Denoon": 63,
  "Pisa|Francesco Coppola": 63,
  "Pisa|Lorenzo Tosi": 62,
  "Pisa|Matteo Luppichini": 62,
  "Pisa|Tommaso Guizzo": 62,
  "Pisa|Rosen Bozhinov": 62,
  "Pisa|Daniel Battistella": 62,
  "Pisa|Brando Bettazzi": 62,

  // --- Roma ---
  "Roma|Paulo Dybala": 82,
  "Roma|Mile Svilar": 82,
  "Roma|Manu Koné": 80,
  "Roma|Evan Ndicka": 79,
  "Roma|Gianluca Mancini": 78,
  "Roma|Lorenzo Pellegrini": 77,
  "Roma|Matías Soulé": 77,
  "Roma|Angeliño": 77,
  "Roma|Bryan Cristante": 76,
  "Roma|Donyell Malen": 76,
  "Roma|Artem Dovbyk": 75,
  "Roma|Wesley": 75,
  "Roma|Evan Ferguson": 74,
  "Roma|Neil El Aynaoui": 74,
  "Roma|Devyne Rensch": 74,
  "Roma|Kostas Tsimikas": 74,
  "Roma|Mario Hermoso": 74,
  "Roma|Stephan El Shaarawy": 73,
  "Roma|Zeki Çelik": 73,
  "Roma|Bryan Zaragoza": 72,
  "Roma|Daniele Ghilardi": 72,
  "Roma|Niccolò Pisilli": 71,
  "Roma|Pierluigi Gollini": 71,
  "Roma|Jan Ziółkowski": 69,
  "Roma|Robinio Vaz": 68,
  "Roma|Lorenzo Venturino": 63,
  "Roma|Antonio Arena": 62,
  "Roma|Radosław Żelezny": 62,

  // --- Sassuolo ---
  "Sassuolo|Domenico Berardi": 79,
  "Sassuolo|Armand Laurienté": 76,
  "Sassuolo|Kristian Thorstvedt": 74,
  "Sassuolo|Nemanja Matić": 74,
  "Sassuolo|Jay Idzes": 74,
  "Sassuolo|Ismaël Koné": 73,
  "Sassuolo|Daniel Boloca": 73,
  "Sassuolo|Arijanet Murić": 73,
  "Sassuolo|Cristian Volpato": 72,
  "Sassuolo|Aster Vranckx": 72,
  "Sassuolo|Tarik Muharemović": 72,
  "Sassuolo|Sebastian Walukiewicz": 72,
  "Sassuolo|Stefano Turati": 72,
  "Sassuolo|Josh Doig": 72,
  "Sassuolo|M'Bala Nzola": 71,
  "Sassuolo|Fali Candé": 70,
  "Sassuolo|Alieu Fadera": 70,
  "Sassuolo|Edoardo Iannoni": 69,
  "Sassuolo|Filippo Romagna": 69,
  "Sassuolo|Luca Moro": 68,
  "Sassuolo|Edoardo Pieragnolo": 68,
  "Sassuolo|Luca Lipani": 66,
  "Sassuolo|Pedro Felipe": 66,
  "Sassuolo|Giacomo Satalino": 64,
  "Sassuolo|Christian Frangella": 64,
  "Sassuolo|Giorgio Vezzosi": 64,
  "Sassuolo|Darryl Bakola": 63,
  "Sassuolo|Tommaso Macchioni": 63,
  "Sassuolo|Troy-Leo Tomșa": 62,
  "Sassuolo|Jeffrey Baffoh": 62,
  "Sassuolo|Gioele Zacchi": 62,

  // --- Torino ---
  "Torino|Guillermo Maripán": 75,
  "Torino|Duván Zapata": 74,
  "Torino|Giovanni Simeone": 74,
  "Torino|Ché Adams": 74,
  "Torino|Ivan Ilić": 74,
  "Torino|Saúl Coco": 74,
  "Torino|Nikola Vlašić": 74,
  "Torino|Cesare Casadei": 73,
  "Torino|Ardian Ismajli": 73,
  "Torino|Adrien Tameze": 72,
  "Torino|Valentino Lazaro": 72,
  "Torino|Zakaria Aboukhlal": 72,
  "Torino|Franco Israel": 72,
  "Torino|Cristiano Biraghi": 72,
  "Torino|Niels Nkounkou": 71,
  "Torino|Gvidas Gineitis": 70,
  "Torino|Saba Sazonov": 70,
  "Torino|Matteo Prati": 70,
  "Torino|Tino Anjorin": 70,
  "Torino|Marcus Holmgren Pedersen": 70,
  "Torino|Alieu Eybi Njie": 69,
  "Torino|Enzo Ebosse": 69,
  "Torino|Emirhan İlkhan": 68,
  "Torino|Rafael Obrador": 68,
  "Torino|Luca Marianucci": 68,
  "Torino|Alberto Andrea Paleari": 68,
  "Torino|Sandro Kulenović": 66,
  "Torino|Sergiu Perciun": 63,
  "Torino|Zanos Savva": 63,
  "Torino|Wisdom Acquah": 63,
  "Torino|Tommaso Gabellini": 62,
  "Torino|Mattia Pellini": 62,
  "Torino|Lapo Siviero": 62,

  // --- Udinese ---
  "Udinese|Oumar Solet": 77,
  "Udinese|Nicolò Zaniolo": 74,
  "Udinese|Maduka Okoye": 74,
  "Udinese|Hassane Kamara": 74,
  "Udinese|Jesper Karlström": 73,
  "Udinese|Arthur Atta": 72,
  "Udinese|Jurgen Ekkelenkamp": 72,
  "Udinese|Keinan Davis": 72,
  "Udinese|Christian Kabasele": 72,
  "Udinese|Alessandro Zanoli": 72,
  "Udinese|Adam Buksa": 71,
  "Udinese|Nicolò Bertola": 71,
  "Udinese|Thomas Kristensen": 71,
  "Udinese|Jordan Zemura": 71,
  "Udinese|Lennon Miller": 70,
  "Udinese|Vakoun Bayo": 70,
  "Udinese|Kingsley Ehizibue": 70,
  "Udinese|Răzvan Sava": 70,
  "Udinese|Oier Zarraga": 70,
  "Udinese|Idrissa Gueye": 68,
  "Udinese|Abdoulaye Camara": 66,
  "Udinese|Juan David Arizala": 64,
  "Udinese|Daniele Padelli": 64,
  "Udinese|Alessandro Nunziante": 62,
};
