import type { ShowcaseLeague } from "./types";

/**
 * **Eredivisie 2025/26** — il campionato in cui i Big 5 vanno a prendere i ventenni.
 *
 * Profilo diverso da quello portoghese e per questo utile: qui i talenti sono quasi tutti
 * *prodotti in casa*, giovanissimi e con potenziale alto, mentre in Primeira Liga arrivano già
 * comprati dal Sudamerica. Per il mercato della DS mode significa un bacino di under 23 che
 * altrove non c'è.
 *
 * Banda dichiarata **62-82**: un punto sotto la Primeira Liga, coerente con la differenza reale
 * fra i due campionati nelle coppe europee.
 */
export const PAESI_BASSI: ShowcaseLeague = {
  name: "Eredivisie",
  nation: "Paesi Bassi",
  prestigeTier: 3,
  overallRange: [62, 82],
  clubs: [
    {
      name: "Ajax",
      prestigeTier: 4,
      players: [
        { name: "Vítězslav Jaroš", nation: "Rep. Ceca", birthDate: "2001-07-23", role: "POR", overall: 74 },
        { name: "Maarten Paes", nation: "Paesi Bassi", birthDate: "1998-05-14", role: "POR", overall: 72 },
        { name: "Ko Itakura", nation: "Giappone", birthDate: "1997-01-27", role: "DC", overall: 79 },
        { name: "Josip Šutalo", nation: "Croazia", birthDate: "2000-02-28", role: "DC", overall: 75 },
        { name: "Takehiro Tomiyasu", nation: "Giappone", birthDate: "1998-11-05", role: "DC", secondaryRoles: ["TD"], overall: 74 },
        { name: "Youri Baas", nation: "Paesi Bassi", birthDate: "2003-03-17", role: "DC", secondaryRoles: ["TS"], overall: 73 },
        { name: "Anton Gaaei", nation: "Danimarca", birthDate: "2002-11-19", role: "TD", secondaryRoles: ["QD"], overall: 71 },
        { name: "Lucas Rosa", nation: "Brasile", birthDate: "2000-04-03", role: "TD", secondaryRoles: ["QD"], overall: 71 },
        { name: "Oleksandr Zinchenko", nation: "Ucraina", birthDate: "1996-12-15", role: "TS", secondaryRoles: ["MED"], overall: 76 },
        { name: "Owen Wijndal", nation: "Paesi Bassi", birthDate: "1999-11-28", role: "TS", secondaryRoles: ["QS"], overall: 73 },
        { name: "Davy Klaassen", nation: "Paesi Bassi", birthDate: "1993-02-21", role: "CC", overall: 73 },
        { name: "Youri Regeer", nation: "Paesi Bassi", birthDate: "2003-08-18", role: "MED", secondaryRoles: ["TD"], overall: 72 },
        { name: "Kian Fitz-Jim", nation: "Paesi Bassi", birthDate: "2003-07-05", role: "CC", overall: 71 },
        { name: "Maximilian Ibrahimović", nation: "Svezia", birthDate: "2006-09-22", role: "CC", overall: 68 },
        { name: "Oscar Gloukh", nation: "Israele", birthDate: "2004-04-01", role: "TRQ", secondaryRoles: ["TQS"], overall: 76 },
        { name: "Steven Berghuis", nation: "Paesi Bassi", birthDate: "1991-12-19", role: "TQD", secondaryRoles: ["TRQ"], overall: 76 },
        { name: "Mika Godts", nation: "Belgio", birthDate: "2005-06-07", role: "TQS", overall: 75 },
        { name: "Oliver Edvardsen", nation: "Norvegia", birthDate: "1999-03-19", role: "TQD", overall: 73 },
        { name: "Maher Carrizo", nation: "Argentina", birthDate: "2006-02-19", role: "TQD", overall: 71 },
        { name: "Rayane Bounida", nation: "Belgio", birthDate: "2006-03-03", role: "TRQ", overall: 70 },
        { name: "Wout Weghorst", nation: "Paesi Bassi", birthDate: "1992-08-07", role: "ATT", overall: 76 },
        { name: "Kasper Dolberg", nation: "Danimarca", birthDate: "1997-10-06", role: "ATT", overall: 75 },
        { name: "Don-Angelo Konadu", nation: "Paesi Bassi", birthDate: "2006-05-03", role: "ATT", overall: 68 },
      ],
    },
    {
      name: "PSV Eindhoven",
      prestigeTier: 4,
      players: [
        { name: "Matěj Kovář", nation: "Rep. Ceca", birthDate: "2000-05-17", role: "POR", overall: 78 },
        { name: "Nick Olij", nation: "Paesi Bassi", birthDate: "1995-08-01", role: "POR", overall: 72 },
        { name: "Armando Obispo", nation: "Curaçao", birthDate: "1999-03-05", role: "DC", overall: 74 },
        { name: "Ryan Flamingo", nation: "Paesi Bassi", birthDate: "2002-12-31", role: "DC", overall: 74 },
        { name: "Yarek Gasiorowski", nation: "Spagna", birthDate: "2005-01-12", role: "DC", secondaryRoles: ["TS"], overall: 72 },
        { name: "Sergiño Dest", nation: "Stati Uniti", birthDate: "2000-11-03", role: "TD", secondaryRoles: ["QD"], overall: 77 },
        { name: "Kiliann Sildillia", nation: "Francia", birthDate: "2002-05-16", role: "TD", secondaryRoles: ["QD"], overall: 74 },
        { name: "Anass Salah-Eddine", nation: "Marocco", birthDate: "2002-01-18", role: "TS", secondaryRoles: ["QS"], overall: 74 },
        { name: "Mauro Júnior", nation: "Brasile", birthDate: "1999-05-06", role: "TS", secondaryRoles: ["QS"], overall: 73 },
        { name: "Jerdy Schouten", nation: "Paesi Bassi", birthDate: "1997-01-12", role: "MED", overall: 79 },
        { name: "Joey Veerman", nation: "Paesi Bassi", birthDate: "1998-11-19", role: "CC", overall: 79 },
        { name: "Ismael Saibari", nation: "Marocco", birthDate: "2001-01-28", role: "CC", secondaryRoles: ["TRQ"], overall: 78 },
        { name: "Guus Til", nation: "Paesi Bassi", birthDate: "1997-12-22", role: "CC", overall: 75 },
        { name: "Paul Wanner", nation: "Austria", birthDate: "2005-12-23", role: "TRQ", overall: 77 },
        { name: "Ivan Perišić", nation: "Croazia", birthDate: "1989-02-02", role: "TQS", secondaryRoles: ["ES"], overall: 78 },
        { name: "Dennis Man", nation: "Romania", birthDate: "1998-08-26", role: "TQD", overall: 76 },
        { name: "Ruben van Bommel", nation: "Paesi Bassi", birthDate: "2004-08-03", role: "TQS", overall: 74 },
        { name: "Couhaib Driouech", nation: "Paesi Bassi", birthDate: "2002-04-17", role: "TQD", overall: 72 },
        { name: "Esmir Bajraktarević", nation: "Bosnia ed Erzegovina", birthDate: "2005-03-10", role: "TQD", overall: 70 },
        { name: "Ricardo Pepi", nation: "Stati Uniti", birthDate: "2003-01-09", role: "ATT", overall: 77 },
        { name: "Alassane Pléa", nation: "Francia", birthDate: "1993-03-10", role: "ATT", overall: 75 },
        { name: "Myron Boadu", nation: "Paesi Bassi", birthDate: "2001-01-14", role: "ATT", overall: 72 },
      ],
    },
    {
      name: "Feyenoord",
      prestigeTier: 3,
      players: [
        { name: "Timon Wellenreuther", nation: "Germania", birthDate: "1995-12-03", role: "POR", overall: 76 },
        { name: "Steven Benda", nation: "Germania", birthDate: "1998-10-01", role: "POR", overall: 71 },
        { name: "Anel Ahmedhodžić", nation: "Bosnia ed Erzegovina", birthDate: "1999-03-26", role: "DC", overall: 76 },
        { name: "Tsuyoshi Watanabe", nation: "Giappone", birthDate: "1997-02-05", role: "DC", overall: 74 },
        { name: "Gernot Trauner", nation: "Austria", birthDate: "1992-03-25", role: "DC", overall: 74 },
        { name: "Thomas Beelen", nation: "Paesi Bassi", birthDate: "2001-06-11", role: "DC", overall: 73 },
        { name: "Jerry St. Juste", nation: "Paesi Bassi", birthDate: "1996-10-19", role: "DC", overall: 72 },
        { name: "Givairo Read", nation: "Paesi Bassi", birthDate: "2006-06-02", role: "TD", secondaryRoles: ["QD"], overall: 73 },
        { name: "Jordan Lotomba", nation: "Svizzera", birthDate: "1998-09-29", role: "TD", secondaryRoles: ["QD"], overall: 72 },
        { name: "Bart Nieuwkoop", nation: "Paesi Bassi", birthDate: "1996-03-07", role: "TD", secondaryRoles: ["QD"], overall: 71 },
        { name: "Jordan Bos", nation: "Australia", birthDate: "2002-10-29", role: "TS", secondaryRoles: ["QS"], overall: 74 },
        { name: "Gijs Smal", nation: "Paesi Bassi", birthDate: "1997-08-31", role: "TS", secondaryRoles: ["QS"], overall: 72 },
        { name: "Hwang In-Beom", nation: "Corea del Sud", birthDate: "1996-09-20", role: "MED", secondaryRoles: ["CC"], overall: 76 },
        { name: "Jakub Moder", nation: "Polonia", birthDate: "1999-04-07", role: "CC", overall: 75 },
        { name: "Luciano Valente", nation: "Paesi Bassi", birthDate: "2003-10-04", role: "CC", overall: 73 },
        { name: "Oussama Targhalline", nation: "Marocco", birthDate: "2002-05-20", role: "MED", overall: 72 },
        { name: "Sem Steijn", nation: "Paesi Bassi", birthDate: "2001-11-17", role: "TRQ", secondaryRoles: ["CC"], overall: 77 },
        { name: "Raheem Sterling", nation: "Inghilterra", birthDate: "1994-12-08", role: "TQD", secondaryRoles: ["TQS"], overall: 78 },
        { name: "Anis Hadj Moussa", nation: "Algeria", birthDate: "2002-02-11", role: "TQD", overall: 74 },
        { name: "Leo Sauer", nation: "Slovacchia", birthDate: "2005-12-16", role: "TQS", overall: 72 },
        { name: "Gonçalo Borges", nation: "Portogallo", birthDate: "2001-03-29", role: "TQS", overall: 72 },
        { name: "Ayase Ueda", nation: "Giappone", birthDate: "1998-08-28", role: "ATT", overall: 77 },
        { name: "Casper Tengstedt", nation: "Danimarca", birthDate: "2000-06-01", role: "ATT", overall: 73 },
        { name: "Shaqueel van Persie", nation: "Paesi Bassi", birthDate: "2006-11-16", role: "ATT", overall: 68 },
      ],
    },
    {
      name: "AZ Alkmaar",
      prestigeTier: 3,
      players: [
        { name: "Rome-Jayden Owusu-Oduro", nation: "Paesi Bassi", birthDate: "2004-07-02", role: "POR", overall: 74 },
        { name: "Jeroen Zoet", nation: "Paesi Bassi", birthDate: "1991-01-06", role: "POR", overall: 70 },
        { name: "Wouter Goes", nation: "Paesi Bassi", birthDate: "2004-06-10", role: "DC", overall: 74 },
        { name: "Maxim Dekker", nation: "Paesi Bassi", birthDate: "2004-04-21", role: "DC", overall: 73 },
        { name: "Alexandre Penetra", nation: "Portogallo", birthDate: "2001-09-09", role: "DC", overall: 72 },
        { name: "Andrea Natali", nation: "Italia", birthDate: "2008-01-28", role: "DC", overall: 64 },
        { name: "Seiya Maikuma", nation: "Giappone", birthDate: "1997-10-16", role: "TD", secondaryRoles: ["QD"], overall: 71 },
        { name: "Denso Kasius", nation: "Paesi Bassi", birthDate: "2002-10-06", role: "TD", secondaryRoles: ["QD"], overall: 70 },
        { name: "Mateo Chávez", nation: "Messico", birthDate: "2004-05-12", role: "TS", secondaryRoles: ["QS"], overall: 71 },
        { name: "Mees de Wit", nation: "Paesi Bassi", birthDate: "1998-04-17", role: "TS", secondaryRoles: ["QS"], overall: 71 },
        { name: "Peer Koopmeiners", nation: "Paesi Bassi", birthDate: "2000-05-04", role: "CC", overall: 73 },
        { name: "Jordy Clasie", nation: "Paesi Bassi", birthDate: "1991-06-27", role: "MED", overall: 72 },
        { name: "Kees Smit", nation: "Paesi Bassi", birthDate: "2006-01-20", role: "CC", overall: 72 },
        { name: "Matěj Šín", nation: "Rep. Ceca", birthDate: "2004-06-02", role: "CC", overall: 70 },
        { name: "Sven Mijnans", nation: "Paesi Bassi", birthDate: "2000-03-09", role: "TRQ", secondaryRoles: ["CC"], overall: 76 },
        { name: "Weslley Patati", nation: "Brasile", birthDate: "2003-10-01", role: "TQD", overall: 73 },
        { name: "Ibrahim Sadiq", nation: "Ghana", birthDate: "2000-05-07", role: "TQS", overall: 73 },
        { name: "Isak Jensen", nation: "Danimarca", birthDate: "2003-12-23", role: "TQD", overall: 70 },
        { name: "Ro-Zangelo Daal", nation: "Paesi Bassi", birthDate: "2004-02-10", role: "TQS", overall: 69 },
        { name: "Ayoub Oufkir", nation: "Paesi Bassi", birthDate: "2006-01-04", role: "TQD", overall: 68 },
        { name: "Troy Parrott", nation: "Irlanda", birthDate: "2002-02-04", role: "ATT", overall: 77 },
        { name: "Mexx Meerdink", nation: "Paesi Bassi", birthDate: "2003-07-24", role: "ATT", overall: 72 },
        { name: "Jizz Hornkamp", nation: "Paesi Bassi", birthDate: "1998-03-07", role: "ATT", overall: 70 },
      ],
    },
  ],
};
